### ISSUE TITLE
[Bug]: `isRouteErrorResponse` returns `false` with the error thrown inside the `Promise` in the deferred route loader

### ISSUE THREAD

**Issue by PhanDungTri** [remix-run/react-router#10097]
### What version of React Router are you using?

6.8.1

### Steps to Reproduce

Create a deferred route loader that returns a Promise which has an error thrown inside it.

```typescript
const deferredLoader = () => {
  const completed = (async () => {
    await wait(5000);

    throw new Response("", { status: 500, statusText: "Loader error" });

    return true;
  })();

  return defer({ completed });
};
```

Create an `ErrorPage` that receives the error and shows that error message.

```tsx
const ErrorPage = () => {
  const error = useRouteError();

  return (
    <div>
      {isRouteErrorResponse(error) ? error.statusText : "Unexpected error"}
    </div>
  );
};
```

Reproduced demo: https://codesandbox.io/s/ecstatic-artem-cfe543?file=/src/router.tsx:284-506

### Expected Behavior

Error page should show "Loader error"

### Actual Behavior

Error page shows "Unexpected error" instead

**Comment by domosedov** [comment]
you are not using Response correctly

```ts
const deferredLoader = () => {
  const completed = (async () => {
    await wait(5000);

    // throw new Response("", { status: 500, statusText: "Loader error" });
    throw new Error('some error');

    return true;
  })();

  return defer({ completed }); // or throw new Response("", { status: 500, statusText: "Loader error" });
};
```

**Comment by bhoop** [comment]
@PhanDungTri I asked about this in the [Discord channel](https://discord.com/channels/770287896669978684/1081340349819125910/1081340349819125910) and received a response pointing me to a new section in the React Router docs:

[Why don't Response objects returned by the loader work anymore?](https://reactrouter.com/en/main/guides/deferred#why-dont-response-objects-returned-by-the-loader-work-anymore)
> When you use defer, you're telling React Router to load the page immediately, without the deferred data. The page is already loaded before the Response object is returned so responses are not automatically processed in the same way as if you had done return fetch(url).
> 
> Therefore, you will need to handle your own Response processing and resolve your deferred Promise with data, not a Response instance.

I'm not sure why _thrown_ responses can't still be wrapped by React Router so that `isRouteErrorResponse()` still works, but I'm sure there's a reason. Regardless, I've been able to work around it by creating and throwing my own [`ErrorResponse`](https://github.com/remix-run/react-router/blob/main/packages/router/utils.ts#L1376) objects in the loader:

```
// instead of throwing this in deferredLoader()...
throw new Response("", { status: 500, statusText: "Loader error" });
...
isRouteErrorResponse( error ) // false

// throw this (or create your own ErrorResponse class):
throw { data: "", internal: false, status: 500, statusText: "Loader error" };
...
isRouteErrorResponse( error ) // true!
```

**Comment by brophdawg11** [comment]
As @bhoop commented, this is working as intended.  The best way to think about it is that a loader returns a _single thing_ which is then potentially post-processed by React Router.  In this case, React Router post-processes the `defer()` value but from that point on it's just a `Promise`.  The eventual resolved/rejected value is handed to your `Await` verbatim.
