### ISSUE TITLE
[Bug]: Routes with partial dynamic parameters have lost priority

### ISSUE THREAD

**Issue by l-Nuril-l** [remix-run/react-router#10163]
### What version of React Router are you using?

v6.8.1

### Steps to Reproduce

Routes with partial dynamic parameters have lost priority after update
```
<Route path=':id' element={<Profile />} />
<Route path="audios:id" element={<Audio />} />
```
```
http://localhost:3000/audios1
[v6.4.5] <Route path="audios:id" element={<Audio />} />
[v6.5.0-latest] <Route path=':id' element={<Profile />} />
```

### Expected Behavior

`<Route path="audios:id" element={<Audio />} />`

### Actual Behavior

`<Route path=':id' element={<Profile />} />`

**Comment by brophdawg11** [comment]
Partial dynamic parameters only worked due to an underlying bug and were never supposed to match (and weren't documented as a supported approach).  This underlying bug was fixed in [6.5.0](https://github.com/remix-run/react-router/releases/tag/react-router%406.5.0) to align with how splat parameters work.  You can extract the static portion from `useParams` and render the appropriate element accordingly:

```jsx
// <Route path=':id' element={<AudioOrProfile />} />

function AudioOrProfile() {
  let params = useParams();
  return params.id.startsWith("audios") ?
    <Audio id={params.id.replace(/^audios/, "") /> :
    <Profile />
}
```

**Comment by magicdawn** [comment]
+1 on this feature(undo the underlying bugfix

**Comment by foucdeg** [comment]
I'm upgrading from v5, a few dozen hours into it, and discovering this now.

Please note that the upgrade docs, while they do warn that _regexp_ dynamic params are no longer supported, don't mention anything about _partial_ dynamic params.

Due to the number and complexity of partial dynamic parameters I need to keep (in order to avoid changing user-facing URLs which would have a SEO impact of tens of thousands of €), the proposed workaround basically means that I need to write a home-made subrouter for these URLs, probably using the path-to-regexp lib.

@brophdawg11 please reopen for discussion - at least to update docs.

**Comment by extendself** [comment]
@foucdeg i have same problem.
