### ISSUE TITLE
Look into fetcher revalidation cancellation issue

### ISSUE THREAD

**Issue by brophdawg11** [remix-run/react-router#10238]
There seem to be some edge cases where we're not properly cancelling pending revalidations triggered by `fetcher.submit` calls. 

**Scenario 1**
1. `fetcherA.submit()` called
2. `fetcherA` action completes
3. `fetcherA` revalidates active loaders
4. `fetcherB.submit()` called during `fetcherA` revalidation
   * ❌ This should abort the fetcherA revalidation but it doesn't
5. `fetcherB` action completes
6. `fetcherB` revalidates active loaders

**Scenario 2**
1. `fetcherA.submit()` called
2. `fetcherB.submit()` called before `fetcherA` action completes
   * ❌ This should abort the eventual `fetcherA` revalidation but it doesn't
4. `fetcherA` action completes
   * ❌ Should not revalidate because it's been aborted
* `fetcherB` action completes
* `fetcherB` revalidates active loaders

Reproduction Repo: https://github.com/nicholaschiang/fetchers
Discord Thread: https://discord.com/channels/770287896669978684/1083562895423590400/1083876078214455417

**Comment by ryanflorence** [comment]
The revalidation is working as designed right now.

At step (4) we want to allow the other fetcher's revalidation so that we "commit along the way". That revalidation is the freshest possible state from the server, so we should commit it.

Imagine a simple list of checkboxes, all with their own fetcher. If every checkbox POST cancelled every previous fetcher's revalidation, then we are putting every checkbox into a pending state until the final checkbox completes.

We don't need to throw away those previous revalidations because they contain the freshest data from the server.

We have a test for this case:

```
describe(`
  A) POST /foo |---[A]------O
  B) POST /foo   |-----[A,B]---O
`, () => {
  // ...
}
```

1. A post goes out for fetcher `(A)`, completes, and a revalidation is started that we know contains the mutation for `[A]`'s new state.
2. A post goes out for fetcher `(B)` while the `(A)` revalidation is in flight. The post completes and a revalidation is sent out. We know the server state at that point will send back the new states for both `[A,B]`.

Now this part is the race. If `[A]` lands first, that's good state. We want to commit it because it contains the new `[A]` state. Even though we know `[A,B]` is coming, we can still commit `[A]`, it's not stale yet. That's what the test shows.

But if `[A,B]` lands first, we will cancel the `[A]` revalidation because it's stale: it started earlier but will land later. We also have a test for this:

```
describe(`
  A) POST /foo |---[A]---------X
  B) POST /foo   |-----[A,B]---O
`, () => {
  // ...
}
```

You can see the `[A,B]` revalidation starts later but lands earlier, so we cancel `X` the `[A]` revalidation.
