### ISSUE TITLE
[Bug]: Location state type any 

### ISSUE THREAD

**Issue by simeng-li** [remix-run/react-router#10241]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

const { state } = useLocation() throws ts unsafe assignment error. 

### Expected Behavior

The state type defined in the Location should be unknown.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/36393111/226614173-2ca79875-09df-484d-b72b-38f322490731.png">

### Actual Behavior

The state type defined in Location is any

https://github.com/remix-run/react-router/blob/main/packages/router/history.ts#L60

**Comment by timdorr** [comment]
@brophdawg11 Any reason we didn't replicate this from `history`: https://github.com/remix-run/history/blob/dev/packages/history/index.ts#L106

**Comment by brophdawg11** [comment]
Ah, took a while but was able to track down the reason for the change.  Seems that it was because `unknown` _forces_ the strictest type narrowing on everyone, even non-type-purists.  `any` is more flexible but doesn't prevent folks from going all in on type narrowing.   

https://github.com/remix-run/react-router/pull/8702#discussion_r819907643
