### ISSUE TITLE
[Bug]: Regression: path with two variables no longer matches

### ISSUE THREAD

**Issue by aeharding** [remix-run/react-router#10251]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

Use a route `path` equal to `":lat,:lon"`

```ts
<Route path="/:lat,:lon" element={<Test />} />
```

should match path = `43,-83`

observe it no longer matches.

https://stackblitz.com/edit/github-hqjpnf?file=src%2FApp.tsx (notice path = `/43,33` DOES NOT match `<About />`)

This was working in react-router 6.3.0:

https://stackblitz.com/edit/github-hqjpnf-67v23c?file=index.html (notice path = `/43,33` matches `<About />`)

### Expected Behavior

Should match and parse into two path params (`lat` and `lon`)

### Actual Behavior

Fails to match

**Comment by brophdawg11** [comment]
Unfortunately, this functionality was due to an underlying implementation bug and was never intended or documented to work as such.  We fixed it in 6.5.0 so dynamic parameters are the entire URL segment: https://github.com/remix-run/react-router/releases/tag/react-router%406.5.0.  

For this use-case, you can use a single dynamic parameter (`/:location`) and extract the `lat`/`lon` manually:

```js
let [lat, lon] = params.location.split(',')
```
