### ISSUE TITLE
[Bug]: Can't use debounce of lodash with Form React-router

### ISSUE THREAD

**Issue by tuan-dd** [remix-run/react-router#10263]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/118432439/227612319-acdf7126-a515-4861-a96a-bf48dceb5c06.png)
 -I have form to search movie
 
![image](https://user-images.githubusercontent.com/118432439/227612445-38a4094f-1f42-4a3d-b87f-98f332967db1.png)
 -I use  useSubmit()  to navigate component <Search>

![image](https://user-images.githubusercontent.com/118432439/227612715-a8076618-8d97-4385-8a4d-784252d7a45a.png)
 - I use loader to get parmas to get api data

### Expected Behavior

I have a Form to search for movies. Since the data api is too big to improve the UI UX , I use debounce  to delay action for router but not working. When I remove debounce ,it works normally 

### Actual Behavior

err : Uncaught TypeError: Cannot read properties of null (reading 'form')

example: https://codesandbox.io/s/staging-morning-9wx6ym

**Comment by brophdawg11** [comment]
You can't use `event.currentTarget` with `debounce` since it's only available during the lifetime of the `event`.  You'll need to use `event.target` for this use case:

https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

<img width="788" alt="Screenshot 2023-03-24 at 4 45 51 PM" src="https://user-images.githubusercontent.com/1609022/227636029-a588a739-0d86-4352-8bb8-66ddff83ef18.png">
