### ISSUE TITLE
[Bug]: RouterProvider shows fallbackElement instead of layout route 

### ISSUE THREAD

**Issue by Rinaldo** [remix-run/react-router#10295]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

[Live Demo](https://codesandbox.io/p/sandbox/react-router-issue-zqye8j?file=%252Fsrc%252FApp.tsx)

Start the app on the index route (Fast) and notice the app loads fine. Navigate to _Slow_ and notice a spinner is shown until the new page loads. Refresh the page and notice the layout route and its spinner are not shown until the child route is loaded.

### Expected Behavior

If I provide a layout route on the top level I expect `RouterProvider` to always show that route even if a child route is loading. I want to see the navbar on the first render even if the child route is still loading. I want the same loading experience whether I'm navigating to a lazy loaded page from within the app or from outside the app.

### Actual Behavior

When the app starts `RouterProvider` shows `fallbackElement` until all route matches have loaded. So if there is loading behavior defined in a layout component, none of that applies on the first load, it only applies in subsequent navigation.

**Comment by brophdawg11** [comment]
This is expected behavior.  All route loaders run in a parallel and on initial load the `fallbackElement` is shown until they all finish to prevent spinner waterfalls.  You can leverage the same UI components though so all you need to do is put the same `<Shell>` in the `fallbackElement`, which has access to all the same hooks such as `useNavigation`.

```
<RouterProvider router={router} fallbackElement={<Shell />} />
```

Demo: https://codesandbox.io/p/sandbox/react-router-issue-forked-e5q0sj

The other option is to use `defer` for your slow data and then the `Slow` loader will resolve immediately and you can get into your root layout.
