### ISSUE TITLE
[Bug]: Hydration fails

### ISSUE THREAD

**Issue by ecalcutin** [remix-run/react-router#10315]
### What version of React Router are you using?

18.2.0

### Steps to Reproduce

I followed the docs on https://reactrouter.com/en/main/guides/ssr  to make SSR.

I do not use loadable or lazy components.

```typescript
const render = async (request: Request): Promise<string> => {
    const sheet = new ServerStyleSheet();
    const cache = createCache();

    const fetchRequest = query(request);
    const handler = createStaticHandler(routes);

    const context = await handler.query(fetchRequest);
    if (context instanceof Response) {
        throw context;
    }
    let router = createStaticRouter(handler.dataRoutes, context);

    try {
        const body = renderToString(
            <StyleSheetManager sheet={sheet.instance}> // Ant SSR
                <StyleProvider cache={cache}> // styled-components SSR
                    <App> // App container with providers
                        <StaticRouterProvider
                            context={context}
                            router={router}
                        />
                    </App>
                </StyleProvider>
            </StyleSheetManager>
        );
        const styles = extractStyle(cache).concat(sheet.getStyleTags());
        const html = await hydrateHtml(styles, body);
        return html;
    } catch (e) {
        console.error(e);
        throw e;
    } finally {
        sheet.seal();
    }
};
```

### Expected Behavior

Should server render without errors

### Actual Behavior

I got the rendered HTML, but React complains that it can't hydrate:
- _Hydration failed because the initial UI does not match what was rendered on the server._ and 

- _There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering._

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/42963334/230432107-da819df2-4eac-4dc8-b836-6eb2b5c85e7f.png">

My assumptions are it fails because additional tags are inserted into DOM. How to deal with that?

**Comment by timdorr** [comment]
First, you should be using a development build of React when building locally. It will give you better error messages with more contextual information.

But in this case, the error isn't caused by that script tag. [We suppress that error specifically.](https://github.com/remix-run/react-router/blob/f85e0b33536645aa14c9d7cc6e3f9e09f63373da/packages/react-router-dom/server.tsx#L135). It's caused by some other area of your HTML output differing during the client render. A dev build of React may better be able to help you track that down.

**Comment by OliverJAsh** [comment]
I'm facing the same issue. It looks like the hydration mismatch _is_ caused by the `script` tag. The diff reported by React in development mode makes it very clear that the server included a `<script>` but the client did not.

> the error isn't caused by that script tag. [We suppress that error specifically.](https://github.com/remix-run/react-router/blob/f85e0b33536645aa14c9d7cc6e3f9e09f63373da/packages/react-router-dom/server.tsx#L135).

@timdorr If I understand correctly, `suppressHydrationWarning` will have no affect on client-side hydration because `StaticRouterProvider` is only used for the server render.

This feels related to [the other issue mentioned here regarding `useId`](https://github.com/remix-run/react-router/blob/2ac4f9b231d83ee391b94160021397161e5e586d/packages/react-router/lib/components.tsx#L452). It's not enough to render `null` though, because we still get hydration mismatches like this.

**Comment by OliverJAsh** [comment]
[Here's a reduced test case](https://stackblitz.com/edit/github-wawn2a72?file=src%2Fentry.server.tsx,src%2Fentry.client.tsx). The issue only reproduces when there's DOM elements wrapping the router, so I took the official [Data Router Server-side Rendering Example](https://github.com/remix-run/react-router/tree/main/examples/ssr-data-router) and modified it very slightly to wrap the router on client and server in a `<div>`. That's all I did.

```diff
   ReactDOM.hydrateRoot(
     document.getElementById('app')!,
     <React.StrictMode>
+      <div>
         <RouterProvider router={router} fallbackElement={null} />
+      </div>
     </React.StrictMode>
   );
```

```diff
   return ReactDOMServer.renderToString(
     <React.StrictMode>
+      <div>
         <StaticRouterProvider
           router={router}
           context={context}
           nonce="the-nonce"
         />
+      </div>
     </React.StrictMode>
   );
```
