### ISSUE TITLE
[Docs]: missing documentation for DataFunctionArgs.context

### ISSUE THREAD

**Issue by GideonMax** [remix-run/react-router#10366]
### Describe what's incorrect/missing in the documentation

Context is one of the arguments for loaders and actions.
Its type is any and it has no mention (as far as I can see) in the documentation.
This seems like an oversight, as I couldn't get context to be anything but undefined in all of my tests, so this might be a leftover type.

**Comment by jamalsoueidan** [comment]
Most of the documentation is missing types in the documentation, I have to dig inside the source to know the type.

```
loader: async ({ params }:????) => {
   return fetch(`/api/teams/${params.teamId}.json`);
},
```

**Comment by kiliman** [comment]
A lot of the data APIs were carried over from Remix. In Remix, the `context` passed to loaders and actions are provided by the `getLoadContext` function that's sent to the Remix handler on each request. This is an app-defined context, so the type is `AppContext`, which is essentially `any`, but you can override that. I'm unsure if React Router has this concept, so the type definitions may be a holdover from the code migration.

As for the `params` object, that's an object that includes keys for each dynamic param `:param` defined in your `<Route path>`. Again this is typed as `any` since these are extracted from string path definitions. Although I've seen some libraries that will generate static typing from your existing routes.

**Comment by brophdawg11** [comment]
`context` is not documented by design as it is not available for client-side `createBrowserRouter`.  It is only a hook used by Remix to pass information from your app server (think express `req`/`res`) into your route `loaders`/`actions`.

It can be used if you're doing manual [SSR](https://reactrouter.com/en/main/guides/ssr) via:

```ts
export async function render(req: express.Request) {
  let { query, dataRoutes } = createStaticHandler(routes);
  let remixRequest = createFetchRequest(request);
  let staticHandlerContext = await query(remixRequest, { 
    // Pass data from the express layer to the remix layer here
    requestContext: {
      dataFromExpressMiddleware: req.something
    }
 });
   ...
}
```

I'll look into adding a small blurb in the SSR docs around this 👍

**Comment by brophdawg11** [comment]
Docs added in https://github.com/remix-run/react-router/commit/24f80acb846299b4ef6b9176583d836009a494db
