### ISSUE TITLE
[Bug]: errorElement not being rendered

### ISSUE THREAD

**Issue by creativebay** [remix-run/react-router#10479]
### What version of React Router are you using?

6.11.1

### Steps to Reproduce

Pass custom error component as errorElement prop to Route component

### Expected Behavior

Custom error component is rendered on a Route level

### Actual Behavior

Custom error component is not rendered on the Route level, instead default react router error element is rendered on the root level.

The bug was introduced in 6.11.0 version and it's present in the 6.11.1 version as well:
https://stackblitz.com/edit/github-apayvk?file=src/app.tsx - 6.11.1
https://stackblitz.com/edit/github-apayvk-f653sv?file=src%2Fapp.tsx - 6.11.0

The bug does not exist in 6.10.0 version:
https://stackblitz.com/edit/github-apayvk-m5utbg?file=src/app.tsx - 6.10.0

**Comment by timdorr** [comment]
This is expected behavior and a regression that was fixed in 6.11. [As the docs indicate](https://reactrouter.com/en/main/route/error-element), `errorElement` only applies to data routers. When you use `<Routes>`, that is falling back to the old component Routers. They should have never shown the error element, but this is now fixed.
