### ISSUE TITLE
[Bug]: effect of [#10283]

### ISSUE THREAD

**Issue by ikangjie** [remix-run/react-router#10477]
### What version of React Router are you using?

6.11.x

### Steps to Reproduce

Hello, I have implemented a KeepAlive component using React router dom, which has the same functionality as the KeepAlive component in Vue. It is used to cache data from the previous page and will re render the latest data when new dependencies change. It ran stably before React router dom version 6.11.0, but after upgrading to version 6.11.0, these caching effects disappeared, The inability to render the latest data when new dependencies change has a significant impact on my project. I am currently unable to provide detailed reproduction steps, but I am certain it is related to the side effect of [#10283](https://github.com/remix-run/react-router/issues/10283) and hope to be fixed

### Expected Behavior

Components can be re rendered

### Actual Behavior

Component cannot be re rendered

**Comment by ikangjie** [comment]
![coder](https://github.com/remix-run/react-router/assets/48464397/9845a541-0466-4818-8454-98984261502a)

**Comment by brophdawg11** [comment]
I think we're going to need a simplified reproduction in order to investigate further.  There is too much going on in this screenshot that is outside the scope of `react-router-dom` and too little information about your router setup, such as `BrowserRouter` versus `RouterProvider` and `element` versus `Component` etc.
