### ISSUE TITLE
[Bug]: useNavigate() trims search params

### ISSUE THREAD

**Issue by LukaszNowakPL** [remix-run/react-router#10486]
### What version of React Router are you using?

6.10.0

### Steps to Reproduce

Once `useNavigate()` is called with search param ending with space, the space is not reflected into url in the browser.

### Expected Behavior

Search params are not trimmed.

Optionally - in order to being consistent with setter exposed by `useSearchParams()` hook - spaces are exchanged by `+` chars.

### Actual Behavior

```
const navigate = useNavigate();
const {search} = useLocation();

console.log(`_${search}_`); // Underscones for better space identification

const handleSearchSubmit = (value: string) => {
  console.log(`_${value}_`); // Underscones for better space identification
  navigate('/any-page?search=${value}`);
}
```

Calling `handleSearchSubmit` with value of `any ` (note the space at the end) ends up with `/any-page?search=any` url (with search param being trimmed).

After component rerender, the `search` part of `useLocation()` hook is printed into the console as `_?search=any_` (with no space at the end of search param.

**Comment by brophdawg11** [comment]
I'm not sure if this is really a bug, since this is all using built-in browser primitives under the hood and we're aiming to emulate the browser where we can.

Per the [URL spec](https://url.spec.whatwg.org/#concept-basic-url-parser) leading and trailing spaces are trimmed prior to creating a URL, so the spot at which we lose the space is when we create the URL for the `Request`.  This is also true if you were to `pushState` with a trailing space:

<img width="376" alt="Screenshot 2023-05-15 at 10 51 54 AM" src="https://github.com/remix-run/react-router/assets/1609022/102e1a45-c77f-47e6-bf21-267f5244190c">

`setSearchParams` is different and specifically works only with search params via the `URLSearchParams` constructor - which does encode spaces to `+`:

<img width="380" alt="Screenshot 2023-05-15 at 10 56 21 AM" src="https://github.com/remix-run/react-router/assets/1609022/b62254e9-3248-4070-958e-550180df7746">

If trailing spaces are important I'd suggest switching to `setSearchParams` if you're only setting params, or creating your own pre-encoded params before calling `navigate`:

```jsx
let sp = new URLSearchParams();
sp.append("key", "value ");
navigate(`?${sp.toString()}`);
```

**Comment by LukaszNowakPL** [comment]
I used that on our project. I just didn't know whether it was a workaround or a recommended way.

What do you think of providing this edge case in `useNavigate` docs (https://reactrouter.com/en/main/hooks/use-navigate)? I believe it would lower the confusion level as not only `space` is being trimmed, but also `%20` returned by `qs.stingify`.

**Comment by brophdawg11** [comment]
I think for now I'm going to hold off on adding this to the docs since (to my knowledge) this is the first time this has been raised and we can't afford to try to document all of the weird quirks with the spec in our own docs.  If this becomes a common-enough question I think it could warrant a call out in the docs so I'll keep an eye out if future issues are raised.  Thank you for the issue and reproduction!
