### ISSUE TITLE
[Bug]: Using HashRouter in the React project created by vite cannot achieve lazy routing loading

### ISSUE THREAD

**Issue by ueiheng** [remix-run/react-router#10509]
### What version of React Router are you using?

v6

### Steps to Reproduce

```jsx
import { HashRouter } from "react-router-dom";
import RouterView from "./router";
import { BrowserRouter } from 'react-router-dom';

function App() {
  return (
    <BrowserRouter>
      <RouterView></RouterView>
    </BrowserRouter>
  );
}

export default App;
```

When useing BrowserRouter. The above code can implement routing

```jsx
import { HashRouter } from "react-router-dom";
import RouterView from "./router";
import { BrowserRouter } from 'react-router-dom';

function App() {
  return (
    <HashRouter>
      <RouterView></RouterView>
    </HashRouter>
  );
}

export default App;
```

When I use HashRouter, I am unable to achieve lazy loading of routes and there are no errors reported on the console

So sorry! My personal abilities are limited, perhaps I overlooked a certain aspect of the problem. I look forward to your answer

### Expected Behavior

HashRouter uses routing lazy loading normally in React projects created by vite

### Actual Behavior

HashRouter cannot route lazy loading, but when I switch to BrowserRouter, I can perform route lazy loading.

**Comment by brophdawg11** [comment]
I'm not quite sure what the issue is you're describing - can you provide a simplified reproduction?  

If you're referring to [`Route.lazy`](https://reactrouter.com/en/main/route/lazy), then that only works when using a `RouterProvider` (see [picking a router docs](https://reactrouter.com/en/main/routers/picking-a-router)).

If you're referring to [`React.lazy`](https://react.dev/reference/react/lazy) then that should work in both since that's a React feature, not a React Router feature.

**Comment by ueiheng** [comment]
Thank you very much for your thoughtful answer. I have resolved this issue and it is not a bug. I will continue to improve my programming skills!
