### ISSUE TITLE
[Docs]: Comment bloc not showing correctly

### ISSUE THREAD

**Issue by hichemfantar** [remix-run/react-router#10533]
### Describe what's incorrect/missing in the documentation

Hovering over useNavigate shows:
![image](https://github.com/remix-run/react-router/assets/34947993/58c98893-3284-49c4-8dfb-4102996d4d67)

[Line](https://github.com/remix-run/react-router/blob/99768dfb987ad154b672a7f145622c37306741bc/packages/react-router/lib/hooks.tsx#LL171C60-L171C60) in docs.

**Comment by timdorr** [comment]
This isn't a React Router bug.

**Comment by kiliman** [comment]
I think this is a valid issue. The problem is that the JSDoc should be updated to use proper Markdown formatting, with backticks around JSX.

```md
/**
 * Returns an imperative method for changing the location. Used by `<Link>`s, but
 * may also be used by other elements to change the location.
```
This way it renders the reference to `<Link>` properly.
![image](https://github.com/remix-run/react-router/assets/47168/0c275f82-d3e1-40db-b4d3-57d3d85f4ea7)

**Comment by timdorr** [comment]
This is a display issue with VSCode. Markdown support was added way back in microsoft/vscode#1920, which causes these blocks to be interpreted as Markdown. However, that is not something [the TSDoc spec](https://github.com/microsoft/tsdoc/blob/main/tsdoc/src/beta/DeclarationReference.grammarkdown) makes a special accommodation for. 

This is not a problem with us, it's a problem with VSCode.

**Comment by kiliman** [comment]
I get that you're trying to keep the issues triaged, but closing out issues "just because" comes across as 😒

If you look at the JSDocs for the other functions in this repo, you'll see that 99% use the Markdown syntax. Only a handful appear to be missing.

The code lives in the world that is, not the world that we wished it would be (where VSCode didn't have this problem). Not sure why you can't just thank the guy and say we'd appreciate a PR.
