### ISSUE TITLE
[Bug]: createBrowserHistory creates history not behaving as expected

### ISSUE THREAD

**Issue by spicylemonhaha** [remix-run/react-router#10572]
### What version of React Router are you using?

"@remix-run/router": "^1.6.1"

### Steps to Reproduce

The history created by createBrowserHistory, when I use history.push, the address bar changes, but the route is not re-rendered. Then I added v5Compat: false when using createBrowserHistory, and the route was successfully re-rendered. But there is a problem with history.go(-1) at this time. After history.push, I need history.go(-1) or (-2) twice to return to the previous page

### Expected Behavior

I hope that history.push() can be used normally, that is, re-rendering occurs after push, and go (-1) can fall back

### Actual Behavior

like Reproduce

**Comment by brophdawg11** [comment]
There's a bit too much going on in there to use that as a reproduction.  Could you provide a stripped down minimal reproduction in stackblitz/codesandbox?  Trying to run that example feels a bit like debugging the `ice.js` meta framework and not debugging `history`.

Also if you are only interested in `history` you probably want to set `v5Compat: true`, or even just use the [`history@5`](https://www.npmjs.com/package/history) package on npm.  The `history` inside `@remix-run/router` is an implementation detail of the router itself is isn't intended to be used in isolation.

**Comment by ClarkXia** [comment]
In my case i exported the history for developers to use, and create router by myself.

```js
import { createBrowserHistory, createRouter } from "@remix-run/router";
import { RouterProvider } from "react-router-dom";

// history will be exported.
const history = createBrowserHistory({ window, v5Comapt: true });

function CustomRouter() {
    const routerOptions = {
      routes,
      history,
      future: {
        v7_prependBasename: true,
      },
    };
    cons router = createRouter(routerOptions).initialize();
    return <RouterProvider router={router} fallbackElement={null} />;
}
```
When i use history.push() to navigate, it will trigger the navigation twice, because the history.push() will trigger listener function when v5Comapt is true.

https://github.com/remix-run/react-router/blob/fe661c5c0405c2212a5299b75af362df9f031b11/packages/router/history.ts#L302

And the listener function will trigger startNavigation function which called `completeNavigation`, the `completeNavigation` will trigger `init.history.push` again

https://github.com/remix-run/react-router/blob/fe661c5c0405c2212a5299b75af362df9f031b11/packages/router/router.ts#L1033

**Comment by brophdawg11** [comment]
That's expected behavior.  

`v5Compat:true` puts `history` into a mode similar to `history@5` where the concept of a `router` did not exist (this is required and used by `<BrowserRouter>` for backwards compatibility).  

The `@remix-run/router` fetches data _prior to_ updating `history` on `push`/`replace`, so if you are using `createRouter` you do not want to enable `v5Compat` and all navigation should be done using `router.navigate`.  The end-user should not be interacting with `history` at all - it's merely an implementation detail. 

So it sounds like you just want to be exporting the `router` (or a small wrapper around it) but you do not want to exporting `history` for developers to use.
