### ISSUE TITLE
[Bug]: When submitting a <Form>, the state overwrites to null

### ISSUE THREAD

**Issue by josh-sanger** [remix-run/react-router#10629]
### What version of React Router are you using?

Lastest

### Steps to Reproduce

1. Save some state to `location.state`
2. Submit a `<Form>`
3. Log the location.state after action returns;

### Expected Behavior

It would be great it would could pass in the current state or new state via `<Form state>` (like the `<Link>` component)

### Actual Behavior

There is no ability to send state with a `<Form>` navigation and it automatically resets to `null`

**Comment by timdorr** [comment]
This is because [we're doing a navigation](https://github.com/remix-run/react-router/blob/bc2552840147206716544e5cdcdb54f649f9193f/packages/react-router-dom/index.tsx#L1049) that you don't have direct access to. 

Your best bet is to send over the state data as a `type="hidden"` input along with the rest of the form. Then you can retain it as the form is submitted and choose to carry it to future navigations.

**Comment by brophdawg11** [comment]
Going to reopen since I Josh to open this 😄 

I think the bug is not so much that we don't preserve externally-set `location.state`, but that we don't provide `<Form state>` just like we support `<Link state>` since both are router/history navigations under the hood.  That way folks could proxy along current state if needed.

**Comment by brophdawg11** [comment]
This is fixed in #10630 and should be available in the next release (`6.14.2` or `6.15.0`)
