### ISSUE TITLE
[Bug]: React.Suspense fallback not triggered when useNavigate, useSearchParams or using Form

### ISSUE THREAD

**Issue by fabian-steinert** [remix-run/react-router#10638]
### What version of React Router are you using?

6.14.0

### Steps to Reproduce

1. Default deferred data set up: Implement a loader with defer, use React.Suspense with Await
2. A search input in a Form or default search parameter logic with useSearchParams or useNavigate

### Expected Behavior

Like in the Documentation said, "You will get a fallback rendered when the user navigates to the same route with different params". I expect search parameters to be params. If a search parameter changes with useSearchParams, useNavigate or within a Form, the React.Suspense fallback should be triggered.

### Actual Behavior

The React.Suspense fallback don't trigger. Not sure how to implement a search field that can trigger the fallback.

**Comment by owtdalvarezr** [comment]
But why would it re-enter the loader function (and re-load associated async data) without triggering the Suspense callback by default ?

I'm in a situation where I use `setSearchParams` and it triggers the laoder function of the route... but without showing the loader

**Comment by brophdawg11** [comment]
https://reactrouter.com/en/main/guides/deferred#when-does-the-suspense-fallback-render

If you are in a react router application you don't need to use the `defer` utility since there's no need to stream the Promise's across the wire.  Just return the raw data with promises directly from your loader and then you are in full control of the Suspense behavior via `key`.  You probably want to set this to something that will change (`navigation.location?.key || location.key`) when you want the fallback to re-render.

**Comment by MoSattler** [comment]
> I'm in a situation where I use `setSearchParams` and it triggers the laoder function of the route... but without showing the loader

Same problem here, using RR7. Unfortunately @brophdawg11 solution does not work, and Suspense keeps not rendering the fallback.
