### ISSUE TITLE
[Bug]: React Router Invokes Loaders Before Passing to RouteProvider

### ISSUE THREAD

**Issue by rgare-travistrue** [remix-run/react-router#10654]
### What version of React Router are you using?

6.14.0

### Steps to Reproduce

1. Create a router where a nested route had a loader assigned to it
2. Pass that router to `RouteProvider`
3. Open the app directly from that sub-route. In this case, we're opening the app directly on the `/projects/:projectId` route as defined below, and so that route path will be valid since before the call to `createBrowserRouter()` will be called.

Here's a stripped-down example for reference:

```js
import SignIn from './SignIn'

import {
  createBrowserRouter,
  RouterProvider,
  Outlet,
} from 'react-router-dom'

function testLoader () {
  console.log('LOADER HAS STARTED')

  return Promise.resolve()
}

console.log('about to initialize the router')

const router = createBrowserRouter([
  {
    id: 'root',
    path: '/',
    element: <div><Outlet /></div>,
    children: [
      {
        path: 'projects',
        element: <div><Outlet /></div>,
      },
      {
        loader: projectLoader,
        path: 'projects/:projectId',
        element: <div><Outlet /></div>,
      },
    ],
  },
])

console.log('finished initializing the router')

export default function App () {
  console.log('rendering the component')

  return (
    <div>
      <SignIn>
        <RouterProvider router={router} />
      </SignIn>
    </div>
  )
}
```

### Expected Behavior

Loaders would run only after being assigned to the `RouterProvider`.

Expected order of console logs:
1. `about to initialize the router`
2. `finished initializing the router`
3. `rendering the component`
4. `LOADER HAS STARTED`

### Actual Behavior

Loaders are invoked immediately after creating the router via `createBrowserRouter()`, but before being passed into `RouterProvider`.

Actual order of console logs:
1. `about to initialize the router`
2. `LOADER HAS STARTED`
3. `finished initializing the router`
4. `rendering the component`

At first, I wondered if this is intended behavior, but then how would one go about acquiring an authentication token asynchronously before the other loaders act?

My current setup is to have my `<SignIn>` component fetch the token, and then render its `children` if a token can be acquired. This would lead to `<RouterProvider>` getting rendered which I thought would start any loaders that were matched.

**Comment by brophdawg11** [comment]
This is working as expected - the primary idea behind "data routing" is to decouple fetching from rendering, so we kick off loaders before any rendering happens and you can leverage the `<RouterProvider fallbackElement>` to show a loading state during those fetches.

You can check out https://remix.run/blog/remixing-react-router and https://www.youtube.com/watch?v=95B8mnhzoCM for more information around this design.

> how would one go about acquiring an authentication token asynchronously before the other loaders act?

Until we get the [middleware](https://github.com/remix-run/react-router/discussions/9564) proposal implemented, you'll want to check for auth tokens in each of your authenticated route loaders since they run in parallel.  You should be able to dedup these API calls for fetching a token using a small abstraction around your `fetch` calls.
