### ISSUE TITLE
[Bug]: setState in action fails when a loader is present

### ISSUE THREAD

**Issue by jacobdubailcadmv** [remix-run/react-router#10701]
### What version of React Router are you using?

6.14.1

### Steps to Reproduce

I have a Form with uncontrolled inputs. The form is processed by an `action`. I need to save some of the form data in state after validation and processing. To achieve this, I'm passing `setState` to my action as a curried function. I then process my form data, set state, then return a redirect to the appropriate route.

When I have a `loader` defined on my route, the action redirect fails. The url updates, but the route does not re-render with the correct element. When I remove the loader, the redirect works correctly.

Here is a Codesandbox with an overly simplified example  https://codesandbox.io/p/sandbox/distracted-surf-5htgwx. To see the issue, uncomment the loader on lines 49-51. If you submit the form twice, the redirect works.

Adding `shouldRevalidate` and returning `false` from the route that contains the `loader` also fixes this issue.

### Expected Behavior

I would expect to be able to `setState` or call a `dispatch`er from within an action when a `loader` is present.

### Actual Behavior

The redirect fails to re-render the new route with the new element.

**Comment by brophdawg11** [comment]
When using `RouterProvider`, your `router` should be a singleton defined outside the react render lifecycle - `createBrowserRouter` has side effects (such as listening for `popstate` events) and is tightly coupled to the URL so it should only ever be called one time.  This is because the design of the data APIs decouples data fetching from rendering (see the [blog post](https://remix.run/blog/remixing-react-router) and [conference talk](https://www.youtube.com/watch?v=95B8mnhzoCM) for more info).

This approach is likely setting state, which is causing a re-render, which creates another router and renders `RouterProvider` again.  So I'm not even sure if the `redirect` ever processes correctly because that happens on a router that's since be replaced by a new one which never heard of the original redirect.  It's also likely stacking up a ton of internal `popstate` listeners on ever re-render and creation of a new router 😬 

If you need to pass data _through_ a redirect, I would either (in loose order of personal preference):

1. encode it in the URL as search params
2. stick it in local storage and then delete it when you read it (like a flash session cookie)
3. return it in `actionData`, and use an effect to stick it in react state and "redirect" via `useNavigate`
