### ISSUE TITLE
[Bug]: Path with optional parameter is not matched properly when a child with another parameter exists

### ISSUE THREAD

**Issue by Akallabet** [remix-run/react-router#10739]
### What version of React Router are you using?

6.14.1

### Steps to Reproduce

```
import { matchRoutes, Outlet } from "react-router-dom";

const routes = [
  {
    path: "/*",
    element: (
      <>
        <h1>Home</h1>
        <Outlet />
      </>
    ),
    children: [
      {
        path: "layout/:type?/*",
        element: (
          <>
            <p>Layout</p>
            <Outlet />
          </>
        ),
        children: [
          {
            path: ":details/*",
            element: (
              <>
                <p>details</p>
                <Outlet />
              </>
            ),
            children: [
              {
                path: "content",
                element: <p>Content</p>
              }
            ]
          }
        ]
      }
    ]
  }
];

const matches = matchRoutes(routes, "/layout/type1");
```
[Codesandbox](https://codesandbox.io/s/nervous-worker-589d95?file=/src/index.js)
Also I've opened a [PR with a failing test](https://github.com/remix-run/react-router/pull/10738)

### Expected Behavior

The pathname `"/layout/type1"` should match `["/*", "layout/:type?/*"]`

### Actual Behavior

The pathname `"/layout/type1"` actually matches `["/*", "layout/:type?/*", "layout/:details/*"]`

**Comment by brophdawg11** [comment]
This is behaving correctly due to the way the internal route ranking/scoring works.  I think you just don't want the trailing splat params on each route - since they end up adding more URL segments and bumping up the score.  You generally just want a splat on the leaf route.

Here's what your ranked route branches look like with your current setup:

<img width="445" alt="Screenshot 2023-08-02 at 1 01 52 PM" src="https://github.com/remix-run/react-router/assets/1609022/029edbcd-a546-47a7-a442-1156ca484a50">

So both `/*/layout/*/:details/*` and `/*/layout/:type/*` will match `/layout/type1` but because of the extra splat segment, the `:details` route gets an extra point because the # of URL segments is part of the scoring.

Instead, if you take the splats off then it works as you would expect:

```jsx
  it("matches parent path with optional parameter without matching any child", () => {
    let routesWithOptionalParameters: RouteObject[] = [
      {
        path: "/",
        element: <h1>Home</h1>,
        children: [
          {
            path: "layout/:type?",
            element: <p>Layout</p>,
            children: [
              {
                path: ":details",
                element: <p>details</p>,
                children: [
                  {
                    path: "content",
                    element: <p>Content</p>,
                  },
                ],
              },
            ],
          },
        ],
      },
    ];
    expect(pickPaths(routesWithOptionalParameters, "/layout/type1")).toEqual([
      "/",
      "layout/:type?",
    ]);
    expect(
      pickPaths(routesWithOptionalParameters, "/layout/type1/detail1")
    ).toEqual(["/", "layout/:type?", ":details"]);
  });
```

**Comment by Akallabet** [comment]
@brophdawg11 thanks for providing a detailed answer: it totally makes sense.
