### ISSUE TITLE
[Bug]: I use '\' in router path, for example :【’http://localhost:8089/#/\‘】 throw a error

### ISSUE THREAD

**Issue by html-body** [remix-run/react-router#10760]
### What version of React Router are you using?

v6

### Steps to Reproduce

![image](https://github.com/remix-run/react-router/assets/49872751/995f2b1a-f621-43ec-ad68-0194b7a0c91a)

// input url in address 【’http://localhost:8089/#/\‘】

### Expected Behavior

I want a redirected callback function，go path *.

### Actual Behavior

// result => 

//error:  Failed to construct 'URL': Invalid URL TypeError: Failed to construct 'URL': Invalid URL，

**Comment by brophdawg11** [comment]
`/\` is an invalid URL which is why this error is throwing.  React Router can't intelligently do anything here (like decide what a better URL would be), so all we can do is throw if the platform throws on our creation of a `URL`.

<img width="445" alt="Screenshot 2023-08-04 at 8 01 58 AM" src="https://github.com/remix-run/react-router/assets/1609022/348eb178-687a-413f-91e9-d363cbf6d360">


If you are concerned about failing gracefully on these types of URLs, I would do a quick check before you instantiate React Router and redirect to the location of your choosing:

```jsx
try {
  new URL(window.location.hash.replace(/^#/, ""), window.location.origin);
} catch (e) {
  // If the hash value is an invalid URL, redirect to the homepage
  window.location.href = "/";
}

// Only render the app once we've validated the hash can be constructed into a URL
ReactDOM.createRoot(document.getElementById("root")!).render(<App />);
```
