### ISSUE TITLE
[Bug]: 6.14.2 breaks nested router within Remix

### ISSUE THREAD

**Issue by Ehesp** [remix-run/react-router#10766]
### What version of React Router are you using?

6.14.2

### Steps to Reproduce

When upgrading to 6.14.2, using `react-router-dom` within a Remix application throws the error:

```
You cannot render a <Router> inside another <Router>. You should never have more than one in your app.
```

Appreciate using react router within Remix is a bit weird, but it's what's in place at the moment. If you navigate to: https://stackblitz.com/edit/remix-run-remix-qam45w?file=app%2Froutes%2F_index%2FRouter.tsx you can see a Remix route renders a react-router-dom Router. This is working as expected.

- Now update `react-router-dom` dependency in `package.json` to `"react-router-dom": "6.14.2",`.
- Run `npm i`
- Reload the application, the above error is now thrown.

### Expected Behavior

It continues to work within Remix.

### Actual Behavior

The above error is thrown.

**Comment by brophdawg11** [comment]
This is not a supported usage of React Router - you can only have one router because it is synced to the singular `window.location` URL.

This is only working by happenstance because you have mismatched versions of the router in your current application:

```
~/projects/remix-run-remix-qam45w 5s
❯ npm ls react-router-dom
remix-run-remix-qam45w@ /home/projects/remix-run-remix-qam45w
+-- @remix-run/react@1.19.2
| `-- react-router-dom@6.14.2
`-- react-router-dom@6.14.1
```

Internally React Router uses a `React.context` instance to detect this so when you have 2 copies of `react-router-dom`, you have 2 copies of the Context and the nested router detection fails.  Updating to `6.14.2` aligns the version and the check then correctly detects the invalid nested Router usage.

You can keep an eye on [this proposal](https://github.com/remix-run/react-router/discussions/9601) which requests official support for nesting a memory router inside a browser router.

If you just need to _render_ nested routes, you can do so with a `<Routes>` component in your Remix components.  You just cannot define _another_ `createBrowserRouter`/`RouterProvider` because Remix already instantiates one of those internally.

**Comment by Ehesp** [comment]
Thanks @brophdawg11 that makes sense. 

Rendering `Routes` does the trick, although I lose access to client `handle` data, but I suspect thats because Remix is overriding that

**Comment by brophdawg11** [comment]
Not overriding per-se, [`<Routes>`](https://reactrouter.com/en/main/components/routes) components and their child routes don't have access to the [Data APIs](https://reactrouter.com/en/main/routers/picking-a-router#data-apis) because `<Routes>`is tightly coupled to the render cycle, and the Data APIs operate outside of the render.
