### ISSUE TITLE
Need next route for unstable_useBlocker and unstable_usePrompt

### ISSUE THREAD

**Issue by resatDev** [remix-run/react-router#10859]
After the **Prompt component** was removed, the **unstable_useBlocker** and **unstable_usePrompt** hooks were added again. However, the "message" prop, which is one of the most important features of the Prompt component, does **not have the ability to work as a function**. One of the parameters that the function message prop return was the next route to proceed. I will need this as soon as possible. The **nextPathname** prop used in the **unstable_useBlocker hooks is the related prop which I need**.

**Comment by timdorr** [comment]
These are still unstable APIs, so they are not supported and will have active bugs or incomplete functionality. If you want to see those things added, please create a PR.

**Comment by douglasjunior** [comment]
I'm very sad to say this, but it looks like the react-router v6 docs was created only as a showcase for Remix. 

I'm truly grateful for all the react-router team in the last years, but all the useful things from the previous version were removed, with no glue.

We don't have even a search bar in the docs.

I have used react-route since 2017, professionally, personally and for education purpose.

Since v4 we are experiencing a downgrade in features and functionalities, and now with Remix looks like the things are worse.
