### ISSUE TITLE
[Bug]: loader's redirect is not work

### ISSUE THREAD

**Issue by vaynevayne** [remix-run/react-router#10863]
### What version of React Router are you using?

latest

### Steps to Reproduce

into page, when accessToken not exist, should redirect to login page, but nothing happend

https://stackblitz.com/github/vaynevayne/react-auth?file=src%2Frouters.tsx%3AL37-L37

### Expected Behavior

redirect to login page

### Actual Behavior

into home page

**Comment by brophdawg11** [comment]
Can you provide a smaller/minimal reproduction?  I am not aware of how `react-router-auth-plus` works under the hood so there's a chance that is causing the issue.  

The first thing that jumps out is that you are creating your `router` in the render cycle via `createBrowserRouter(_routers)` - which is usually the source of problems because you end up creating a brand new router on every single re-render and you lose any prior stateful information.  You want to create your router as a module singleton outside the render cycle as shown in the docs: https://reactrouter.com/en/main/routers/create-browser-router

**Comment by Youssef11296** [comment]
Will check it

**Comment by vaynevayne** [comment]
Just because the loader doesn't work and other properties are still fine, how can you put the blame on the user

**Comment by timdorr** [comment]
I looked into this more. Your example is doing exactly as Matt said, which is recreating the router instance and losing state information. That react-router-auth-plus library appears to be poorly designed and encourages this anti-pattern. I would avoid using it.
