### ISSUE TITLE
[Docs]: It's unclear whether useParams() result is dynamic

### ISSUE THREAD

**Issue by vporton** [remix-run/react-router#10901]
### Describe what's incorrect/missing in the documentation

It's unclear from a [docs page](https://reactrouter.com/en/main/hooks/use-params) whether `useParams()` result is "dynamic" like the result of `useState()` that may change.

For example, does it make sense to watch for useParams() result in `useEffect`? Like:
```typescript
const { id } = useParams();
useEffect(() => {
  ...
}, [id]);
```

**Comment by timdorr** [comment]
It literally has that word on that page:

> The `useParams` hook returns an object of key/value pairs of the **dynamic** params from the current URL that were matched by the `<Route path>`.

But if you navigate to the same route, it will re-render the same component with an updated value from the hook. So, you would need to include that in useEffect dependencies.

**Comment by reorx** [comment]
It seems that `useParams()` will return two results even if you navigate to a different URL. For example, if you navigate from `/item/foo` to `/item/bar`, `useParams()` will first return `{"id": "foo"}` and then `{"id": "bar"}`. Is this by design?

**Comment by timdorr** [comment]
Why wouldn't it? It's giving you the parameters from the URL. If the URL changes, the parameters would change and trigger another render. This is its only function.

**Comment by reorx** [comment]
Yes, its function is to give you the URL parameters. The problem is why the current URL's parameters are returned. If you change `useParams` to `useLocation`, you will find that only the target URL is returned. Since parameters and the URL are essentially the same thing from a higher perspective, I expect `useParams` and `useLocation` should behave the same in terms of rendering effect.
