### ISSUE TITLE
[Bug]: SSR with `lazy` causes double-render

### ISSUE THREAD

**Issue by sgammon** [remix-run/react-router#10918]
### What version of React Router are you using?

6.16.0

### Steps to Reproduce

1. Setup an MUI app with SSR via Express
2. Setup a `lazy={() => import(...)}` route
3. Load the SSR endpoint for that route
4. Observe that there is a double render

### Expected Behavior

I would expect this to work as the other (non-lazy) routes do.

### Actual Behavior

I see a double render, but only if the route is `lazy`; if the route uses a directly-rendered `element`, it works fine.

### Diagnosis & repro

Repro is [here](https://github.com/elide-dev/site/tree/repro-router-bug), in a public and relatively new OSS project. You can replicate the bug with the steps:

1. Clone the project
2. Run `pnpm i`
3. Run `pnpm build:dev && pnpm serve:express`
4. Load `http://localhost:3000`, observe regular SSR hydrated render (this is a non-lazy route)
5. Load `http://localhost:3000/hi`, observe the double render

**Failure condition:**
<img width="796" alt="Screenshot 2023-10-09 at 10 00 47 AM" src="https://github.com/remix-run/react-router/assets/171897/731b08d8-52d2-4767-8734-ffe4ce0adf40">

**Server output** (just one render highlighted, i.e. SSR is working fine):
<img width="1599" alt="Screenshot 2023-10-09 at 10 01 10 AM" src="https://github.com/remix-run/react-router/assets/171897/22cc151f-18fc-414a-af8e-efc43f7c2d92">

**Converting to a non-lazy route** (no double render):
<img width="551" alt="Screenshot 2023-10-09 at 10 02 54 AM" src="https://github.com/remix-run/react-router/assets/171897/ad5dee42-7abd-43de-af20-b4de5c6e630b">

**Combining these observations:**
- No obvious error logs (for example, no SSR render misalignments, hydration working as expected)
- The bug seems related only to `react-router-dom`
- The bug only kicks in when SSR and lazy routes are both active
- SSR rendering always seems to produce one render as expected (so, a CSR-only issue?)

**Comment by sgammon** [comment]
Repro is [here](https://github.com/elide-dev/site/tree/repro-router-bug), in a public and relatively new OSS project. You can replicate the bug with the steps:

1. Clone the project
2. Run `pnpm i`
3. Run `pnpm build:dev && pnpm serve:express`
4. Load `http://localhost:3000`, observe regular SSR hydrated render (this is a non-lazy route)
5. Load `http://localhost:3000/hi`, observe the double render

**Comment by brophdawg11** [comment]
I've run into this double-rendering before and it's not a React Router issue but something that React ends up doing when it encounters a hydration error and re-does a full client-side render.  I've not yet been able to narrow down a small reproduction to open a React bug ... but the good news is I _do_ know why this happens with `lazy` and what you need to do to avoid it 😄 

The tl;dr; is [this section in the docs](https://reactrouter.com/en/main/guides/ssr#lazy-routes)

The root cause is a hydration issue, and you can see this if you run the [`ssr-data-router` example](https://github.com/remix-run/react-router/blob/main/examples/ssr-data-router) and comment out [these lines](https://github.com/remix-run/react-router/blob/main/examples/ssr-data-router/src/entry.client.tsx#L14C1-L28C4).  If you then load the /lazy route directly you'll see the double-render.

Here's what's happening:
* User loads `/lazy`
* During SSR, `staticHandler.query` waits for the `lazy()` function to execute so that it can run the `loader` and SSR the `Component`
  * This means that you send up a fully-rendered HTML of the `/lazy` route
* During client-side hydration, if you comment out the above lines and just create a router and synchronously render `RouterProvider`, then the _initial_ client render is the `fallbackElement` since the first thing `createBrowserRouter` needs to do it asynchronously run the `lazy()` functions and it shows the `fallbackElement` until it can run those and any associated loaders.
* This means you have a guaranteed hydration mismatch (`/lazy` `Component` on SSR and `fallbackElement` on client render).  This is no good - as the user will initially see fully-rendered content, then it will flip to the fallbackElement, then back to rendered content.

Instead, when using SSR and `lazy` you need to ensure that any _initial_ route modules are loaded _before_ doing the initial client render so that the first render of `RouterProvider` matches what was rendered on the server.  In the example, the code before `createBrowserRouter` is doing just that and detecting any initially-rendered routes and running their lazy modules to update those routes prior to hydration.

This is a bit of a workaround though.  What you really want (and this is what Remix does) is to make sure your initial routes are immediately available and don't even use `lazy`.  During SSR you know the route matches and can render `<script>` tags for the initial matches and then you don't need to define them as lazy in the client side router.  It's a bit more complex - and is a reason that Remix is our recommended way to SSR React Router 😄 .

Also, as I'm playing with this example, I realized that the double render only happens with `fallbackElement={null}`, but if I change it to `fallbackElement={<p>Loading...<p>}` I still get a hydration error in the console, but I get an the expected UI behavior of `content -> loading -> content`.  So that tells me that the double render has something to do with a hydration error when you try to hydrate `null` over top of SSR content.  I'm assuming React has no reference to replace due to the `null` so it ends up just appending the newly rendered client side content or something 🤷
