### ISSUE TITLE
[Docs]: Add unstable_useBlocker and unstable_usePrompt to the docs

### ISSUE THREAD

**Issue by deenns** [remix-run/react-router#10950]
### Describe what's incorrect/missing in the documentation

I cannot find any mentions of `unstable_useBlocker` and `unstable_usePrompt` on https://reactrouter.com
But both hooks exist. 

Related to: https://github.com/remix-run/react-router/issues/8139

**Comment by timdorr** [comment]
They are both marked as unstable. As such, they can change at any time and documentation may become quickly out of date. They'll be undocumented until they reach stable status.

**Comment by IanVS** [comment]
This is very frustrating.  I've been waiting years to upgrade react-router hoping that this feature would be added, since the migration docs say:

>We will absolutely be working on adding this back in to v6 at some point in the near future, but not for our first stable release of 6.x.

It's been a long time since the first stable release, and there's no indication that this feature will be "absolutely" added "in the near future".  I'd recommend at least removing that language from the migration docs, if this is not in fact something that is being worked on.  https://github.com/remix-run/react-router/issues/8139 was closed as complete and docs were promised back in January, but yet there are still no docs.

**Comment by IanVS** [comment]
Furthermore, `unstable_viewTransition` is [documented](https://reactrouter.com/en/main/components/link#unstable_viewtransition) with a warning about it being unstable.  Why does that feature deserve documentation and yet these do not?
