### ISSUE TITLE
[Bug]: Directly changing the URL for local navigation bypasses useBlocker

### ISSUE THREAD

**Issue by differentsmoke** [remix-run/react-router#11088]
### What version of React Router are you using?

6.20.1

### Steps to Reproduce

In any component using the `useBlocker` hook, using a data router created with `createHashRouter`, changes to the URL that aren't triggered from navigation items within the Router are not picked up by the blocker.

### Expected Behavior

Changing the URL location from outside the Router should also trigger blockers, be that directly typing a different route or using navigation items not rendered by the Router app.

To clarify, I am talking about changes that _would **not** trigger_ `onbeforeunload`, but that would have been picked up by the v5 `Prompt` component, such as manually typing a Router defined route into the Location bar.

### Actual Behavior

For instance, if I have a route `items/:id/edit` with a Link back to `items/:id`, clicking the Link will trigger the blocker, but directly changing the URL to `items/:id` will not.

**Comment by brophdawg11** [comment]
Unfortunately, this is expected behavior due to the limitations of the underlying `history` API.  Blocking is limited to navigations [performed via the router](https://reactrouter.com/en/main/hooks/use-blocker):

> This only works for client-side navigations within your React Router application

You should be seeing see a console warning like the following when you do a direct-URL navigation with an active blocker:

```
You are trying to use a blocker on a POP navigation to a location that was not created by @remix-run/router. This will fail silently in production. This can happen if you are navigating outside the router via `window.history.pushState`/`window.location.hash` instead of using router navigation APIs.  This can also happen if you are using createHashRouter and the user manually changes the URL.
```

In order to do blocking correctly across POP navigations, React Router needs to track indices of history entries.  This is because a user can click the back button to go back 1 entry, or they can click and hold and choose something that's N entries backwards in the stack.  React Router needs to be able to determine how far back/forward in the stack the user went and does so using indices on the history state entries that are created when you navigate via the router.  If you navigate outside the router, the new location doesn't get an index and therefore React Router can no longer reliably block the navigations involving that entry moving forward so it logs the warning.
