### ISSUE TITLE
[Docs]: why need localforage, match-sorter, sort-by in the example in the tutorial?

### ISSUE THREAD

**Issue by electfreak** [remix-run/react-router#11099]
### Describe what's incorrect/missing in the documentation

I was reading the [tutorial](https://reactrouter.com/en/main/start/tutorial). there is a command:
```sh
npm install react-router-dom localforage match-sorter sort-by
```
But there is no usage of these packages (except react-router-dom itself) further

**Comment by brophdawg11** [comment]
They're used by the [contacts](https://gist.githubusercontent.com/ryanflorence/1e7f5d3344c0db4a8394292c157cd305/raw/f7ff21e9ae7ffd55bfaaaf320e09c6a08a8a6611/contacts.js) module you have to copy/paste in:

> 👉 Copy/Paste the tutorial data module found here into src/contacts.js

**Comment by electfreak** [comment]
@brophdawg11 it worth noting (for beginners) that these packages are not needed for react-router itself

**Comment by ShaneYu** [comment]
This needs addressing somehow, either the gist needs updating or the docs need to call it out more clearly that it's not needed by the react router itself.

Dependabot and other vulnerability scanners are screaming about prototype-pollution vulnerabilities in sort-by package, most of us included it because we were lead to believe it was needed by the tutorial.

Obviously we can just remove them, but might be a good idea to make it clearer to people.

**Comment by brophdawg11** [comment]
We'd happily accept a PR to update the documentation!
