### ISSUE TITLE
[Docs]: Firebase Subscription and Route Loader

### ISSUE THREAD

**Issue by aress31** [remix-run/react-router#11107]
### Describe what's incorrect/missing in the documentation

Is it possible from a loader to define a subscription like:

```js
const useOnDataChange = (query, key, setLoading) => {
  const [data, setData] = useState([]);

  useEffect(() => {
    setLoading(true);

    const fetchData = async () => {
      try {
        const newData = await wGet(query, key);
        setData(newData);
      } finally {
        setLoading(false);
      }
    };

    const unsubscribe = onValue(ref(database, query), fetchData);

    return () => {
      unsubscribe();
    };
  }, [query, key]);

  return { data };
};
```

That would be immensely useful!

**Comment by ChristophP** [comment]
I just stumbled across this issue as well.
I am using RTK Query that also works with a subscription based request model.

I would like something like "when this route matches, subscribe to the data so that it'll get fetched. Then when the users navigates away unsubscribe".

>  They are not the correct place to establish subscriptions or other side effects.
Where would a good place be for things like that in your opinion?
