### ISSUE TITLE
[Bug]: the loader have been called twice when redirect inside loader

### ISSUE THREAD

**Issue by lili21** [remix-run/react-router#11129]
### What version of React Router are you using?

6.15.0

### Steps to Reproduce

https://stackblitz.com/edit/github-kfzdp2?file=src%2Fapp.tsx

You can try the stackblitz demo.

1. open chrome devtools
2. click the "compare" link, it will redirect to "compare/12345"
3. check the devtools console panel

### Expected Behavior

when redirecting to a child route, the parent route should be same, and the loader shouldn't be called again.

### Actual Behavior

the parent loader have been called twice

**Comment by timdorr** [comment]
This is expected behavior. We always call all loaders on navigation in case their data is out of date.

**Comment by lili21** [comment]
But when I use <Link /> to navigate to child route, the parent loader won't be called again.

**Comment by Manizuca** [comment]
Hi @timdorr
As @lili21 pointed out, there is a difference on how loaders are called when there is a redirection from the component (<Navigate> or useNavigation()) vs when i done from a loader.

I'll love to understand  why there is such a difference. Is this by design?

I have made 2 simplified examples to show this:
Example a: https://stackblitz.com/edit/github-kfzdp2-bhsanz?file=src%2Fapp.tsx
Example b: https://stackblitz.com/edit/github-kfzdp2-mi7kvg?file=src%2Fapp.tsx

Both have the same routes structure. Both of them will make a redirection to "/redirect-to" when accessed from "redirect-from":
```
{
    path: "/",
    children: [
        {
            path: "redirect-from"
        },
        {
            path: "redirect-to"
        }
    ]
}
```

Now, for example 1, if you start your application at "/redirect-from" the root loader is called twice:
```
root loader
redirect-from loader 1721091200127
root loader
redirect-to loader 1721091201129
```
This example is the one that calls redirect() from the loader.

However, for example 2, if you start your application at "/redirect-from" the root loader is just called once:
```
root loader
redirect-from loader 1721091208543
redirect-to loader 1721091209549
```
This example is calls navigate() inside an useEffect.

Is there a way I can redirect from a loader function, but without the parent loaders executing again?
