### ISSUE TITLE
[Bug]: useLoaderData() rerenders component twice upon revalidation. Once with the previous data, once with the new one.

### ISSUE THREAD

**Issue by alexanderhorner** [remix-run/react-router#11134]
### What version of React Router are you using?

6.21.1

### Steps to Reproduce

https://stackblitz.com/edit/github-6s4uyd?file=src%2Fapp.tsx

When you click revalidate, you will observe following in the console:

```
Loader is called
Rerender. Loader data:  0.39536183926497515  1703184193137
Loader will return now
Rerender. Loader data:  0.4060284267270109  1703184198639
```

### Expected Behavior

When a loader is revalidated, the components that use `useLoaderData()` should rerender only once the loader is finished revalidating. 

### Actual Behavior

When a loader is revalidated, the components that use `useLoaderData()` render immediately after revalidation, and then again once the Loader is resolved.

**Comment by brophdawg11** [comment]
This is expected behavior - because navigations/revalidations are global and update the global Data Router context at the root of the tree.  You go into a `revalidator.state == "loading"` state during the revalidation, causing a re-render.  And then back to `revalidator.state == "idle"` with the new loader data.
