### ISSUE TITLE
[Bug]: Please expose the `history` object created by `createMemoryRouter`

### ISSUE THREAD

**Issue by julienw** [remix-run/react-router#11167]
### What version of React Router are you using?

6.18.0

### Steps to Reproduce

Use `createMemoryRouter` in a test, eg:
```js
render(
  <RouterProvider
    router={createMemoryRouter([{ path: route, element: ui, loader }], {
      initialEntries: [route + search],
    })}
  />
)
```

In v5 we could use the `Router` object directly to create an history object with  `createMemoryHistory`, but as far as I know `createRouter` isn't exposed in v6, so we can't do it this way.

The memory history makes it easy to create an initial path, and then inspect it in tests.

### Expected Behavior

I'd like to have access to the `history` object.

### Actual Behavior

I don't have access to the `history` object, despite that the documentation mentions being able to `testing a back navigation`.

**Comment by brophdawg11** [comment]
I'm not sure what functionality you are missing?  

* `createMemoryRouter` accepts `initialEntries` and `initialIndex`
* You can inspect the current location via `useLocation` or `router.state.location`
* You can "test a back navigation" via `router.navigate(-1)`

With Data Routers, `history` is (by design) an implementation detail because the `router` is the primary interaction and needs to do data fetching _prior_ to an interactions with history on push/replace navigations.  It is also helping us future proof ourself to eventually replace `history` with the the [Navigation API](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_API).

**Comment by julienw** [comment]
mmm I see that `router.navigate(number)` and `router.state` are marked as "internal only" on the Router interface (and actually they're not documented).

For now I've settled to use `history.replaceState` for the initial entries, a browser router, and access `window.location` directly (as I'm in a JSDOM environment).

**Comment by brophdawg11** [comment]
They're fine to use in tests.  They're marked that way to avoid folks trying to reach for them within app code instead of their hook equivalents such as `useNavigate`, `useLocation`, etc.

**Comment by niksauer** [comment]
@brophdawg11 Do you have suggestion for https://github.com/remix-run/react-router/discussions/12466? We also rely on having access to the history object or somehow plugging in to the push/replace actions 😕
