### ISSUE TITLE
[Bug]: Internal link not working 

### ISSUE THREAD

**Issue by Ic3b3rg** [remix-run/react-router#11186]
### What version of React Router are you using?

6.21.2

### Steps to Reproduce

https://stackblitz.com/edit/react-kmrgsn?file=src%2FAbout.js,src%2FApp.js,src%2FpageTracking.js

go to home page and click on "go to footer" (WORKING)
go to about page and click on "go to footer" (NOT WORKING)

### Expected Behavior

that the scroll not goes to the footer

### Actual Behavior

that the scroll goes to the footer

**Comment by brophdawg11** [comment]
You need to ensure the hash is using the current pathname:

```
let { pathname } = useLocation();
<a href={`${pathname}#footer`}>go to footer</a>
```

If you want hash scroll updates from `<Link>` you can use `<ScrollRestoration>` within a `<RouterProvider>` app as well

**Comment by Ic3b3rg** [comment]
The anchor tag is a web standard and the problem doesn't arise if I make a normal html page much less if I send my code into prod, so I think this should be revised
If you use dev tools in both development and prod of that code you will see that the anchor tags work differently. I also don't want to use JS to do something that works normally on the web
@brophdawg11

**Comment by brophdawg11** [comment]
I agree it's a web standard - unfortunately, you are using it incorrectly in this case.

You are rendering `<a href="/#footer">` which will (1) navigate to the `/` route and (2) scroll to any embedded `#footer` in the document.  (1) is why you're landing back on the home page and (2) doesn't happen because the `#footer` doesn't exist in the HTML document received for `/` - and it gets subsequently client side rendered.

If you instead render just `<a href="#footer">` or embed the pathname as suggested above then (1) will _not_ fetch a new document because only the hash is changing and (2) will work as expected.

> I also don't want to use JS to do something that works normally on the web

I'm a bit confused by this - the web does link navigations but you're choosing to use a JS library to handle them, no?   So you're opting into JS logic which behaves differently.  If you want native hash scrolling - use the native `<a>` tag.  The first thing `<Link>` does is call `e.preventDefault()` so that you can perform a client side navigation.  That, by definition, also prevents the browsers "scrolling to hash" behavior.  We have added `<Link>` support for scroll handling in `RouterProvider` via [`<ScrollRestoration>`](https://reactrouter.com/en/main/components/scroll-restoration) so if you wish to leverage that feature you can [upgrade to use `RouterProvider`](https://reactrouter.com/en/main/upgrading/v6-data)
