### ISSUE TITLE
[Bug]: Navigate function behaves differently depending on which route element it is created in

### ISSUE THREAD

**Issue by chaance** [remix-run/react-router#11262]
### What version of React Router are you using?

6.22.0

### Steps to Reproduce

Repro: https://stackblitz.com/edit/stackblitz-starters-w1fcnu?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx&title=React%20Starter

Click `My Project` > `Create a Page`. If you click `Cancel` in the dialog, this calls `navigateFromRoot("..", { relative: "path" })` using the navigator created in the `Providers` component (rendered by the root layout route). 

### Expected Behavior

I expect this to navigate up one path segment relative to the current URL (removing the `/add` segment)

### Actual Behavior

Navigates to the root path.

### More context

Admittedly this is a bit of a weird approach. In this contrived example I am calling `useNavigate` in two different components and passing both of those navigate functions into a render-prop component so that route elements can use them directly.

If you replace `navigateFromRoot` with `navigate`, which is created in `CreatePageDialog` (the current route's element), navigation works as expected. I would expect the function returned from `useNavigate` to navigate based on the context from the route from the current URL, no matter where the function is created in the React tree.

If this is intended behavior, it's a bit confusing and some docs or clarification here would be helpful. If not, perhaps we have a bug!

**Comment by brophdawg11** [comment]
Yeah I think this is just a missing nuance in the docs - I can get a note added in there

"Relative Routing" has 2 key points:

1. Where do I start?  I.e., what does `.` mean?
2. How do I go up?  I.e., what does `..` mean?

Relative routing in RR always starts at the route in context, so (1) is constant.

`relative: "path"` alters the behavior of (2) - should it go up one route in the hierarchy?  Or go up one URL segment?

If you want "no matter where I am called, I want to navigate from the current `window.location` using `relative:path` behavior", then you don't really need an RR primitive since you aren't using it's internal route hierarchy.  You can do that with the `URL` constructor.


```js
new URL("..", "http://localhost/editor/project/page").pathname
// '/editor/'
new URL("..", "http://localhost/editor/project/page/").pathname
// '/editor/project/'
```

(just beware of the trailing slash importance which can be a bit of a footgun)

**Comment by chaance** [comment]
@brophdawg11 This is less about "where is navigate called" and more "where is navigate initiated" (or "where was `useNavigate` called"). In both cases I'm calling `navigate` from the same route.

**Comment by brophdawg11** [comment]
agreed - bad wording on my part above

**Comment by brophdawg11** [comment]
Added a note in 135e8aa10e0448a9720f2868be96e0a30403fd91 - thanks for the call out!
