### ISSUE TITLE
[Bug]: Routing from a location to a location/hash Continued

### ISSUE THREAD

**Issue by rebeccapeltz** [remix-run/react-router#11268]
### What version of React Router are you using?

6.22.0

### Steps to Reproduce

This follows a previous bug report that was closed.  https://github.com/remix-run/react-router/issues/11264#issuecomment-1936865274

The outstanding problem is that if you click a location/#hash link from a page other than the one the hash is on, you are not taken to the hash.  
For example, I have an id="midpoint" on the Home page.   When I click on a link to this from the Home page it takes me to the "midpoint".  If I click on the link from another page, like About, not the Home page, it takes me to the top of the Home page, not the "midpoint".  Here is a link to an example of this behavior using react-router: https://stackblitz.com/edit/react-ts-9kwbcp?file=package.json.

### Expected Behavior

The expected behavior is that by clicking on the Midpoint link on the About page, you would navigate to the "midpoint" location on the Home page.  You can see this expectation fulfilled in this HTML sandbox: https://replit.com/@RebeccaPeltz/Opentohash.  

I'm assuming React Router wants to maintain the same functionality in page routing that you would see in a static web page.

 The workaround for this problem in React is to use JavaScript to scroll to the Midpoint after examining the location and hash routes. You shouldn't need to use JavaScript to take your user to the hashed location on another page.

https://www.w3docs.com/snippets/html/how-to-create-an-anchor-link-to-jump-to-a-specific-part-of-a-page.html#link-to-another-page-in-the-same-domain-18

### Actual Behavior

This sandbox using react-router demonstrates the behavior that is not working: https://stackblitz.com/edit/react-ts-9kwbcp?file=package.json.
- Click on About
- Click on Midpoint
- 
You should navigate to the middle of the Home pages, but instead, you navigate to the top of it.

I added  `reloadDocument` to the hash link as recommended in a previous bug report, but this didn't help cross page hash navigation.
```
<Link to="/#midpoint" reloadDocument={true}>
    Midpoint
</Link>
```

**Comment by brophdawg11** [comment]
Scroll management is not available when using `BrowserRouter` - you would need to handle that via your own effects.

We released a [`ScrollRestoration`](https://reactrouter.com/en/main/components/scroll-restoration) component in 6.4 that you can use with a [Data Router](https://reactrouter.com/en/main/routers/picking-a-router)/[`RouterProvider`](https://reactrouter.com/en/main/routers/router-provider) that solves this: https://stackblitz.com/edit/react-ts-ug6gbd?file=App.tsx

> You shouldn't need to use JavaScript to take your user to the hashed location on another page.

This is a bit confusing to me since you've already opted into JS being a requirement with the SPA architecture?  If you were rendering your HTML on the server, then the `reloadDocument` suggestion would work as expected.  It doesn't only because the anchor indicated by the hash does not exist on page load.

**Comment by rebeccapeltz** [comment]
`reloadDocument` does work on the Home page, where the anchor is located.  Are you saying that if I had pre-rendered the About page, that this would work?
I appreciate the clarification that we need to write our own JavaScript for this cross-page scroll-to-hash functionality.   I was concerned that I was not correctly implementing the react-router package.

**Comment by brophdawg11** [comment]
Yep!  `reloadDocument` basically turns your link into a normal `<a href>` that react router doesn't touch (no `onClick` listener, no `e.preventDefault()`, no client side routing) so it will be a document HTTP request to your server for a fresh HTML page.  Browser's built-in hash-routing operates on the initial HTML returned from the server - and if it doesn't find an `id` matching the hash in that HTML then it doesn't do any scrolling.  So if the HTML returned from the server for `GET /about` had the midpoint ID in it then it would work as expected.

My recommendation would be to [migrate to a data router](https://reactrouter.com/en/main/upgrading/v6-data) if possible and then `ScrollRestoration` should solve your problem.  

If you can't migrate at the moment, you may be able to adapt the code in https://github.com/epicweb-dev/restore-scroll (which is loosely based on `ScrollRestoration` and adapted to work for any element with scrolling) and remove the `useNavigation` logic since there is no "navigation " concept in `BrowserRouter` and my hunch ois that you can get pretty close to getting a working `<ScrollRestoration>` for `BrowserRouter`
