### ISSUE TITLE
[Bug]: Links in <fieldset disabled> reload the page in firefox

### ISSUE THREAD

**Issue by mattoni** [remix-run/react-router#11366]
### What version of React Router are you using?

6.22.3

### Steps to Reproduce

Wrap a `<Link>` in a `<fieldset>`. It correctly navigates without reloading the page. 

If you put `<fieldset disabled>` on it, the link now reloads the page. This does not happen in safari or chrome. 

I suspect Firefox is preventing the event from propagating up in a disabled fieldset (I've found some stack overflow posts alluding to this) but wanted to see if there was any additional information that could be provided here or if it is solvable in this package.

See this for a repro'd example: https://codesandbox.io/p/sandbox/react-router-v6-forked-qkjxcz?file=%2Fsrc%2FApp.js%3A23%2C15

  

### Expected Behavior

The link doesn't reload the whole page.

### Actual Behavior

The link reloads the whole page

**Comment by timdorr** [comment]
This is expected behavior, as per that API: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset#disabled

It won't send the mouse events to those elements, so our handling of the click of that link never fires. I would expect the link to be disabled as well, but that's outside of the scope of the router to control.
