### ISSUE TITLE
[Bug]: useBlocker not prevent fetcher submits

### ISSUE THREAD

**Issue by abustany** [remix-run/react-router#11369]
### What version of React Router are you using?

6.22.3

### Steps to Reproduce

1. Open https://stackblitz.com/edit/github-wxm49t?file=src%2Fapp.tsx
2. Click the Go button

(note: I added a beforeunload handler to make 100% sure the issue is not linked to client vs. "real" navigation)

### Expected Behavior

`useBlocker` prevents the fetcher from submitting

### Actual Behavior

`fetcher.submit()` navigates way, potentially losing unsaved data on the page

**Comment by brophdawg11** [comment]
This is intended - `useBlocker` prevents _navigations_ and fetchers are explicitly not navigations.  What you're seeing is the bubbling of a 404 on the fetcher call to the [Error Boundary](https://reactrouter.com/en/main/route/error-element), and since you haven't specified one it's using the default which is blowing away your UI so it "feels" like it navigates elsewhere but it remains on `/` the whole time.

Here's an example of using an `ErrorBoundary` to capture those errors contextually in the UI: https://stackblitz.com/edit/github-wxm49t-jdqbwf

**Comment by abustany** [comment]
Thanks for the detailed answer! My use case involves not a 404 but the loader returning a redirect, should that also be captured using an error boundary then?

**Comment by brophdawg11** [comment]
Can you provide a reproduction of your actual use case?  Using a `fetcher.submit` to submit a GET request to a `loader` that redirects sounds like an odd combination to me.  Why not just `navigate()` instead if that's the goal?

If you were using a `fetcher.submit` to an `action` that mutates some data and then redirects, the use case would be more idiomatic, but I'm unsure if we'd want to block on that.  The redirect is likely intended to go to a UI that shows the updated information after the mutation.  If we allow the blocker to block that, we leave the user in an intermediate state where we have mutated data but we've blocked any type of confirmation UI so they are left in an intermediate/inconsistent UI showing potentially stale information.

It feels like in userland you could choose not to submit the fetcher if the blocking condition is true?
