### ISSUE TITLE
<HydratedRouter routes> prop

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#11652]
https://github.com/remix-run/remix/pull/9062

This enables data routers to incrementally adopt route modules

**Comment by brophdawg11** [comment]
https://github.com/remix-run/react-router/pull/11693

**Comment by brophdawg11** [comment]
Chatted with Ryan and we don't actually need/want this since you can't really mix/match these routes with vite file-based routes in any meaningful way.  

* We could patch them into an SSR app but you'd have 404/hydration errors for any client-side only routes
  * Then you also end up having to move entire route subtrees at once - and if you have a root layout route then you need to move everything all at once
* We could restrict it to SPA apps but you still have to then move everything over before you can use SSR
  * This still has the move a whole subtree at once limitation
* The `RouterProvider` `routes` is essentially what `routes.ts` will be with `lazy -> file` so there's no real reason to introduce an intermediate step - we'll just have folks go right to `routes.ts`
  * They can just move everything to `lazy` in `RouterPRovider`
  * Then switch to file and to `HydratedRouter`
