### ISSUE TITLE
[Bug]: Update comments recommending to use polyfill.io

### ISSUE THREAD

**Issue by behnam-oneschema** [remix-run/react-router#11742]
### What version of React Router are you using?

main

### Steps to Reproduce

In `useSearchParams()` impl we have:
https://github.com/remix-run/react-router/blob/2f25789e60412aa5ed02442f81b315b1a2407562/packages/react-router-dom/index.tsx#L1463-L1472

### Expected Behavior

Another recommendation in place of:
```
      `If you're unsure how to load polyfills, we recommend you check out ` +
      `https://polyfill.io/v3/ which provides some recommendations about how ` +
      `to load polyfills only for users that need them, instead of for every ` +
      `user.`
```

### Actual Behavior

N/A

**Comment by behnam-oneschema** [comment]
Context: https://www.sonatype.com/blog/polyfill.io-supply-chain-attack-hits-100000-websites-all-you-need-to-know

**Comment by udbhavgoyal-fareye** [comment]
This should be fixed by replacing the reference to polyfill.io with Cloudflare equivalent. Similiar fix has been implemented in https://github.com/thebuilder/react-intersection-observer/pull/684

More details here - https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet

**Comment by brophdawg11** [comment]
Dup of https://github.com/remix-run/react-router/issues/11733
