### ISSUE TITLE
[Docs]: Nested Routes are essentially undocumented

### ISSUE THREAD

**Issue by bootrino** [remix-run/react-router#11745]
### Describe what's incorrect/missing in the documentation

Nested Routes are explained extremely well here in only a couple of paragraphs:

https://blog.webdevsimplified.com/2022-07/react-router/

However hours of searching the official docs left me assuming nested routers cannot be done in React Router 6.

Either the docs do not exist of they are hard to find or poorly written.

**Comment by brophdawg11** [comment]
A quick search shows they are documented in a handful of places.  We're always open to improvements so if you have specific suggestions of how they could be better surfaced please let us know!

![Screenshot 2024-06-28 at 10 54 28 AM](https://github.com/remix-run/react-router/assets/1609022/f04c7470-a407-444f-8fd1-5437942723af)


https://reactrouter.com/en/main/start/overview#nested-routes
https://reactrouter.com/en/main/start/tutorial#nested-routes
https://reactrouter.com/en/main/routers/create-browser-router#routes
https://reactrouter.com/en/main/components/outlet

**Comment by bootrino** [comment]
I looked at the documentation at the links you provided.

Honestly I probably looked at that documentation whilst I was searching and it looks nothing like nested routes to me.
There is no clear and simple explanation of how for example I can have routes in a separate component.

**Comment by brophdawg11** [comment]
Ah ok - I see the confusion now.  You're not talking about what we call "Nested Routes" which is nesting UI based on the URL via `<Outlet>`.  You're referring to what we call ["Descendant Routes"](https://reactrouter.com/en/main/start/faq#how-do-i-nest-routes-deep-in-the-tree) which lets you define and render additional `<Route>` components deep in the tree via [`<Routes>`](https://reactrouter.com/en/main/components/routes). 

These are somewhat intentionally less documented as they're an older pattern that is no longer recommended since it encourages data fetching waterfalls.  The new Data APIs (`createBrowserRouter`/`RouterProvider`) decouple fetching from rendering which can lead to much better app performance.  Routes rendered via descendant `<Routes>` cannot leverage the Data APIs.  See [Picking a Router](https://reactrouter.com/en/main/routers/picking-a-router) for more info.

One of the biggest reasons folks reached for descendant `<Routes>` in prior versions was to code split sections of the route tree out of the critical bundle.  When using the data APIs, we recommend using [`route.lazy`](https://reactrouter.com/en/main/route/lazy) which gets you most of the way there and if that doesn't go far enough, we've recently released a new feature we call "Fog of War" that leys you lazily load entir eportions of the route tree: in [`unstable_patchoutesOnMiss`](https://reactrouter.com/en/main/routers/create-browser-router#optsunstable_patchroutesonmiss) that may be of interest.

I would also suggest checking out the [When to Fetch](https://www.youtube.com/watch?v=95B8mnhzoCM) conference talk from Ryan and there two blog posts ([post](https://remix.run/blog/remixing-react-router), [post](https://remix.run/blog/react-router-v6.4)) for more information on this move towards the Data APIs

**Comment by bootrino** [comment]
Just not documenting a common pattern because it's frowned upon is less effective than discussing it and the issues.

**Comment by brophdawg11** [comment]
It is documented, [here](https://reactrouter.com/en/main/start/faq#how-do-i-nest-routes-deep-in-the-tree) and in the [`<Routes>`](https://reactrouter.com/en/main/components/routes) component.  And the downsides are called out on the `<Routes>` component docs:

![Screenshot 2024-07-02 at 2 30 34 PM](https://github.com/remix-run/react-router/assets/1609022/ba1e7985-1d74-4733-83ee-bba21bde4c5e)

Do you have any specific feedback on where we could better explain this?
