### ISSUE TITLE
[Bug]: unstable_patchRoutesOnMiss leaf ignored when patching sub-trees asyncronously

### ISSUE THREAD

**Issue by Wykks** [remix-run/react-router#11748]
### What version of React Router are you using?

6.24.0

### Steps to Reproduce

https://stackblitz.com/edit/github-tgrtuk-ttgqiq?file=src%2Fapp.tsx

### Expected Behavior

When trying to patch sub-trees, it should call `unstable_patchRoutesOnMiss` when the leaf is reached.

Maybe I'm not doing it right? How can we "force" `unstable_patchRoutesOnMiss` to be called in this case?

### Actual Behavior

If you click on test, you get 
"Matched leaf route at location "/test" does not have an element or Component. This means it will render an `<Outlet />` with a null value by default resulting in an "empty" page."

**Comment by brophdawg11** [comment]
Yeah I think this is just a setup issue based on the current API design.  There is no way to force the function to be called - it is only called when the router otherwise can't match a path - i.e., a "miss" (barring splat route behavior).

By providing the parent route `/test` in the critical routes, you're allowing the router to match `/test` and it never needs to call `patchRoutesOnMiss` when navigating to `/test` because it didn't "miss".

The two options to fix this would be:

1. Remove the `/test` definition from the critical routes, thus causing a "miss" on `/test` and giving you a chance to patch it all in:

```jsx
let router = createBrowserRouter(
  [
    {
      path: '/',
      Component: RootComponent,
    },
  ],
  {
    async unstable_patchRoutesOnMiss({ path, patch }) {
      // Patch the full `/test` tree in here as a new top-level route
      if (path.startsWith('/test')) {
        patch(null, [
          {
            id: 'test',
            path: '/test',
            children: [
              {
                index: true,
                element: <div>Test</div>,
              },
              {
                path: 'another',
                element: <div>Another</div>,
              },
            ],
          },
        ]);
      }
    },
  }
);
```

2. Or, you could include the test `index` route in the critical routes so it has everything it needs to match `/test` and then only patch in `/another` when needed:


```jsx
let router = createBrowserRouter(
  [
    {
      path: '/',
      Component: RootComponent,
    },
    {
      id: 'test',
      path: '/test',
      children: [{
        index: true,
        element: <div>Test</div>,
      }],
    },
  ],
  {
    async unstable_patchRoutesOnMiss({ path, patch }) {
      // Patch the full `/test` tree in here as a new top-level route
      if (path.startsWith('/test/another')) {
        patch('test', [{
          path: 'another',
          element: <div>Another</div>,
        }]);
      }  
    },
  }
);
```

**Comment by Wykks** [comment]
I see, thanks :+1:

**Comment by Wykks** [comment]
As a sidenote; the doc (https://reactrouter.com/en/main/routers/create-browser-router#optsunstable_patchroutesonmiss) should not recommend to do something like this: 

```typescript
let router = createBrowserRouter(
  [
    {
      path: "/",
      Component: Home,
    },
    {
      id: "dashboard",
      path: "/dashboard",
    },
    {
      id: "account",
      path: "/account",
    },
  ],
  {
    async unstable_patchRoutesOnMiss({ path, patch }) {
      if (path.startsWith("/dashboard")) {
        let children = await import("./dashboard");
        patch("dashboard", children);
      }
      if (path.startsWith("/account")) {
        let children = await import("./account");
        patch("account", children);
      }
    },
  }
);
```

Because this way, the exact leaf route "/dashboard" will always show a blank page, even with a "*" route
