### ISSUE TITLE
[Bug]: react-aria-components Link - wrong href for external links integrating with React Router

### ISSUE THREAD

**Issue by universse** [remix-run/react-router#11856]
### What version of React Router are you using?

6.25.1

### Steps to Reproduce

Follow https://react-spectrum.adobe.com/react-aria/routing.html.
Here's a reproduction https://stackblitz.com/edit/vitejs-vite-jqjqfr?file=src%2FApp.tsx

### Expected Behavior

External link should be kept as is.

### Actual Behavior

External link is appended the site origin and basename.

**Comment by brophdawg11** [comment]
This is not a React Router issue - as it's not our `Link` component.  The React Router `Link` component handles external links correctly: https://stackblitz.com/edit/vitejs-vite-xradgj?file=src%2FApp.tsx

My hunch is that it's because React Aria is just using `useHref` directly to generate the href's - and `useHref` is only for use with links within your React Router app - not for external links.
