### ISSUE TITLE
[Bug]: Spurious rerender at the start of a load

### ISSUE THREAD

**Issue by julienw** [remix-run/react-router#11864]
### What version of React Router are you using?

6.26.0

### Steps to Reproduce

When a component uses `useLoaderData`, it spuriously rerenders as soon as some navigation is started, even though data still hasn't changed.

<details>
<summary>Here is some code</summary>

```js
import React from "react";
import ReactDOM from "react-dom/client";
import {
  createBrowserRouter,
  RouterProvider,
  useLoaderData,
  Form,
  Await,
} from "react-router-dom";

function ApplicationContent() {
  const { results } = useLoaderData();

  console.log("render");

  return (
    <>
      <p>{results}</p>
      <Form>
        <button type="submit">Refresh</button>
      </Form>
    </>
  );
}

const router = createBrowserRouter([
  {
    path: "/",
    element: <ApplicationContent />,
    loader: function () {
      return { results: "Hello World" };
    },
  },
]);

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);
```

</details>

Or open it in https://codepen.io/julienw/pen/yLdMKdB
Then open the web console, click refresh once, and notice that the log is output twice.

### Expected Behavior

There's no rerender until the data actually changes.

### Actual Behavior

There's a spurious rerender.

**Comment by timdorr** [comment]
Loader data is not compared for strict equality because we don't know the full structure of the data. It's often times something coming from an external data source (an API or database) that may have changed outside of the application and cannot be assumed to be the same.

You are also _technically_ creating a new object every time you call `return { results: "Hello World" }`, so that wouldn't be strictly equal (i.e., `{ results: "Hello World" } !== { results: "Hello World" }`)

As a result of this, when you submit the form, we are re-running the loader and returning the data as a new instance back to the component. This happens any time the loader is re-run. It's very common for a `<Form>` action to modify the contents of the loader data, so we have re-run it to ensure it's in sync with anything external.

**Comment by julienw** [comment]
Hey @timdorr , thanks for your answer ! I think there's a misunderstanding.
I'm totally fine with 1 render, as I understand the constraints we're dealing with. However I see not 1 but 2 renders when clicking on the button: 1 right away, 1 after the loader runs. You can add a timeout to the loader or add more logs to check this further.
It would be good to reopen the bug, please :-)

**Comment by julienw** [comment]
yes, I understand this is expected due to how things work internally, but I don't understand why this would be expected from the library user point of view.
I haven't worked much with contexts in the past, maybe the "state" and the "data" should be in 2 different contexts rather than the same one?
Thanks for your consideration.
