### ISSUE TITLE
[Docs]: Content selection gets retained across page navigations in Safari

### ISSUE THREAD

**Issue by bnzone** [remix-run/react-router#12076]
### Describe what's incorrect/missing in the documentation

Hi there!

I've noticed that in Safari the selections you make with the cursor are retained across page navigations. Chrome does not have this behavior.

I've included a screen recording below. The same behavior is on the Remix docs. 
Curious about why this would be happening in Safari 🤔
Thanks!

https://github.com/user-attachments/assets/3906b66f-dadc-4534-b137-45549109edbe

**Comment by timdorr** [comment]
Since React is rendering essentially the same tree under the hood, just updating text in those nodes, it makes some sense that it would retain selection. However, we are navigating, so the browser should take this as a cue to reset the selection. This is more of a Safari issue, not something we can solve in the library.

**Comment by lauri865** [comment]
@timdorr, this happens in Chrome under certain circumstances as well – e.g. when navigating very quickly back and forth between pages. Will try to create a repro, but only happens when spamming keys.
