### ISSUE TITLE
[Bug]: Multiple setSearchParams() calls in single render cycle break

### ISSUE THREAD

**Issue by alesmenzel** [remix-run/react-router#12179]
### What version of React Router are you using?

latest

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-3qh6zw?file=src%2FApp.tsx
2. Click on "one" to navigate to `/one` path
3. Write something to input 1 (q1) and input 2 (q2)
4. Navigate to path `/one/a` using the provided links in the top
5. Observe that the first parameter is removed

### Expected Behavior

Both of the search params are kept on navigation.
The issue is that the `setSearchParams(...)` function does not have the latest previous search params - when the first effect runs, the search params are empty and we set the q1, **when the second effect runs, it still sees the previous search params as empty, even though we have already set q1 param**, therefore unsettling the `q1` param.

### Actual Behavior

`q1` is removed on navigation

**Comment by alesmenzel** [comment]
@OlegDev1 that's just hiding the real issue as well as prevents splitting the login into multiple hooks

**Comment by timdorr** [comment]
`setSearchParams` calls `navigate` under the hood. When you call it multiple times during the same render cycle, those `navigate` calls cannot communicate with each other and will overwrite the prior call. There is unfortunately no way to work around this because of how React Router and React itself are architected. 

I would have the hooks return a state value and setter and then have a separate effect or hook to update those state values in the URL as one combined value (similar to Oleg's suggestion).

```js
const [stateA, setStateA] = useStateHookA()
const [stateB, setStateB] = useStateHookB()

useEffect(() => {
  setSearchParams(prev => ({ ...prev, a: stateA, b: stateB }))
}, [stateA, stateB])
```

**Comment by alesmenzel** [comment]
@timdorr @OlegDev1 It would be nice to improve the documentation on this topic instead of closing the issue.

**Comment by OlegDev1** [comment]
@alesmenzel avoid using unnecessary use effects, check https://react.dev/learn/you-might-not-need-an-effect https://react.dev/learn/separating-events-from-effects

But yeah, one `navigate` will override another in a single render cycle, as well as, `setSearchParams`, since it uses `navigate` under the hood. So it's better to avoid this behaviour.
