### ISSUE TITLE
[Bug] v7 : json is missing

### ISSUE THREAD

**Issue by 4FunAndProfit** [remix-run/react-router#12191]
### What version of React Router are you using?

7.0.0-pre-2

### Steps to Reproduce

import {json} from 'react-router';
or import {json} from '@react-router/node';

does not work

### Expected Behavior

https://remix.run/docs/en/main/utils/json

### Actual Behavior

json not found.

Where is our friend json? :)

**Comment by Moonflower-labs** [comment]
Json is deprecated in v7. I believe it’s on the docs somewhere although they’re still work in progress. You can use the  new data utility if you need to return custom headers or status from your loaders and actions and Respose.json for resource routes 🙂 https://reactrouter.com/dev/api/react-router/data

**Comment by 4FunAndProfit** [comment]
Thanks @Moonflower-labs !
I confirm with data it works fine :)

**Comment by aaronksaunders** [comment]
but now my loader data is no longer typed without using the old `typeof loader` hack?

**Comment by Moonflower-labs** [comment]
Have a look at the [type safety explanation ](https://reactrouter.com/dev/explanation/type-safety) in the docs. Bare in mind they are wip. RRv7 generates the types.

**Comment by aaronksaunders** [comment]
Thanks for responding, I understand what it is supposed to do, it worked with json helper in previous release but since they depreciated it, the types are not completely generated. It is marked as closed and it still exists so I thought it was still appropriate to mention it. I will just open a new issue with a sample project
