### ISSUE TITLE
[Bug]: `v7_relativesplatpath` migration produces error "Matched leaf route at location [path] does not have an element or Component"

### ISSUE THREAD

**Issue by foucdeg** [remix-run/react-router#12267]
### What version of React Router are you using?

6.28.0

### Steps to Reproduce

Following the docs from https://reactrouter.com/en/main/upgrading/future#v7_relativesplatpath : 

1. Activate `v7_relativeSplatPath`
2. Migrate 
```
<Route path={`${Routes.partstore.home}*`} element={<LoadablePartStoreRoutes />}>
```
to
```
<Route path={Routes.partstore.home}>
  <Route path="*" element={<LoadablePartStoreRoutes />} />
</Route>
```
Note: `Routes.partstore.home === '/parts/'`

3. Navigate to `/parts/` via URL.

### Expected Behavior

The index for the subrouter at `<LoadablePartStoreRoutes />` should render.

### Actual Behavior

- An empty page is displayed
- The following error is printed to the console:
> Matched leaf route at location /parts/ does not have an element or Component.
- Breakpoints at module level inside `LoadablePartStoreRoutes` aren't reached.

**Comment by JoshGiacopini** [comment]
Having the same problem. Followed the recommended migration guide and it's not working.

**Comment by foucdeg** [comment]
Also worth noting that the docs for `Route` show a "TODO" under [route nesting](https://reactrouter.com/en/main/route/route#children), which is the pattern used in this migration guide.

**Comment by rekul** [comment]
Same issue

**Comment by lhartvik** [comment]
Any workaround for this issue?

**Comment by foucdeg** [comment]
@lhartvik I don't have one. I'm just not upgrading to v7 for now.

**Comment by lhartvik** [comment]
This is still an issue in react-router 7.0.1

**Comment by timdorr** [comment]
I'm not sure I'm understanding what's going on here. The flag doesn't change anything about matching, just how relative links are handled. 

Your Route components always need an element, so I would expect that to render a blank page. If there is some other expected behavior here, please put together a reproduction on Stack Blitz so we can see what's going on.

**Comment by imjordanxd** [comment]
@timdorr I'm unsure why this issue was closed. Route components don't always need an element as the docs even state that they are route prefixes otherwise: https://reactrouter.com/start/library/routing#route-prefixes

The migration docs now shows code that no longer works in React Router 7. Here's a [codesandbox] (https://codesandbox.io/p/sandbox/3m5vcx). Can we get some more clarity on what's expected?

**Comment by mrados7** [comment]
+1 for the issue. The guide on docs is clearly not working. Seems like rush decision to close this one immediately 🤷‍♂️

**Comment by jrakotoharisoa** [comment]
+1 for the issue. Still no workaround ?

**Comment by mrados7** [comment]
@jrakotoharisoa I just opened another issue, maybe that will get more attention https://github.com/remix-run/react-router/issues/12460
