### ISSUE TITLE
[Bug]: useNavigate's NavigateFunction is mixing async and non-async return types

### ISSUE THREAD

**Issue by kylsgl** [remix-run/react-router#12348]
### What version of React Router are you using?

7.0.1

### Steps to Reproduce

Initialize navigate

```ts
const navigate = useNavigate();
```

### Expected Behavior

The `navigate` function return type should be either:

```ts
void
```
or

```ts
Promise<void>
```

This would make it clear whether we need to handle a promise or not, making the behavior of `navigate` more predictable.

### Actual Behavior

`navigate` return type is

```ts
void | Promise<void>
```

**Comment by dorei44** [comment]
use this:

`Promise.resolve(navigate('/')).catch(console.log)`

**Comment by DimaAmega** [comment]
@kylsgl Check changelog: https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#exposed-router-promises

**Comment by jgarplind** [comment]
Hey @timdorr! Would you mind sharing the rationale behind closing? Not saying it's wrong in any way, just interested to know what you consider to be the solution. Is it one of the suggestions mentioned above? Or was there a code update?

**Comment by MarcusCaspeco** [comment]
> use this:
> 
> Promise.resolve(navigate('/')).catch(console.log)

Is this actually the way we're supposed to invoke `navigate` now? @timdorr

**Comment by dorei44** [comment]
@timdorr can you reopen this issue? `React.use` is not compatible with `navigate` 

![ss](https://github.com/user-attachments/assets/84a773e2-c133-462b-9e24-89a4422b5593)

**Comment by MarcusCaspeco** [comment]
@brookslybrand Is the team aware of this type issue? This issue was closed but I don't think a good solution was presented

**Comment by brophdawg11** [comment]
The tricky part about `useNavigate` is that it can return both `void` or `Promise<void>` so the type is accurate.   It forks logic internally based on whether or not you're using a data router so that we can provide a stable `navigate` function reference when using a data router.

The data router version returns the promise from `router.navigate` while the non-data-router version is a synchronous function because there's no async data loading step.

Changing the return type to `Promise<void>` would mean making the non-data-router version unnecessarily async and would also likely constitute a breaking change.

I reopened this so we can figure out the best recommendation for usage with `use` now that 19 is out.  For now, I would wrap it in app code and cast the return type if you're using a data router.  Something like:

```js
function useNavigatePromise(...args) {
  return useNavigate(...args) as (args: Parameters<NavigateFunction>) => Promise<void>
}
```

**Comment by Philipp91** [comment]
`use(navigate());` isn't the only case where this break TS checks on existing code. I also have a couple situations like:

```
const myHelper = (): void => navigate(...);  // tsc error: can't cast Promise<void> to void

navigate(...);  // ESLint error: Don't ignore the floating promise.
```

-----

> It forks logic internally

FTR that happens [here](https://github.com/remix-run/react-router/blob/a6353f8f1951184cbc75ec7e5fa9431a207e0742/packages/react-router/lib/hooks.tsx#L229). Why are they called "stable" and "unstable"?

One solution could be to expose both of those functions separately, for users who know what they're getting. More concretely, have `useNavigatePromise()` and `useNavigateVoid()` available in the library, but it starts with asserting `isDataRoute` has the right value and then calls the right internal function variant. And perhaps this requires the `NavigateFunction` type to be forked too, and `useNavigate()` would return a union type.

> Changing the return type to Promise<void> would mean making the non-data-router version unnecessarily async

Is it thinkable that this becomes a Promise in the future too, when the non-data-router version also supports data loading or for other reasons? (I have no idea whether this question even makes sense to ask.)

Would doing an extra `Promise.resolve()` in the library hurt (performance or so)?

> and would also likely constitute a breaking change.

I guess it would be the same amount of breaking as the change to `void | Promise<void>` was?

**Comment by timdorr** [comment]
> FTR that happens [here](https://github.com/remix-run/react-router/blob/a6353f8f1951184cbc75ec7e5fa9431a207e0742/packages/react-router/lib/hooks.tsx#L229). Why are they called "stable" and "unstable"?

Because the architecture of `BrowserRouter` (et. al) necessitates that when the location changes, the result of `useNavigate` will change. In the data router form, we can produce a "stable" version of `useNavigate` that won't change when the location changes and won't trigger lots of renders for components that don't actually depend on the location.

**Comment by Philipp91** [comment]
I see, thanks for the explanation!

So the stable/unstable situation is conceptually unrelated to the void/promise situation, just in today's implementation it happens to be fully correlated. That naming is fine for those two internal functions, but perhaps not worth adopting when exposing two different functions (I guess?), if that's even a reasonable solution in the first place (if so, I proposed two other names above).

**Comment by IanVS** [comment]
What is the current recommendation from the react-router team?  I guess we need a matrix of: React 18/19 and data router / non-data-router. The documentation at https://reactrouter.com/start/library/navigating#usenavigate seems woefully inadequate, unfortunately.

**Comment by Corrob** [comment]
Do we really expect everyone calling `Navigate` to use `Promise.resolve(navigate('/')).catch(console.error)` everywhere? Seems to be a very poor API... Can we expose a `useNavigateNoPromise()` that does that on every call automatically?

**Comment by harshithmohan** [comment]
> Do we really expect everyone calling `navigate` to use `Promise.resolve(navigate('/')).catch(console.error)` everywhere? Seems to be a very poor API... Can we expose a `useNavigateNoPromise()` that does that on every call automatically?

I'm just using a custom hook for now but yeah, this should be handled by the library itself.

```ts
import { useNavigate } from 'react-router';
import type { NavigateOptions, To } from 'react-router';

type NavigateFunctionVoid = {
  (to: To, options?: NavigateOptions): void;
  (delta: number): void;
};

const useNavigateVoid = () => useNavigate() as NavigateFunctionVoid;

export default useNavigateVoid;
```

**Comment by gromaco** [comment]
To avoid floating-promises error, for now, we are using [void](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void#description) when calling `navigate`:
```typescript
const navigate = useNavigate()

const takeMeToTheNextPage = () {
    void navigate('nextPage');
}

```

But would be awesome to see the recommended way from the react-router team.

**Comment by sdavids** [comment]
```ts
navigate('/');
```

triggers [@typescript-eslint/no-floating-promises](https://typescript-eslint.io/rules/no-floating-promises/).

The [proposed workaround](https://github.com/remix-run/react-router/issues/12348#issuecomment-2701099436)
```ts
void navigate('/');
```

triggers [no-void](https://eslint.org/docs/latest/rules/no-void).

**Comment by qsoo** [comment]
I am sharing this for those who are in the same situation as me. The above method did not fit me, so I applied the method of turning off lint only for this function. If you are using `typescript-eslint` v8 or higher, you may want to consider this method.

```js
'@typescript-eslint/no-floating-promises': [
        'error',
        {
          allowForKnownSafeCalls: [
            {
              from: 'package',
              name: 'NavigateFunction',
              package: 'react-router',
            },
          ],
        },
      ],
```
- Refer to: https://typescript-eslint.io/rules/no-floating-promises#allowforknownsafecalls

**Comment by MarcusCaspeco** [comment]
@brophdawg11 Can you re-open this issue? The minimal reproduction is in the description

**Comment by brophdawg11** [comment]
What action are you looking for the team to take here?  We can't change the return value because it is accurate given the fact that `useNavigate` can return `void` or `Promise<void>` depending on whether or not it's being used in a Declarative versus Data/Framework mode.  You can also use a one-liner wrap hook in your app if these eslint errors are a problem for you (or relax the lint config) so I don't see a pressing need for the library to export that one-liner?

Another option - couldn't you augment the types like this based on the router you're using?

```ts
// If using <BrowserRouter>
declare module "react-router" {
  interface NavigateFunction {
    (to: To, options?: NavigateOptions): void;
    (delta: number): void;
  }
}

// If using <RouterProvider> or Framework mode
declare module "react-router" {
  interface NavigateFunction {
    (to: To, options?: NavigateOptions): Promise<void>;
    (delta: number): Promise<void>;
  }
}
```

**Comment by IanVS** [comment]
@brophdawg11, module augmentation seems reasonable, but one thing that could help here is a clarification in the docs.  https://reactrouter.com/start/library/navigating#usenavigate does not mention anything about usage in a data router vs non data router, or compatibility concerns with React 19's `use` function.

**Comment by brophdawg11** [comment]
yeah I agree the docs should do a better job of explaining the nuance here.   If anyone wants to take a stab at a PR to update we'd be happy to accept an improvement there!

**Comment by mdmower-csnw** [comment]
> or compatibility concerns with React 19's `use` function.

@IanVS - eavesdropping here... is there a chance you could link me to this discussion? I'm not aware of this problem and would like to make sure the React 19 upgrade I performed last week doesn't have unwanted surprises.

**Comment by IanVS** [comment]
I'm referring to https://github.com/remix-run/react-router/issues/12348#issuecomment-2523085788

**Comment by kylecarhart** [comment]
@qsoo Thanks for sharing your eslint rule solution. Was very quick to implement and allows our team to keep on trucking along 😊

**Comment by brophdawg11** [comment]
Added a note to the docs in https://github.com/remix-run/react-router/commit/b0b9d98cd3d6832c00ff4ff5c3366bde9ba708c7

**Comment by vezaynk** [comment]
@brophdawg11 I don't understand why returning an empty resolved promise would be a breaking change.

Behaviorally, there is no change for code that expects nothing to be returned (they cant be consuming the value anyways, right?).

If they have linting rules, they would just need to decide whether they want to await or void it.

Is there any example of idiomatic code that it would break?

**Comment by brophdawg11** [comment]
It's a useless promise because there is nothing async about the declarative router version of `navigate`. It adds a small convenience for data router users ate the expense of declarative router users, when there already exists a user land solution for both camps via module augmentation (https://github.com/remix-run/react-router/issues/12348#issuecomment-3045470328).

**Comment by vezaynk** [comment]
I'd argue that right now it inconveniences both because it requires either an augmentation (which is a type override, really, which has no safeguards against mistakes such as change the router in your app), or dealing with the possibility of a Promise.

This seems like a middle-ground that actually serves nobody IMHO.

I think this is a mistake that should be at least revisited with an open mind for the next major release.

**Comment by brophdawg11** [comment]
It's a minor inconvenience that I'm sure we'd love to clear up in v8 when we can introduce a breaking change (this is where the github proposal comes in).  There are ~25 comments on this issue, many of them from the same folks, so from the data we have available we know of maybe ~15 folks who have voiced concern about this, so it's not something that appears to be a big issue across the landscape of react router apps in the wild.  If you open the proposal and it skyrockets with upvotes, we can absolutely re-consider doing something sooner potentially behind a future flag.

**Comment by vezaynk** [comment]
Sounds good. FWIW I don't think counting comments is a good metric. 

Developers interested in improving API design in their dependencies are few and far between. The goal should be doing things correctly regardless of how unexciting it is.

I hope I'm not coming off too strongly, I only wish for React Router to be the best it can be and appreciate all the work you and the team have put into it.

**Comment by MarcusCaspeco** [comment]
> so from the data we have available we know of maybe ~15 folks who have voiced concern about this

FWIW at the time of writing this issue has 27 upvotes, if it was open it would be the 3rd most upvoted open issue out of the 101 currently open. So I think saying that ~15 people have voiced concerns is a bit disingenuous, though I see your point that it's hard to gauge. Especially since it is a minor inconvenience (not a complete blocker) I would expect that most people aren't very vocal about their concerns with it. Proposal sounds good.
