### ISSUE TITLE
`lazy` cause render twice

### ISSUE THREAD

**Issue by fkworld** [remix-run/react-router#12511]
### I'm using React Router as a...

library

### Reproduction

https://stackblitz.com/edit/vitejs-vite-mbnd2a24?file=src%2Fapp.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    react-router: ^7.0.2 => 7.0.2 
    vite: ^6.0.3 => 6.0.3
```

### Used Package Manager

npm

### Expected Behavior

Render `App`, `Layout`, `Page` only once.

### Actual Behavior

Render `App`, `Layout` twice.

It seems that the second rendering is unrelated to the first rendering. `count` is reset to `0`.

**Comment by timdorr** [comment]
This is expected behaviour. While we wait on the lazy route to load, we will render what we can on the page. Once it's loaded, we can then re-render with the component included. You should handle this via the `hydrateFallbackElement` property on your root route or any route above the lazy route that you want to handle that.
