### ISSUE TITLE
AMD compatibility

### ISSUE THREAD

**Issue by andreaferretti** [remix-run/react-router#171]
Is there a way to use react-router as an AMD module? I have tried to pull it with requirejs, but I get `TypeError: React is undefined`. It seems that it tries to refer to a `React` variable in the global scope.

I understand that one can use react-router with browserify, but there are many situations where browserify is not enough (requirejs handles dependencies of resources other js, dynamic loading, shimming components that are not AMD and more).

**Comment by jiyinyiyong** [comment]
@rpflorence I'm late.. Thx. I managed to build code based on `0.11.6` with the `router-helper.js` solution.

**Comment by jiyinyiyong** [comment]
@hipertracker ES6 sounds good. Currently we are writing in CoffeeScript.(JSX and Router in .coffee, a bit stubborn...) I'm quite curious how you debug. Bundling tens of files(our project size, check talk.ai) into one is supposed to be slow, and what do you think about that?

**Comment by hipertracker** [comment]
@jiyinyiyong debugging is simple because you have the source maps (the same technique Coffeescript and the others are using). Some errors can be avoided by using ES6 constants. The ES6 transpiler will raise an exception if you change it's value. The bundling is quite fast because Broccoli do all transformations in the memory. And last , but not least, you do not need to build the final bundle all over the time, but only before you deploy the project.

**Comment by jiyinyiyong** [comment]
@hipertracker Sounds Broccoli is a nice option, I'd like try Broccoli someday.

**Comment by gaearon** [comment]
Webpack also has a watch mode, the cool thing is that it works both for dev builds (local dev server) *and* for production-ish builds (just add `watch: true` to config and `rsync` build output in callback).
