### ISSUE TITLE
preserve scroll position on "back"

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#186]
The new auto-scrolling feature is fantastic, but traditionally when you click "back" in a website the browser remembers the scroll position.

We should too.

**Comment by greenlaw110** [comment]
I think only half side of the issue is closed. Here is the other side that is still an issue:

Suppose I have a page `/products` contains lots of data and hence needs scroll the window. Now I have scrolled on `/products` page for 300px for example and then I've navigated to other route. After a while I decide to come back to `/products` by clicking on the side navigation menu which is generated via `Link` component, I didn't hit the back button, the `/products` page will be scrolled to the top instead of restoring my previous position. How to deal with this case?

**Comment by arunkjn** [comment]
@greenlaw110 I have the same issue. Did you find a solution to this?

**Comment by greenlaw110** [comment]
@arunkjn sorry it was long time ago. I can't remember clearly but I don't think it is resolved.
