### ISSUE TITLE
Issue with router and InfiniteScroll

### ISSUE THREAD

**Issue by ferrannp** [remix-run/react-router#295]
I am not sure if this is the proper place to write this but here you go. I am using the infinite scrolling component from https://github.com/vjeux/react-infinite-scroll/blob/master/src/react-infinite-scroll.js

When I use react-router and I write the url of my website like: http://xxx.index.html, the react-router is changing it to http://xxx.index.html#/ and this is making that the function "loadMore" from InfiniteScroll component gets called twice! (so I am fetching twice from my server).

Instead, if I write the url as http://xxx.index.html#/ directly, it works fine. Any idea of why this is happening and how to solve it?

**Comment by jedwards1211** [comment]
So this happened to me, turns out the second willTransitionTo() did a redirect but the first one didn't, yet the second one's redirect never took effect.  I think I will just add code to make it ignore the second willTransitionTo()...

**Comment by jothikg** [comment]
I am facing this similar issue and causing browser back button issue eg. I am navigating from View page (http://localhost:3000/) to Edit page (http://localhost:3000/editCard/1234) via dispatch(routeActions.push(/editCard/1234)), so it first navigate it to http://localhost:3000/editCard/panGuid1# and then http://localhost:3000/editCard/1234, when the user clicks browser back button. The page are navigating from the below sequence. 

http://localhost:3000/editCard/1234
http://localhost:3000/editCard/1234# - Unnecessary navigation
http://localhost:3000/

Expected behaviour should be http://localhost:3000/editCard/1234 -> http://localhost:3000/

is there any fix for this?

**Comment by jothikg** [comment]
Any updates on my above question?
