### ISSUE TITLE
accessing props/state on willTransition* methods

### ISSUE THREAD

**Issue by rygine** [remix-run/react-router#302]
i'm don't understand why the `willTransition*` methods are static in the first place. can someone explain this?

anyways, some of my routes require an active session (i.e. user is logged in). i want to create a mixin to attach to my route handlers to check for an active session if the `sessionRequired` prop is set to true. if there's no active session, i want to abort the current transition and go to another route, such as a login page.

maybe i'm going about this the wrong way. has anyone solved this already?

**Comment by ndreckshage** [comment]
@rpflorence how do you handle this when also rendering on server? Attach session / current user object to req object? Using a module variable could be overwritten w concurrent requests (shared variables server side).

What I'm doing is passing req through fetchData, and setting current user on req (fake, cached req for client), so that I have access to it in static methods. And also passing it through UI hierarchy, because I can't safely cache it.

**Comment by ndreckshage** [comment]
Right now I am accessing cached current user object on client, which is fine for the client -- but the redirect (authenticated route) doesn't happen until client side routes take over. Can we pass req throughout methods? Could work on a pull request.

**Comment by ndreckshage** [comment]
Found this https://github.com/rackt/react-router/pull/590 nvm!
