### ISSUE TITLE
Is there a way to tell a Link to do a replaceWith instead of transitionTo?

### ISSUE THREAD

**Issue by jackmoore** [remix-run/react-router#305]

**Comment by sdemjanenko** [comment]
+1 for adding this feature.  It could just be a boolean on the Link props.

**Comment by gaearon** [comment]
When users click a link, they expect to be able to go back. I think it's a reasonable expectation. If you want to have `replaceWith` behavior for some links, it's fine—I just don't think the router should encourage it. You can have a custom implementation in ~80 lines.

**Comment by sdemjanenko** [comment]
What if you have a list of articles and then on an article details page you have several tabs.  If the user switches tabs I don't think the back button should take them back through all the tabs which they clicked.  They might expect to be taken back to the list.

I think its super unfortunate that a custom 80 lines of code need to be written just to support this.

**Comment by ryanflorence** [comment]
I'd merge a `<ReplaceRouteLink>` pull request. Could refactor `<Link>` a bit and share nearly all of the code.

**Comment by ryanflorence** [comment]
> What if you have a list of articles and then on an article details page you have several tabs

I would expect to be taken back to the last article detail page, personally.

Though, I agree, there are certainly use-cases for a link that replaces.

**Comment by gaearon** [comment]
That's the issue. I'd expect tabs to work as normal links. Otherwise you're confusing user because there is no sure way to know if a link pushes or replaces. I think it would be bad UX.

I only needed replacing in two places:

1. When performing an action causes precious screen to be inaccessible. Like publishing a draft article. There is no way to to back to the draft once it's published. Usually you wouldn't perform actions with links.

2. When URL is updated live to reflect user input. For example, when URL is updated by typing in search field.

**Comment by ryanflorence** [comment]
Also:

```
<th><ReplaceRouteLink query={{sort: 'name'}}>Name</ReplaceLinkRoute></th>
```

**Comment by gaearon** [comment]
Valid one. You win :+1:
