### ISSUE TITLE
Using react-router with the webpack build returns a <noscript> tag

### ISSUE THREAD

**Issue by tcoopman** [remix-run/react-router#310]
I'm using react-router with webpack. Using it with the dev-server works great. But when I build my app and browse to it via file:///.... the renderComponent returns a `<noscript>` tag.

**Comment by globexdesigns** [comment]
I'm having this issue as well however I'm deploying to a real server. When I do this -- I just get a noscript tag. Why can't I use Router.HistoryLocation?

**Comment by kuchumovn** [comment]
@Zinggi 
Removing ", Router.HistoryLocation" in the "Router.run" call worked for me too.
But now HistoryLocation isn't working, obviously.

I don't know why the "fix" works and why "HistoryLocation" doesn't work with webpack-dev-server.
I'll use this fix for now.

**Comment by gaearon** [comment]
History location definitely works with webpack dev server. Can you share a reproducible example? It's very hard to guess from incomplete snippets.

**Comment by kuchumovn** [comment]
Well, I guess it's not a major bug since it's only for development and not production, but if you ask for an example, here it is:
https://github.com/kuchumovn/cinema

Installation:

bower install
npm install
sudo npm install --global bunyan
sudo npm install --global nodemon
sudo npm instal --global pm2
gulp

http://localhost:3001/webpack-dev-server/

Then, if you change this file:
https://github.com/kuchumovn/cinema/blob/master/client/application.react

in the end to:
```
	handler = (Handler) ->
		React.render(<Handler/>, document.getElementById('layout'))
	
	Router.run routes, Router.HistoryLocation, handler
```

And refresh the page, it will output the nosript tag and won't work.
"Warning: No route matches path "/index.html". Make sure you have <Route path="/index.html"> somewhere in your routes"

If you change it back to:
```
	handler = (Handler) ->
		React.render(<Handler/>, document.getElementById('layout'))
	
	if __production__
		Router.run routes, Router.HistoryLocation, handler
	else
		Router.run routes, handler
```

And refresh your page, then it will work again

**Comment by kuchumovn** [comment]
@gaearon Oh, I nailed it.
The reason was the address:
If you go to "http://localhost:3001/webpack-dev-server/" instead then everything works.
