### ISSUE TITLE
Showing NotFound route when resource is not found

### ISSUE THREAD

**Issue by zachasme** [remix-run/react-router#357]
I would like to use a global 404 page for any unmatched paths, but I am having trouble with route handlers that need to check for existence of some resource:

```
<Route path=":id" handler={ResourcePage}>
  ...
</Route>

<NotFoundRoute name="notFound" handler={ErrorNotFoundPage} />
```

In the above example the ResourcePage is going to asynchronously check for resource existence. If the identifier in the matched path does not correspond to a resource I would like to show the ErrorNotFoundPage but not change the URL.

However, I have failed to find a satisfying solution. If i abort the transition in a transition hook, the user is redirected to the previous route, and if I `this.transitionTo('notFound')` using the Transition mixin, an error is thrown due to a needed splat parameter which, when given, results in a URL change.

Is it somehow possible to force path matching to fail for a Route in a transition hook so it can continue down to the NotFoundRoute, or perhaps transition to another route without changing the URL?

**Comment by bishtawi** [comment]
Looks like the same issue as this [bug](https://github.com/rackt/react-router/issues/458). There needs to be a way to abort a route even if it matches. That way the router can continue to the 404 route and we can detect this on the server to respond with a 404 error code.

**Comment by th0r** [comment]
+1
The only workaround I see here is to use some kind of 404 flag in some Flux store and reset it every time a `router.run` callback is called.
But I think there should be easier way.

**Comment by arasmussen** [comment]
+1

This means I'm going to have to add boilerplate to all of my major routes that basically does what @ryanflorence describes above. It isn't a ton of code but it'd be awesome if I could just call this.notFound() or something and it would maintain the URL but route to the nearest <NotFoundRoute /> handler.

```
mixins: [Navigation],
componentDidMount: function() {
  fetch(this.onDataResponse);
},
onDataResponse: function(response) {
  if (response === 'not found') {
    this.notFound();
  }
},
```

Instead of having to make all of my major routes aware of my <NotFoundView />, only ReactRouter has to know about it and my major routes can pass handling back to ReactRouter to find the NotFound route.
