### ISSUE TITLE
Intercept normal anchor links 

### ISSUE THREAD

**Issue by ustun** [remix-run/react-router#393]
Sorry for reopening again since old one was closed, but thought my message on a closed issue would not be seen. What is the recommended way to intercept normal links? 

The method outlined in https://github.com/rackt/react-router/issues/197 no longer works.

**Comment by tonyxiao** [comment]
@ustun here's an alternative solution that might be cleaner and works with `react-router` 2.0
```javascript
import {browserHistory} from 'react-router'
export const navigateViaRouter = (event) => {
  event.preventDefault()
  browserHistory.push(event.currentTarget.href)
}
// Then somewhere else
const ThirdPartyLink = () =>
    <a href='/something' onClick={navigateViaRouter} />
```

**Comment by wordyallen** [comment]
@tonyxiao ... I'm still getting 
`browser.js:49 Warning: A path must be pathname + search + hash only, not a fully qualified URL like "https://github.com/"`

**Comment by steida** [comment]
Hmm, I really don't know how to make react-intl FormattedHTMLMessage with router link...

**Comment by joekrump** [comment]
@wordyallen I assume that you've already solved this issue, but if not, I solved the warning that you received by stripping out the domain name from the url so that the string that I gave to the push method was formatted as "/some-internal-link/some-other-slug" rather than "http://mydomainname.com/some-internal-link/some-other-slug"

Note that you can only use the method that @tonyxiao mentioned above for internal links in your app, not for external links to sites such as GitHub.
