### ISSUE TITLE
How to unit test handlers

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/react-router#437]
https://gist.github.com/rpflorence/1f72da0cd9e507ebec29

Until the new API shows up, this works out pretty great.

**Comment by azaharakis** [comment]
Hi the above gist, is 404ing, was hoping it would have some answers to my problem if it's still relevant. I'm having trouble understanding how one can unit test routeHandlers. In my case I have setup an app which is quite similar to the async data example in this repo, my handlers are very basic injecting async data into a another react component. 
In my test I just want to verify that the routeHandler calls the correct react component with mock data from the statics fetchData method. 
I'm using rewire to attempt to stub the react subcomponent in the handler but it still calls the actual sub component. Using rewire with my other components not going through the react-router seems to work as expected.

**Comment by wayoutmind** [comment]
@azaharakis Here is a basic snippet of a TestContext provider that based off the above gist. Hopefully this helps: https://gist.github.com/wayoutmind/76e17f07409be07ffdcb

**Comment by azaharakis** [comment]
@wayoutmind, awesome, that's something what I was after!

**Comment by azaharakis** [comment]
Actually, the above method seems to work... Nothing to see here... Thanks for your help! I'll leave it up incase it helps anyone else.

**Comment by adjavaherian** [comment]
For people that are still having issues with testing React-Router based components in their own project. I've forked this repo and utilized the solution by @wayoutmind to provide test context to complicated components.  This suite uses Mocha instead of Jest and allows you to have a lot more flexibility with stubs, mocks, spies.  https://github.com/adjavaherian/mocha-react

**Comment by gregbenner** [comment]
Getting weird errors with the TestLocation recommended way to use the router to test.
Keep getting   `- TypeError: Cannot call a class as a function`
and I isolated it to TestLocation as a param in Router.run as the issue.
```coffeescript
    TestLocation.history = ['/congratulations/id-1']
    Router.run routes,TestLocation.history, (Handler) ->
        TestUtils.renderIntoDocument(<Handler />)
```

**Comment by kellyrmilligan** [comment]
@gregbenner did you ever get this worked out? i'm just starting out on getting unit tests working again with the new recommended way

**Comment by kellyrmilligan** [comment]
is memory history now the preferred way?

**Comment by wayoutmind** [comment]
@kellyrmilligan @gregbenner You'll need to construct the TestLocation in newer versions of react-router instead of setting history like this:

```javascript
new TestLocation(['/test'])
```

**Comment by wayoutmind** [comment]
I've updated my gist to show this: https://gist.github.com/wayoutmind/76e17f07409be07ffdcb

**Comment by gregbenner** [comment]
I'd also recommend not using Jest, it's really terrible. It's super slow.. depends on old versions of Node.

This article has some tips for setting up testing with React
https://medium.com/about-codecademy/testing-with-reactjs-at-codecademy-2aec88cc4e36

**Comment by kellyrmilligan** [comment]
agreed. i'm using tape with karma and just tape straight up with node. trying out wayoutminds gist

**Comment by kellyrmilligan** [comment]
i'm still hitting a bit of a brick wall here. does test location match the default route?

here's my config:

<Route name="app" path="/shows" handler={App}>
    <DefaultRoute handler={ShowsHomePage}/>
...other routes defined here...
  </Route>

I included my routes definition into the getcontext method, so it's as follows:

````
getRouterComponent: function(TargetComponent, state, data) {
    var component,
      div = document.createElement('div'),
      routes = routes;

    var location = new TestLocation(['/shows']);

    Router.run(routes, location, function (Handler) {
      var mainComponent = React.render(<Handler state={state} data={data} />, div);

      component = TestUtils.findRenderedComponentWithType(mainComponent,
        TargetComponent);
    });

    return component;

  },
````

in the console, i'm getting:
Warning: No route matches path "/shows"

i can't get it to work with a route  that has a param either. still no match. I feel like I need to include my routes, since in my handlers i'm using named routes in link components everywhere, so if I don't then I get an invariant violation. 

any ideas?
