### ISSUE TITLE
Feature: State based / other contexts matching (need something like canActivate)

### ISSUE THREAD

**Issue by valipopescu** [remix-run/react-router#7769]
We need a feature to allow the routes to be conditionally activated or match on more than just the path alone. 
In certain other frameworks there is usually a parameter to the routes that allows the route to be activated based on various parameters and sometimes allows the route to return act upon different parameters altogether (say you want most of the routes do their matching on the path meanwhile certain routes match on a certain context value or a certain state) 

Looking through your code, for what would be possible, I found a comment in the matching function and was thinking that you may have thought about the same. 
https://github.com/ReactTraining/react-router/blob/6e13acf6b9c0101bcffb67a236f29226c18c2a6b/packages/react-router/index.tsx#L714

Can you please confirm the reason for the comment and / or whether there's something in the workings for that?

We could probably code something in this regard and make a pull request.

**Comment by MeiKatz** [comment]
The term state refers to the state associated with the history API and not a state like in a state management system like Redux.

**Comment by verticaljelly** [comment]
In that case can there be something like canActivate be implemented in the router? That is, if what I said above isn't something the router team would consider beneficial.

**Comment by Diggsey** [comment]
I'll second this. It's annoying that `Switch` directly accesses the props of its children, because it means you can't define custom `Route` components.

eg. you might expect the following to work:
```javascript
const ConditionalRoute = ({allowed, ...props}) => (allowed ? <Route {...props} /> : null)
```

But actually, this just results in the route not rendering anything when active (but it can still become active).

**Comment by MeiKatz** [comment]
There were plans to add a `validate` prop to `<Route />`. There you could conditionally deactivate a route even so it would match. Anyway, what you think would be a better way for the communication between `<Switch />` (in v6 `<Routes />`) and `<Route />`?

**Comment by Diggsey** [comment]
> Anyway, what you think would be a better way for the communication between <Switch /> (in v6 <Routes />) and <Route />?

Not sure. Perhaps context could be used so that a `<Route>` element can register/deregister itself with the containing `<Routes>` elements on mount/unmount.

If you insist on accessing child elements directly, then instead of looking at `child.props`, you could call `child.type.match(child.props, ...args)` or similar. This way you can subclass `Route` to have whatever behaviour you want, and the `<Routes>` element doesn't need to understand the props of its children.

**Comment by verticaljelly** [comment]
>With the latter approach, it should also be a hard error if the Router encounters an element which is neither null, nor a subclass of a type such as <Route> which is allowed to appear there.

Why would you want the error to happen at that stage anyway ? It's not like that would happen in any production environment and in development, the developers would notice such errors right as they test said routes. 

Since the system uses two ways:
- **Declarative JSX** kind of approach in this situation the route itself would have a prop that would dictate what and how to use to route its children (by default it goes as is routing by history path), using possibly a context that is given or multiple contexts.
-  `[Partial]RouteObject`  where an array of configurations with "path" and element is given, for this one, an even better approach would be to just be given a function that would allow the routing or not, eventually alternatives to the said routing. 

This whole thing is needed in Routing for apps that use authentication, and sometimes even ACL. While for authentication it would be probably easy enough to handle it in the components, the ACL would most likely be a much more complicated job and would be very elegantly solved like I mentioned above. I would think the latter is a good portion of the applications and you'd meet a demand that's quite substantial.

**Comment by Diggsey** [comment]
> Why would you want the error to happen at that stage anyway ? It's not like that would happen in any production environment and in development, the developers would notice such errors right as they test said routes.

That's exactly what happened, and why I opened the issue. A developer added a component like the following expecting it to disable the route. It *appeared* superficially to work, but actually just made the route render nothing instead.

> const ConditionalRoute = ({allowed, ...props}) => (allowed ? <Route {...props} /> : null)

This meant that when a `Redirect` fallback was later added to this section, it did not work for routes disabled in this way.

The problem is that directly accessing the child components creates tight coupling between the parent and child: it should therefore be a hard error if the wrong child components are used.

**Comment by verticaljelly** [comment]
I understood the code the first time you wrote it but that could would have never been written in the first place should the Route have had the condition applied to itself. The other trouble I see with that code is that `ConditionalRoute` as it's written can't really work... the fact that sometimes the route is not returned whatsoever makes it impossible for the system to know that there's a possibility for that route to even exist and thus can't work. Would consider that the route descriptor stating the condition in itself would make it a lot easier to work.

**Comment by MeiKatz** [comment]
Right, I agree with @verticaljelly. The solution that is planed is `validate`:

```jsx
<Switch>
  <Route path="/admin-area" validate={() => isUserLoggedIn() && isAdmin()}>
    <AdminArea />
  </Route>
  <Redirect to="/login />
</Switch>
```

**Comment by Diggsey** [comment]
I agree that `validate` solves this specific problem.

I still think that accessing child props is inherently a bad design as it introduces the tight coupling I mentioned.

For example, let's say I want to compute the `path` dynamically, I might have:

```rust
const DynamicRoute = ({path, ...props}) => <Route path={`${prefixFromEnv}/${path}`} {...props} />
```

Again, use of `DynamicRoute` within `<Routes>` will not have the desired result and will silently do something different.

There's no good reason not to make this a hard error. If you want to allow custom components to be used here, don't introduce the tight coupling. If you want to stick with the tight coupling, don't allow custom components, since they won't work correctly *anyway*.

**Comment by chris110408** [comment]
@mjackson I would like to work on this feature

**Comment by brophdawg11** [comment]
I'm going to close this out since it's pretty stale, but also since you can use a [`loader`](https://reactrouter.com/en/main/route/loader) now to acheive what the above proposed `validate` was doing.

If there is still a feature request here that I'm missing, please open a [Proposal](https://github.com/remix-run/react-router/discussions/new?category=proposals) over in the Discussions tab so it can go through our new [Open Development](https://remix.run/blog/open-development) process.  Thanks!
