### ISSUE TITLE
[v6] - useParams doesn't capture nested params

### ISSUE THREAD

**Issue by michaelolo24** [remix-run/react-router#7803]
## Version

**6.0.0-beta.0**

## Question

Not sure if this is a bug or expected behavior, but should `useParams` be able to read nested url params? When I had my routes set up as below the `useParams` call returned an empty object.

```
<Route path="/somePath" element={<Element/>}>
    <Route path=":docID" element={<Element/>}>
        <Route path=":pageID" element={<Element/>} />
     </Route>
</Route>
```
It only worked when I switched to this form.
```
<Route path="/somePath" element={<Element/>} />
<Route path="/somePath/:docID" element={<Element/>} />
 <Route path="/somePath/:docID/:pageID" element={<Element/>} />
```
Is this expected behavior?

**Comment by jymbob** [comment]
First, your code as pasted has a closing `/>` on the outer Route in the first line.
Second, I think you want a slightly different syntax.

I'm using 
```
          <Route path=':report'>
            <Route path='' element={element}/>
            <Route path=':filter1' element={element}/>
          </Route>
```
in production

**Comment by MaximeMathyCarne** [comment]
Hello,

I have the same issue. Here is the code: 
```
      <Route path="test" element={<Test />}>
        <Route path="/" />
        <Route path=":id" element={<TestDetail />} />
      </Route >
```
useParams doesn't retrieve the "id".

**Comment by jymbob** [comment]
You need to properly nest your routes. Your second Route has a closing tag, so nothing beyond it is getting checked.

    <Routes>
      <Route path='/'>                              <---- no close quotes here
        <Route path='' element={<Base />}/>         <---- close quotes here
        <Route path=':id'>                          <---- no close quotes here
          <Route path='' element={<SubLevel/>}/>    <---- close quotes here
        </Route>
      </Route>
    </Routes>

**Comment by MaximeMathyCarne** [comment]
I used almost the same code than you. I just moved the `element={<Base />}` at top level route. But I still have the same issue, use Params does not retrieve the id. Id is always undefined whatever the route is.
```
<Routes>
  <Route path='/' element={<Base />}>             <---- element base is use here
    <Route path='' />                                            <---- no Outlet
    <Route path=':id'>
      <Route path='' element={<SubLevel/>}/>   <--- Outlet is SubLevel
    </Route>
  </Route>
</Routes>
```

**Comment by shoxter** [comment]
My use case is slightly more complicated than this, but I'm also experiencing `useParams()` returning an empty map when route params are present.

**Comment by mjackson** [comment]
`useParams` should return only the params that are present for that route (and its parents), not the params for child routes.

So, if your routes look like this:

```tsx
<Route path="/" element={<Root />}>
  <Route path=":docId" element={<Doc />}>
    <Route path=":pageId" element={<Page />} />
  </Route>
</Route>
```

and you are at `/doc123/page456`, you should get the following with `useParams`:

| Component | Params |
|-------------|-------|
| `Root` | `{}` |
| `Doc` | `{ docId: "doc123" }` |
| `Page` | `{ docId: "doc123", pageId: "page456" }` |

Is that not what you are seeing, @michaelolo24?

**Comment by bzalasky** [comment]
> Is that not what you are seeing, @michaelolo24?

I suspect @michaelolo24 was hoping that a useParams hook in a parent component would return the params for nested children, but it doesn't work this way. A use case for this is highlighting the current row in a table with a slide panel details UI open on top of the table. useMatch can be used to get the URL param value in the parent for cases like this, but it feels a bit like an escape hatch. @mjackson Is there another approach that you'd suggest instead?

**Comment by MaximeMathyCarne** [comment]
On my side, I indeed believed that all components had access to all parameters. It is clearer now and it works as @mjackson described.

**Comment by mjackson** [comment]
> a useParams hook in a parent component would return the params for nested children

I suppose we could make it work this way, but only for routes in the same `<Routes>` element. If you have more routes in a separate `<Routes>` element further down the tree (e.g. one of your route components renders another `<Routes>`) this would not be possible since the router matches from the top down. So we wouldn't even know those routes exist until we already matched and rendered the parent route component. But I believe that would satisfy your use case, @bzalasky.

**Comment by evantrimboli** [comment]
To add some more context, I've run across a similar issue. Not sure if accessing child route params is the answer, but hoping it can add some more insight.

https://stackblitz.com/edit/react-ts-rguohw?file=index.tsx

Steps:
- Click "Go to orders"
- Choose "w4" from the dropdown
- Click "current orders"
- Copy the router url from the stackblitz, should be something like "https://react-ts-rguohw.stackblitz.io/orders/w4/current"
- Refresh the stackblitz and paste the url

The issue I'm having is how to keep the select box in sync with whatever is in the url bar. In this case, because the `locationId` is handled at a lower route, I would need use `useMatch` to parse it out.

**Comment by mjackson** [comment]
Let's follow up in #7960. I believe that satisfies this use case.
