### ISSUE TITLE
[v6][Bug]: useSearchParams doesn't parse url on page load, so components initially render without that information

### ISSUE THREAD

**Issue by joegrenan** [remix-run/react-router#7941]
### What version of React Router are you using?

^6.0.0-beta.0

### Steps to Reproduce

Use `var [searchParams, setSearchParams] = useSearchParams()` and then make use of the value `searchParams` on your application's initial load, with search parameters in the URL, and watch, as react-router does not parse them on page load, and they return undefined.

### Expected Behavior

useSearchParams() should immediately parse the URL on its first call so that application code can run immediately with no issues.

### Actual Behavior

useSearchParams() does not immediately parse the URL on its first call, that application code runs into issues and each call to get the data subsequently returns old data.

**Comment by joegrenan** [comment]
![image](https://user-images.githubusercontent.com/88557276/129124015-b70bad32-4311-48b2-a725-a68c1169e10f.png)

**Comment by diegocasmo** [comment]
It looks like `useSearchParams` returns an instance of [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) (see `#createSearchParams` definition [here](https://github.com/remix-run/react-router/blob/dev/packages/react-router-dom/index.tsx#L409)) instead of a “regular” key-value pair object. 

So you'd have to use the `URLSearchParams` [utility methods](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#methods) to work with the query string instead.

**Comment by timdorr** [comment]
Correct, that is what a URLSearchParams looks like on the console. It's not actually empty:

![image](https://user-images.githubusercontent.com/17882/129586471-5687c72b-3043-4aab-bb91-6aa48550758f.png)

**Comment by brophdawg11** [comment]
Can you provide a reproduction of the issue?  This works fine for me in https://codesandbox.io/s/distracted-meninsky-tq6w5v if you add a `?name=test` value to the URL

**Comment by Derp33** [comment]
My problem was a bit more niche. Seems `BrowserRouter` doesn't work as expected within an electron app. `HashRouter` works fine however... 🤔
