### ISSUE TITLE
[v6] First-class animation primitives

### ISSUE THREAD

**Issue by mjackson** [remix-run/react-router#7946]
### What is the new or updated feature that you are suggesting?

React Router v6 should include first-class primitives for supporting animations on route transitions.

A bit of history here: in v4/5, we added the `<Switch location>` prop. This prop provided a way for you to keep the `<Switch>` rendering an old location when it is rendered inside another element with a `key` that is used to perform an animation, such as a `<CSSTransition>` from react-transition-group. It looked something like this:

```tsx
function App() {
  let location = useLocation();
  return (
    <TransitionGroup>
      <CSSTransition key={location.key}>
        <Switch location={location}>
          {/* routes go here */}
        </Switch>
      </CSSTransition>
    </TransitionGroup>
  );
}
```

This API worked fine for v4 and v5, but it's not entirely clear outside of the context of animations that the `<Switch location>` prop is to be used for animations. It was proposed in #7117 that we add a `<Routes location>` prop that could be used in v6. However, since v6 is built entirely on React hooks, I think we can do better.

Instead of a `location` prop, we can provide "animated" versions of all components and hooks that give you elements to render. So, for example, the animated version of `<Routes>` would be `<AnimatedRoutes>`. You could use it exactly like `<Switch location>`, except it's much more clear what it's for.

```tsx
function App() {
  let location = useLocation();
  return (
    <TransitionGroup>
      <CSSTransition key={location.key}>
        <AnimatedRoutes>
          {/* routes go here */}
        </AnimatedRoutes>
      </CSSTransition>
    </TransitionGroup>
  );
}
```

In addition to `<AnimatedRoutes>` we can also provide:

- `<AnimatedOutlet>`
- `useAnimatedRoutes()`
- `useAnimatedOutlet()`

Each of these elements and hooks would ofc work exactly like the non-animated version but with one important difference: they don't subscribe to location updates from context. Instead, **they must be used inside another element with a `key` that will be unmounted in the transition**.

AFAICT all animation libraries for React work this way. They rely on a `key` changing on an element to know when an element is going to transition out/in.

### Why should this feature be included?

Providing animation primitives should make it easier for people to do animations between routes.

**Comment by wojtekmaj** [comment]
The problem is that it does not replace `<Switch location={…}>` entirely. This cannot replace what's being proposed in #7117 and was already implemented in #7571.
That's a great example of what can be achieved with `<Switch location={…}>`: https://reactrouter.com/web/example/modal-gallery
And even if we could create this modal gallery with `<AnimatedRoutes>`, the naming seems a little awkward - we're not doing animations, we're just doing `location` override.

**Comment by CooCooCaCha** [comment]
Also, if react-router wants to gain traction in react-native land then you'll need to be able to support stack navigation. Please see #7943 for details.

**Comment by fgatti675** [comment]
Hi, I hadn't seen this discussion and created a PR for adding `location` to `Routes`
https://github.com/remix-run/react-router/pull/7969
My grain of salt, I don't love the idea of implementing this feature as `AnimatedRoutes` since it is confusing if your use case is not related to animations. Instead, having a generic `Routes` with a location prop that can be used for multiple cases makes a lot of sense to me :)

**Comment by timdorr** [comment]
I'm not sure `<AnimatedRoutes>` really gets us anything. You still have to set up the `useLocation` hook and provide `location.key` to your animation components. That's just hiding the `location` prop, and not removing any knowledge of interacting with the current location.

Maybe a more explicit name would be clear: `<Routes staticLocation={location}>`

The point of the `location` prop for `Switch`/`Routes` is to have the route change process be controlled (much like a controlled input). While you _could_ hack around this with a custom `Router` wrapping this, I think a single prop is much more straightforward. I feel like it's a reasonable API to have, but could use better naming.

**Comment by gitcatrat** [comment]
> If you refresh the page when the modal is open, you go to the actual page for that color without the modal.

That's exactly why I've used `location` prop for many years. The whole point of it is custom context. 

I.e if you're opening a details page in modal, you're seeing it on top of feed (without losing feed position, etc) but if you send the same link to your friend, they do not need to see the feed you were scrolling, post could have been in any/personal feed.

I can't think of a better idea to build that functionality but if there's any, I'm all ears.

**Comment by gnapse** [comment]
> The modal gallery that some here have pointed out is actually busted. If you refresh the page when the modal is open, you go to the actual page for that color without the modal.

We use react-router in Todoist for the settings, which are provided in a modal UI, and the modal routing works great. What we do is that we internally set a default background URL for when the modal was not triggered by the user, but the URL was visited directly. In this case, the users get the view with the settings modal open right from the start, and the background renders the default view we set. When the users close the settings modal, they land on this view as the initial one (which would've been the page they'd get anyway if they start by visiting https://todoist.com/app).

Here's a demo:

https://user-images.githubusercontent.com/15199/131232942-6e901e62-16de-4322-b1f8-289f83a2e8a3.mp4

I trigger the modal from a view called "upcoming", the URL changes fully to not encode anything about the upcoming view being visible underneath. But the upcoming view is still underneath, and all its state preserved if the user closes the settings. In the video, however, I did not close the settings, but I refreshed. You can see that in that case I no longer get the Upcoming view underneath, but the Today view instead (with the settings modal open on top). This is the view I'd get if I visited the app's root path anyway.

This is all working, inspired by the modals example in v5 documentation. So I would not call it busted.

And the approach is great because it allows us to have users open the settings for a quick tweaking, without loosing any transient state in the page underneath (e.g. they may be in the middle of adding a task that's not yet saved, etc).

**Comment by mjackson** [comment]
> Refreshing the page to have the modal go away is actually the intended behavior.

@timdorr No it isn't :) Sorry, I shouldn't have just said the modal example was busted without digging a bit further. It turns out the example **code** isn't actually busted, just the Codesandbox browser is. My original point stands though; the modal should still be open after a page refresh. This is because `location.state` persists across the full page refresh, so when you get back to that URL you should follow the exact same logic in the `<ModalSwitch>` component.

Here's how it should work (running in Chrome):

![ModalExampleChrome](https://user-images.githubusercontent.com/92839/131424404-5d645941-8f99-46bb-bf0f-9295b2749ddb.gif)

Notice how after the page refresh the modal is still open.

Here's the broken behavior I mentioned, where the modal is not still open after the page refresh (running in the Codesandbox browser in our docs):

![ModalExampleCodesandbox](https://user-images.githubusercontent.com/92839/131427983-72f05438-1fcf-4363-b5b3-6eae8592cc59.gif)

Notice how after the page refresh the modal isn't open anymore. That's busted. My guess is the Codesandbox browser doesn't support `location.state`. We should probably fix that! (either by letting the fine folks at Codesandbox know or by finding a similar product that is able to run our demos, but I digress...)

> if you send the same link to your friend, they do not need to see the feed you were scrolling

@gitcatrat Yes, we agree the modal should not be there **in a new window** (i.e. your friend's). But if all you're doing is **refreshing the existing page** (same user, not your friend) you should still see the modal in our example.

But anyway, getting back to the original discussion: it's fairly easy to mimic the current modal example without the `<Switch location>` prop. [I forked the modal example and created a simpler version that doesn't rely on it here](https://codesandbox.io/s/react-router-modal-gallery-forked-iw3cs?file=/example.js). All you have to do is swap out the `children` of the route with the right elements you'd like to show when `location.state.background` is present. And it's simpler because you don't actually need `location.state.background` to be a valid `location` object. It could just be a simple boolean.

> Retaining prior state while navigating is super important for their UX.

I put some state in the `<Gallery>` element @timdorr so you can see it maintains its state in the forked example.

So again, I don't think that modals are a good use case for maintaining the `<Switch location>` API in v6, especially when you can get the same functionality via a much simpler API.

**Comment by gnapse** [comment]
> And it's simpler because you don't actually need location.state.background to be a valid location object. It could just be a simple boolean.

What if what I need to render in the background is not always the same, but actually driven by an actual location value that's not just boolean? Imagine I have a grid (gallery) view and a list view of the same data. Items in this data set open a modal when clicked. And no matter from which view I click them from, I want the modal to open on top of the view that triggered the modal.

How can we know here what background to render:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/15199/131431034-d352f79f-6052-4768-9b0c-82ae3eb79813.png">

**Comment by mjackson** [comment]
> How can we know here what background to render

@gnapse Use a string instead of a boolean.

```tsx
<Route
  path="/img/:id"
  children={
    background === "gallery" ? (
      <>
        <Gallery />
        <Modal />
      </>
    ) ? background === "list" ? (
      <>
        <List />
        <Modal />
      </>
    ) : (
      <ImageView />
    )
  }
/>
```

**Comment by fgatti675** [comment]
> > How can we know here what background to render
> 
> @gnapse Use a string instead of a boolean.
> 
> ```tsx
> <Route
>   path="/img/:id"
>   children={
>     background === "gallery" ? (
>       <>
>         <Gallery />
>         <Modal />
>       </>
>     ) ? background === "list" ? (
>       <>
>         <List />
>         <Modal />
>       </>
>     ) : (
>       <ImageView />
>     )
>   }
> />
> ```

So this solution is similar to what I have implemented while adapting to V6 in https://demo.firecms.co/ 
In my case, I don't have a limited set of components like `Gallery` or `List` but a dynamic set of components defined by the developer.
After going that road, I realised I had done the path matching myself, and didn't really need to include Routes or Route anymore, so I think it defeats the purpose.

Will all due respect @mjackson, I fail to understand the resistance to implement a feature, that basically involves adding a prop and connecting it to an internal API, and that is fixing so many issues (which are there because the prop was removed)

In my opinion, adding the `location` prop is a very elegant solution.
- Easy to migrate from V5
- It makes location management much easier, you can refactor your state to have a `background `string or a `modal` flag, but what is the benefit?
- It solves the animations issue, all the other cases mentioned in this thread and does not need to include a new `AnimatedRoutes`, and all the use cases we are not aware of now.
- What is disadvantage? 

I was really excited with all the new v6 routes system, it is well thought and it allows developers using my library to expand it and customise it ways that were not possible before, especially regarding nested routes. But unfortunately this little detail is breaking it for me.

**Comment by gnapse** [comment]
> > How can we know here what background to render
> 
> @gnapse Use a string instead of a boolean.
> 
> ```tsx
> <Route
>   path="/img/:id"
>   children={
>     background === "gallery" ? (
>       <>
>         <Gallery />
>         <Modal />
>       </>
>     ) ? background === "list" ? (
>       <>
>         <List />
>         <Modal />
>       </>
>     ) : (
>       <ImageView />
>     )
>   }
> />
> ```

Ok, so you're basically telling me to replicate what I've already encoded into routes as an ugly and potentially huge if/else expression in my jsx.

A few questions:

- What if I have not two but around 10 possible views/routes from which this modal can be fired?
- What if these background views are also routed using dynamic route parts?
- What if I have not one, but a couple of modals that use this approach?

It seems you're pretty determined to getting rid of this feature. I really hope you folks reconsider.

**Comment by gitcatrat** [comment]
@mjackson I can't look your example right now but maybe your implementation is broken then? Modal is not disappearing in my app when page is refreshed (but if you open the link in new tab, modal collapses).

**Comment by gitcatrat** [comment]
I'm all about simplicity but I can only see pain when looking at my routes (I'm showing like 20% basic routes here).

* modals like `login` could be opened anywhere
* `post` modal could only be opened from blog feed
* `user profile` modal could be opened from several routes

So many cases, this would be a nightmare without `location` in my humble opinion.

```jsx
<>
  <Header />

  <div className={styles.wrapper}>
    <Switch location={background || location}>
        <Route exact path="/"><Home /></Route>
        <Route path="/login"><Login /></Route>
        <Route path="/user/:id"><UserProfile /></Route>
        <Route path="/post/:id"><CommunityPost /></Route>
        <Route path="/blog/:id/:sort?"><Blog /></Route>
        <Route path="/blog"><Blog /></Route>

        <Route><NotFound /></Route>
    </Switch>

    <Footer />

    {background &&
      <Modal previousPath={background.pathname}>
        <Switch>
          <Route path="/login"><Login /></Route>
          <Route path="/user/:id"><UserProfile /></Route>
          <Route path="/post/:id"><CommunityPost /></Route>
        </Switch>
      </Modal>
    }
  </div>
</>
```

**Comment by mjackson** [comment]
> Ok, so you're basically telling me to replicate what I've already encoded into routes as an ugly and potentially huge if/else expression in my jsx.

@gnapse All I did was show you how to do what everyone was saying is impossible to do without the `location` prop in that one example. If you think the if/else is ugly, feel free to refactor it. I was trying to help you see the diff by changing as little code as possible.

> In my opinion, adding the `location` prop is a very elegant solution.

@fgatti675 I can see why you'd think that for a modal, but I also feel like it's kind of an awkward solution for animation (which is the topic of this issue). For example, maintaining a separate `location` state just so you can plug it into a `<Switch location>` as it's animating out is rather awkward. It's much more elegant to use an `<AnimatedRoutes>` instead and not worry about tracking the state separately.

@gitcatrat Thank you for posting your code. I think this example much more clearly illustrates the need for the `location` prop than our current modal example from v5 does. I've reopened #7117 so we can keep discussing this use case there.

However, I still think `<AnimatedRoutes>` and `<AnimatedOutlet>` are nicer APIs for doing animation specifically than `<Switch location>` ever was. So unless someone has an objection, I think we'll plan on adding these in v6.

**Comment by timdorr** [comment]
> For example, maintaining a separate location state just so you can plug it into a <Switch location> as it's animating out is rather awkward. It's much more elegant to use an <AnimatedRoutes> instead and not worry about tracking the state separately.

Again, this isn't actually more elegant. You still need to get the location from `useLocation` and pass `location.key` into your `Transition` components. You've just removed one usage of it as a prop:

```js
let location = useLocation();
return <TransitionGroup>
  <CSSTransition key={location.key}>
    <Routes location={location}>

// vs

let location = useLocation();
return <TransitionGroup>
  <CSSTransition key={location.key}>
    <AnimatedRoutes>
```

And, more importantly, there are now two entirely different sets components/hooks to use in different situations. It becomes unclear if they can be used interchangeably or what their different props imply. Does `basename` function the same on `AnimatedRoutes` vs `Routes`? What happens if I mix up an `<AnimatedOutlet>` with an `<Outlet>`?

Maybe it would be helpful to understand the motivations behind this API removal. It seems to be to avoid some kind of common footgun that users are running into, although I'm not sure what that is exactly. Can you describe that more or give some other context? You also mentioned v6 being hook-based, but I'm not sure I understand how that factors in to a component API. 

I feel like there's some common ground amongst the stakeholders here, we just need to find it.

**Comment by mjackson** [comment]
> You still need to get the location from `useLocation` and pass `location.key` into your Transition components.

@timdorr The `<CSSTransition key>` can be ANY key, not just a `location.key`. It just needs to change whenever you want to start a new animation.

We use `location.key` in all our animation examples since we want to trigger our animations based on URL changes (link clicks, back/forward buttons, etc.). We are a routing library, after all. But if you wanted you could use any other key to kick off your animation. It could just come from a change in some local state. It's not a super compelling example (because we always encourage updating the actual URL when the page changes), but I forked our v5 animation demo [to show what this could look like](https://codesandbox.io/s/react-router-animated-transitions-forked-h3q3r?file=/example.js). The example just has a single route that renders at /, but it demonstrates the behavior nonetheless. `<AnimatedRoutes>` effectively *decouples* the need for `useLocation` from animations.

**Comment by gnapse** [comment]
> > Ok, so you're basically telling me to replicate what I've already encoded into routes as an ugly and potentially huge if/else expression in my jsx.
> 
> @gnapse All I did was show you how to do what everyone was saying is impossible to do without the `location` prop in that one example. If you think the if/else is ugly, feel free to refactor it. I was trying to help you see the diff by changing as little code as possible.

@mjackson, it is not that it is ugly. It's the fact that I'd be replicating in huge diff what react-router already does really well: mapping a location to something that should be rendered in that location.

Not just that, there are things that I suspect are impossible. I posed a question to you that's key to this point:

> What if these background views are also routed using dynamic route parts?

What if the location that's used to decide whether to render `<Gallery />` or `<List />` are of the sort of `/gallery/:projectId` and `/list/:projectId`, and both `<Gallery />` and `<List />` expect to read these URL params via the `useParams()` hook? Now that, under your suggestion, I'd be rendering them inside a route for path `/img/:id`, these two components will be effectively broken.

Do you have a suggestion on how to solve that in user land without the location prop? Even if it's ugly?

**Comment by ryanflorence** [comment]
@timdorr 

> Can you describe that more or give some other context?

Since `<Routes location>` is going to happen, so if you want to animate at the top by passing the location to routes, you can.

## Why `<Routes location>` makes sense

This `<Routes location>` API makes sense to me because Routes is the thing that:

1. Knows the route tree so it can match the location against it
2. Sets the rest of the context that every component/hook in the library needs (including `<Outlet>`)
3. Only needs the location to do all of that

Given all of that, adding `<Routes location>` is right in line with the core React concept of __controlled vs. uncontrolled components__. Routes can either be uncontrolled (gets location from context) or controlled (gets location from props).

So you can use `<Routes location>` for animations. Let's put that to the side for a minute.

## Why `<Outlet location>` doesn't make sense

**I think the most important animation use case we need to handle is `<Outlet/>`**.

Unless you're animating the **entire document**, you're going to be animating an `<Outlet>`, not `<Routes>`. Animations almost always indicate some relationship between the two routes--they're either siblings or parent/child. 

So even though `<Routes location>` will be implemented, it is actually is of little use for animations.

At first we thought maybe do the same thing: `<Outlet location/>`, but it's not so simple. Outlet's job is just to continue rendering the next slice of the nested route tree.

- It doesn't do any matching.
- It doesn't set any context.
- It has no state

It doesn't make sense to have a "controlled" version with `<Outlet location>`. There is no state to control!

So what is the actual requirement of animating elements? **The ability to freeze the world** so the exiting screen doesn't use the new location from context (and accidentally animate out the same screen that's animating in 🤦🏼‍♂️🤣)

Since outlet has no state to control, we can freeze it another way: initializing context into state on the initial render.

```tsx
function AnimatedOutlet() {
  let [context] = useState(useOutlet());
  return context.outlet;
}
```

World frozen! That's all we need. We never need updates because the animation abstraction forces remounts anyway (otherwise you can't animate, that's literally the one job of an animation library in React).

Of course, we could add `<Outlet location>` with a lot of work, more complicated code (now outlet has to become stateful and learn how to match) and strange React semantics (it's like trying to control the state of an `<option>` instead of using the value on `<select>`), but the end result would be that this:

```tsx
let spring = useSpring();
<TransitionGroup>
  <CSSTransition key={location.key}>
   <AnimatedOutlet />
  </CSSTransition>
</TransitionGroup>
```

Looks like this:

```tsx
let spring = useSpring();
<TransitionGroup>
  <CSSTransition key={location.key}>
   <Outlet location={location} />
  </CSSTransition>
</TransitionGroup>
```

Or so that this:

```tsx
const transitions = ReactSpring.useTransition(location, {/*...*/})
return (
  <div style={{ display: 'flex' }}>
    {transitions(({ /* ... */ }, location) => (
      <animated.div style={{ /* ... */ }}>
        <AnimatedOutlet />
      </animated.div>
    ))}
  </div>
)
```

Looks like this:

```tsx
const transitions = ReactSpring.useTransition(location, {/*...*/})
return (
  <div style={{ display: 'flex' }}>
    {transitions(({ /* ... */ }, location) => (
      <animated.div style={{ /* ... */ }}>
        <Outlet location={location} />
      </animated.div>
    ))}
  </div>
)
```

I see no reason to complicate the implementation of React Router just so people can pass a prop to Outlet instead of using `<AnimatedOutlet/>`.

And since we've got AnimatedOutlet, and it takes two lines of code, why not round it out the animation API `<AnimatedRoutes/>` for consistency?

Of course, more pedantic names would be `<StaticRoutes />` and `<StaticOutlet />`, but "Animated" describes the use case it's made for.

I hope this novel helps describe our thinking 😂

**Comment by CooCooCaCha** [comment]
> > if react-router wants to gain traction in react-native land
> 
> @CooCooCaCha I just remembered that you had said this, and I wanted to let you know that React Native support is not a goal for us in v6. We have supported React Router on React Native for several years now, but haven't seen very much engagement from the React Native community, unfortunately. So we are not planning on shipping v6 for React Native.

That's quite unfortunate to hear. If I'm being honest, I've been following react-router for awhile and I actually got the impression that you all never wanted to support react-native in the first place. Perhaps the community picked up on that too and went a different route.

Anyways, best of luck.

**Comment by wojtekmaj** [comment]
Coming from React DOM world I find out extremely useful to be able to use react-router based components in both web and native version of the app I'm developing. Saves me a ton of time.

Do you think there's anything we could do to help releasing RR6 for RN as well? Including financially.

**Comment by MeiKatz** [comment]
@ryanflorence I like your solution, but why don't we add a `animated` prop to `<Outlet />`? It's not that complicate to add and it would save us two additional components: `<AnimatedRoutes />` and `<AnimatedOutlet />`.

```javascript
function Outlet({ animated = false } = {}) {
  const currentOutlet = useOutlet();
  const prevOutlet = useState( currentOutlet );

  return (
    animated
      ? prevOutlet
      : currentOutlet
  );
}
```
