### ISSUE TITLE
[Bug]: Wrong nested path rendered in v6.0.0-beta.1

### ISSUE THREAD

**Issue by liho98** [remix-run/react-router#7948]
### What version of React Router are you using?

v6.0.0-beta.1

### Steps to Reproduce
Codesandbox link: https://codesandbox.io/s/dreamy-cookies-1z1og
```
function AuthRoutes() {
  return useRoutes([
  {
    path: "login",
    element: lazy(() => import("./views/Auth/Login")),
  },
  {
    path: "forget-password",
    element: lazy(() => import("./views/Auth/ForgetPassword")),
  },
])
}
```
// forget-password.jsx
```
  <Link to="/auth/login"> // in dom got rendered as /auth/auth/login
   Login
  </Link>
```
![image](https://user-images.githubusercontent.com/44250267/129432063-af991fca-65c5-4a32-8df9-bb27739780cd.png)

```
       <Route path="auth/*" element={<AuthLayout />}>
            <Route path="*" element={<AuthRoutes />} />
          </Route>
```

### Expected Behavior

it should behave as v6.0.0-beta.0, the correct should be render as /auth/login.

I think its a bug on the latest build without proper checking on nested path rendering.

### Actual Behavior

The nested paths are rendered with concatenating parent path with absolute path which is incorrect , the result rendered is /auth/auth/login
Using Link component or useNavigation both returning wrong nested path.

Solution now is fallback to v6.0.0-beta.0

**Comment by thedanwoods** [comment]
Same issue here - everything in `<Link />` or `useNavigate()` is suddenly being treated as a relative path, which makes v6.0.0-beta.1 unusable for us. It works fine in v6.0.0-beta.0.

**Comment by apolakipso** [comment]
I'm having the same issue, I don't understand how this is supposed to work.

In the CSB below I have a router with basename `/foo/bar` and a component `<Devices />` with nested routes under `/devices/*`.
The only way I've found to navigate up from within a nested route is to build a relative link like `../../`, which surely isn't how this is supposed to work.

I haven't found a way to navigate or create links to other parts of the application from a nested route, since `navigate` and `<Link/>` treat `/` as the parent route's root (`/` is resolved to `/foo/bar/devices/`)

What am I missing here? From what I've read this *absolute path* behavior in nested routes was a well thought out change for v6, but how is this *actually* going to work? (see #6777)
Specifically in the example below, how do I navigate to `/foo/bar` from `<ViewDevice />`?

https://codesandbox.io/s/react-router-v6-link-to-root-from-nested-routes-l8dl4

**Comment by jgoux** [comment]
The issue seems to be that a `basename` is set in `RouteContext`, even if not explicitly provided by the user : 

https://codesandbox.io/s/async-tdd-yvgk8?file=/src/Login.jsx (see the console)

**Comment by wojtekmaj** [comment]
I think I have related issue. 

I have a bunch of nested routes. In /form/, I have something along the lines

```jsx
    <Routes>
      {paths.map((path) => (
        <Route
          key={path}
          path={path}
          element={<p>Step {path}</p>}
        />
      ))}
      <Route path="*" element={<Navigate to={resolvedPaths[0]} />} />
    </Routes>
```

where

```
paths = ['1', '2', '3']
resolvedPaths = ['/form/1', '/form/2', '/form/3']
```

so that when you enter `/form` you're automatically redirected to `/form/1`.

When updating from 6.0.0-beta.0 to 6.0.0-beta.1, this stopped working, and redirected me to `/form/form/1` instead. `navigate()` has the same problem.

**Comment by nmarchais** [comment]
Same issue for me...

**Comment by chaance** [comment]
Fixed in https://github.com/remix-run/react-router/pull/7961
