### ISSUE TITLE
[Feature]: Allow passing component instances to the component prop

### ISSUE THREAD

**Issue by iluuu1994** [remix-run/react-router#7965]
### What is the new or updated feature that you are suggesting?

When defining a link that should be rendered as custom components there's the `component` prop provided by react-router:

```tsx
<Link to="/create" component={Button} variant="outline-primary">
    <i className="fas fa-plus" />
</Link>
```

This works nicely. Unfortunately, TypeScript will complain that the `variant` property doesn't exist on the `Link` component. The property is passed to the button internally but TypeScript doesn't know about this. Maybe that could be solved by some TypeScript hackery but I think it could be clearer if the property could be added to the button directly.

```tsx
<Link to="/create" component={<Button variant="outline-primary">}>
    <i className="fas fa-plus" />
</Link>
```

This makes it clear which property belongs to which component. The `Link` component could then simply clone the component and add the `onClick` property.

```tsx
const extendedComponent = (
    <component.type
        onClick={...}
        {...component.props}
    />
);
```

Maybe there's a technical reason why this isn't feasible, I'm relatively new to React.

### Why should this feature be included?

This would

* make it clearer what property belongs to what components
* solve the TypeScript error
* allow for any component to take multiple components as props in the future (adding the props to the root component would make it impossible to know which of the two components to add them to)

**Comment by timdorr** [comment]
As of yet, there is no equivalent API in v6 (`component` was changed to `as` and then removed later). But I'm not sure this makes sense, because it's non-typical to provide an element to these kinds of props. It's usually just the component or type string.

If you're needing to add navigation-like capabilities to an arbitrary component, then you should use `useNavigate`. Then you can very specifically choose how the component behaves, as the way it works for an `<a>` will differ from another type of element.
