### ISSUE TITLE
[Bug]: Link to and useParam decode %25 only

### ISSUE THREAD

**Issue by EthanSchoen** [remix-run/react-router#7987]
### What version of React Router are you using?

5.2.1

### Steps to Reproduce

[Here is the sandbox](https://codesandbox.io/s/react-router-url-parameters-forked-2m4p8?file=/example.js)

You can click the links provided and see the url is decoded for %25 but not %24.
Also if you type the url path of %25 the value of the param is just "%" but is "%24" for %24

### Expected Behavior

I expected %25 not to be decoded like all other encoded special characters

### Actual Behavior

%25 is the only special character code that is decoded while other special character codes are not decoded.

**Comment by EthanSchoen** [comment]
After thinking about it some more, I think https://github.com/remix-run/history/issues/505 might apply here so then this wouldn't be an issue (for link to at least)

however from this issue: https://github.com/remix-run/react-router/issues/7173#issuecomment-592030861
I thought for the case when you type %25 in the url and useParam wouldn't decode the %25 but that might be the same issue.

**Comment by shabbir-dhangot** [comment]
We are experiencing a similar issue where a parameter is automatically converting "%25" into "%".

Here is the use case:

- We need to pass "startData%253A" as an argument.
- After encode it, we send it as "startData%25253A".
- The URL we send looks like this: "https://abc.com/startData%25253A".

However, when receiving the "useParams", it automatically converts "%25" to "%". As a result, the received parameter is already decoded, and when we decode it again, it changes to "%3A". This causes a failure in our API logic.

It appears that this issue was closed without any resolution. We kindly request your assistance in addressing this matter.
