### ISSUE TITLE
[v6] [Bug]: `<Routes>` doesn't render non-`<Route>` children 

### ISSUE THREAD

**Issue by rtmruczek** [remix-run/react-router#8033]
### What version of React Router are you using?

6.0.0-beta.4

### Steps to Reproduce

Previously in `6.0.0-beta.3` , I was using this syntax to wrap my `Route`s with another component that mixes in a Theme and a Layout. However, it seems like in `6.0.0-beta.4`, anything you nest directly under `Routes` is not rendered unless it's a `Route`. Wanted to see if this is expected functionality, and if there's any other pattern you recommend to achieve the same outcome.

Here's a codesandbox that reproduces the error.

https://codesandbox.io/s/pedantic-sky-ygkg4?file=/src/App.tsx

### Expected Behavior

In the codesandbox, I expect "Top Nav" to be rendered.

### Actual Behavior

Only the Route content itself is rendered.

**Comment by mjackson** [comment]
In v6 betas previous to beta.4 we would render whatever element you provided in your route config. This behavior was meant to support Reach Router-style route configs that would let you specify any element as your `<Route>` instead of using a `<Route>` directly.

beta.4 is much more strict. This means you must only use `<Route>` inside your `<Routes>` element.

In your codesandbox, all you have to do is render a `<Route>` inside your `<Routes>` element instead of a `<PageRoute>`. You can put whatever you want in your `<Route element>` prop, so you can easily pass through your `theme` variable to whatever element you want there.

```tsx
let theme = { /* ... */ };

function MyApp() {
  return (
    <Routes>
      <Route path="/" element={<PageRoute theme={theme} />} />
    </Routes>
  );
}
```

I'd also encourage you to look at using routes to specify layouts instead of using your own layout mechanism. We designed the `<Route>` API specifically to make using different layouts really easy. All you have to do is wrap your `<Route>` in a parent like `<Route element={<MyLayout />}><Route ... /></Route>` and use an `<Outlet>` inside `MyLayout` to get the child route to render.

Good luck!

**Comment by rtmruczek** [comment]
Thanks @mjackson . I really appreciate the quick response.

**Comment by Sverxsro4nik** [comment]
A <Route> is only ever to be used as the child of <Routes> element, never rendered directly. Please wrap your <Route> in a <Routes>. 
It gives me such an error when compiling. Is the code implemented as in the react-router-dom examples?

**Comment by Kisspa123** [comment]
![Screen Shot 2021-11-18 at 7 32 51 PM](https://user-images.githubusercontent.com/90581670/142712081-2cb1bb98-356a-4bbd-8d05-4d0738594053.png)

**Comment by Kisspa123** [comment]
Also define " { BrowserRouter, Routes, Route }  from 'react-router-dom';  " in the header without quotes

**Comment by MeiKatz** [comment]
@Kisspa123 in RRv6 there is no property `component` for `<Route />` components. You have to pass an instance of your component to the `element` prop, e.g.

```jsx
<Routes>
  <Route path="/product/:id" element={<ProductScreen />} />
  <Route path="/" element={<HomeScreen />} />
</Routes>
```

**Comment by davedx** [comment]
Our application was broken by this change and now needs significant work going from the v6 beta to v6.0.2.
