### ISSUE TITLE
[Bug]: 6.0.0-beta.5 Link in nested routes does not route to correct URL.

### ISSUE THREAD

**Issue by ddebarros** [remix-run/react-router#8074]
### What version of React Router are you using?

6.0.0-beta.5

### Steps to Reproduce

1. Open https://codesandbox.io/s/immutable-star-eld5z?file=/src/App.js
2. Click `App 1`
3. Click on `Content1 Link`
4. Click on `Content2 Link`
5. Notice that the url is `/app1/content1/content2` instead of `app1/content2`

### Expected Behavior

After clicking the `Content2 Link` it should navigate to **app1/content2**

Expect the same behavior as 6.0.0-beta.4

### Actual Behavior

After clicking the `Content2 Link` it navigates to **app1/content1/content2**

**Comment by Beslinda** [comment]
I have the same issue.

**Comment by mjackson** [comment]
This was an intentional change, not a bug. I have updated the beta.5 release notes to be more explicit about this change.

The core idea here is that the "match" in a splat route now includes the portion of the URL pathname that was matched by the `*`, similar to how other params work. For example, if you had a route path of `/users/:id`, and a `<Link to="inbox">` in that route, you wouldn't expect it to route to `/users/inbox`. You'd expect it to go to e.g. `/users/123/inbox`.

Splat routes now work the same way. So a `<Link to="content1">` inside a route with path `/app/*` will resolve relative to the entire URL pathname matched by that route. So if the URL is `/app/content1`, the link should resolve to `/app/content1/content1`.
