### ISSUE TITLE
[v6.0.0-beta.5][Bug]: Custom Route is not working

### ISSUE THREAD

**Issue by drmovi** [remix-run/react-router#8092]
### What version of React Router are you using?

v6.0.0-beta.5

### Steps to Reproduce

```
import React, {useState} from 'react';
import {Navigate, Route} from "react-router-dom";
import {RouteProps} from "react-router";
type AuthRouteProps = RouteProps
const AuthRoute = (props: AuthRouteProps) => {
    const [auth] = useState(false)
    if (!auth) {
        return <Navigate to="/auth" />
    }
    return <Route {...props}/>
};
export default AuthRoute;
```

then use it in App.tsx

```
function App() {
    return (
        <Router>
            <Routes>
                <Route path="/auth" element={<AuthLayout/>}/>
                <AuthRoute path="/dashboard" element={<AdminLayout/>} />
                <Route path="*" element={<Layout404/>}/>
            </Routes>
        </Router>
    );
}
```
visit `/dashboard` then it should be redirected to `/auth` but that does not happen

### Expected Behavior

visit `/dashboard` then it should be redirected to `/auth`

### Actual Behavior

visit `/dashboard` then we see dashboard page

**Comment by mjackson** [comment]
We are trying to discourage the use of "custom routes" in v6 because they don't *really* compose like other React elements. Since `<Routes>` reads all the props of its child `<Route>`s, you have to add all of `<Route>`'s props to whatever component you're using to match it. In your example, you are using the `<Route path>` prop on your `<AuthRoute>`. This is our API bleeding out into yours, which we'd like to avoid. It's also difficult for TypeScript users to add all of `Route`'s props to the props declarations for all their custom components.

Instead, you can compose in the `<Route element>` prop. See [our new auth example](https://github.com/remix-run/react-router/blob/e3cc4851d43e16958fe38acd01ad628293561469/examples/auth/src/App.tsx#L33-L40) for a good example of how this is to be done.

```tsx
      <Routes>
        <Route element={<Layout />}>
          <Route path="/public" element={<PublicPage />} />
          <Route path="/login" element={<LoginPage />} />
          <Route
            path="/protected"
            element={
              <RequireAuth>
                <ProtectedPage />
              </RequireAuth>
            }
          />
        </Route>
      </Routes>
```

This is the really beautiful thing about the `<Route element>` prop: React Router lets you compose whatever you want in there.
