### ISSUE TITLE
[v6] [Bug]: "No routes matched" warning is too noisy

### ISSUE THREAD

**Issue by thedanwoods** [remix-run/react-router#8095]
### What version of React Router are you using?

6.0.0-beta.5

### Steps to Reproduce

[Recently](https://github.com/remix-run/react-router/pull/8071) a new warning was added when no `<Route>` in a `<Routes>` matches the location. To avoid it, everything in a `<Routes>` has to fully describe everything that might happen.

But if you do something like this:-

```
<Routes>
  <Route path="/login" element={<Login />} />
  <Route path="/about" element={<About />} />
</Routes>
{userIsAuthenticated && (
  <FancyMenu>
    <Routes>
      <Route path="/feed" element={<Feed />} />
      <Route path="/profile" element={<Profile />} />
    </Routes>
  </FancyMenu>
)}
```

it fires a warning every time, because one of the groups of `<Routes>` won't include a match.

You can no longer get around this wrapping everything in a single `<Routes>` either, because `<Routes>` will no longer render non-route children, as mentioned in #8033, #8066 and #8092.

### Expected Behavior

1. In my view this warning is unnecessary and risks alert fatigue. There are legitimate cases where having no match is intentional.
2. If the contents of any `<Routes>` **should** always match any location that's expected to occur, this should be documented (and there should be a reason for it). 

### Actual Behavior

It fires a warning every time a match is not found, even though it's harmless and the developer did it on purpose. I can understand why an optional warning might be helpful in some circumstances, but it's continually firing on patterns which (as far as I know) are valid.

**Comment by mjackson** [comment]
With that warning we are trying to avoid the situation where someone renders a `<Routes>`, nothing matches, and the page is blank. A blank page with nothing in the console is the worst.

What you're doing is a little more advanced than the typical use case since there are times when you expect a `<Routes>` to render nothing. Maybe we could follow React's lead here and add a `suppressHydrationWarning` kind of prop? Something like `<Routes suppressNoMatchWarning={true}>`.

**Comment by fadi-george** [comment]
Im also experiencing this as well, I would think "*" should not log that warning, e.g. for something like this:
```
    <Routes>
      <Route element={<Page1 />} path="path-1" />
      <Route element={<Page2 />} path="path-2" />

      {/* Private Routes */}
      <Route
        element={
          !isAuth ? (
            <Navigate
              ...
              to="/login"
            />
          ) : (
            <Routes>
              <Route element={<Account />} path="path-3" />
              <Route element={<Content />} path="path-4" />
            </Routes>
          )
        }
        path="*"
      />
    </Routes>
```
If they were to access a private route like path-3, it's logging the warning even though its present

**Comment by artola** [comment]
> With that warning we are trying to avoid the situation where someone renders a `<Routes>`, nothing matches, and the page is blank. A blank page with nothing in the console is the worst.
> 
> What you're doing is a little more advanced than the typical use case since there are times when you expect a `<Routes>` to render nothing. Maybe we could follow React's lead here and add a `suppressHydrationWarning` kind of prop? Something like `<Routes suppressNoMatchWarning={true}>`.

@mjackson We have our unit testing full of this warnings that really make a lot of noise, therefore we need to sniff the console and remove them or some other hack (adding `<Route path="*" element={null} />`). For example, when we render a single page containing:

```
<Routes>
  <Route path="somepath" element={<SomeDialog />}>
</Routes>
```
I would prefer that the user has a flag to opt-in. This will make it backward compatible.

**Comment by chasm** [comment]
I can't figure out how to get rid of this warning when using a route to an internal id via `hash`. I'm adding a "skip to content" link and however I do it, `Link` or `<a />`, I get `No routes matched location "/#main-content"`. Very annoying. Is there another way to stop this or do we need the above flag?

**Comment by TomasKomprs** [comment]
So because of this warning, we cant split routes into more files or we can but we have a warning. We have to have a single long file where are all routes. Or is there a way how to split routes into many files and connect them in one root without warning?

**Comment by bhj** [comment]
I seem to be getting these warnings erroneously when setting a `basename` on `BrowserRouter`. For example, with a basename of `/test/` and very simple route config

```
<Routes>
  <Route path='account' element={<AccountView/>}/>
  ...
</Routes>
```

`/test/account` renders properly and NavLinks correctly prefix the basename, but in the console I get `index.js:52 No routes matched location "/account" `.

**Comment by lensbart** [comment]
> Maybe we could follow React's lead here and add a `suppressHydrationWarning` kind of prop? Something like `<Routes suppressNoMatchWarning={true}>`.

This seems to be the ideal approach, though maybe this prop could be named `optional`.

**Comment by tondi** [comment]
In case anyone looking for a possible solution wonders where the warning may be originating: 
You may have a `<Routes>` component that is rendered now by your application, and don't have any `<Route path="*" />` fallback so the `No routes matched` is thrown. Try to find that `<Routes>` that is being rendered now and doesn't have any route matching with current location.

**Comment by melloware** [comment]
We have something similar that I can't seem to get around. We are using Microsoft Azure Authentication and we have our app like this...which wraps the MSAL code for authentication and redirecting to login.microsoft.com etc.  And in the console we get these warnings constantly....

```xml
ReactDOM.render(
    <React.StrictMode>
        <HashRouter>
            <SecureApplication instance={msalInstance}>
                    <App />
            </SecureApplication>
        </HashRouter>
    </React.StrictMode>,
    document.getElementById('root')
);
```

Console:
```
       No routes matched location "code=0.AQcA_yqYY2z7IkyXO3DkrPt....
```

I shortened it for brevity because its a Microsoft Base64 call to login.microsoft.com.

**Comment by ml242** [comment]
I have also been getting this warning. I have a lot of dynamic routes that can't be accessed certain times because of user state, or other routes that are included sometimes and not others. It makes it tough to track down where the warnings come from but everything in the app works fine. If this was an opt-in, that would be greatly preferable. Adding a piece like this

```<Route path="*" />

to suppress messages seems like too much.

**Comment by brophdawg11** [comment]
I'm going to close this out since it's quite stale and a feature request versus a bug.  If this is still a desired feature, please open a new [Proposal](https://github.com/remix-run/react-router/discussions/new?category=proposals) so it can go through our new [Open Development Process](https://remix.run/blog/open-development).  Thanks!
