### ISSUE TITLE
[v6] [Feature] Access router `history` object to listen for location updates

### ISSUE THREAD

**Issue by AdeonMaster** [remix-run/react-router#8211]
In the v5 I used this hook in order to listen for location updates:

```ts
import { useEffect } from 'react';
import { useHistory } from 'react-router';

const useOnLocationChange = (handleLocationChange: any) => {
  const history = useHistory();

  useEffect(() => {
    const unlisten = history.listen(handleLocationChange);
  
    return () => {
      if (unlisten) {
        unlisten();
      }
    };
  }, [history, handleLocationChange]);
};

export default useOnLocationChange;

```
Are there any plans to bring back the ability for accessing Router history object?  Do we have any alternatives for this in v6?

**Comment by Grapedge** [comment]
Does [useLocation](https://reactrouter.com/docs/en/v6/api#uselocation) work in your use case?

**Comment by AdeonMaster** [comment]
Oh yes, it might be!

**Comment by JamesGelok** [comment]
I'm not sure why they removed `useHistory` but maybe because it's considered an implementation detail now.

I'd recommend detecting changes with `useLocation` because it's officially exported.

----

That being said... 

There's an UNSAFE way of getting the history object in react-router-dom@6.0.0-beta.8 (SUBJECT TO CHANGE AT ANY POINT IN FUTURE VERSIONS). 

Bunch of implementation details to why it works:

1. [`history` is passed to `navigator` prop in `<BrowserRouter/>`](https://github.com/remix-run/react-router/blob/10403ae64663d7b519ac12af060e642318159507/packages/react-router-dom/index.tsx#L157)
2. [`navigator` prop is saved in `NavigationContext.Provider`](https://github.com/remix-run/react-router/blob/10403ae64663d7b519ac12af060e642318159507/packages/react-router/index.tsx#L261-L316)
3. [You can UNSAFELY consume the `NavigationContext` via `UNSAFE_NavigationContext` and take the `navigator` (`history` if you're using `BrowserRouter`)](https://github.com/remix-run/react-router/blob/10403ae64663d7b519ac12af060e642318159507/packages/react-router-dom/index.tsx#L100-L118).


HOWEVER DON'T DO THIS. (pass `UNSAFE_NavigationContext` to `useContext` and rip the key `navigator` off which represents the `history` object)


```tsx
///////////////////////////////////////////////////////////////////////////////
// DANGER! PLEASE READ ME!
// We provide these exports as an escape hatch in the event that you need any
// routing data that we don't provide an explicit API for. With that said, we
// want to cover your use case if we can, so if you feel the need to use these
// we want to hear from you. Let us know what you're building and we'll do our
// best to make sure we can support you!
//
// We consider these exports an implementation detail and do not guarantee
// against any breaking changes, regardless of the semver release. Use with
// extreme caution and only if you understand the consequences. Godspeed.
///////////////////////////////////////////////////////////////////////////////

/** @internal */
export {
  UNSAFE_NavigationContext,
  UNSAFE_LocationContext,
  UNSAFE_RouteContext
} from "react-router";
```

**Comment by AdeonMaster** [comment]
Yeah, `useLocation` method is more elegant

**Comment by Grapedge** [comment]
> I'm not sure why they removed `useHistory` but maybe because it's considered an implementation detail now.

In the document: [use useNavigate instead of history](https://reactrouter.com/docs/en/v6/upgrading/v5#use-usenavigate-instead-of-history)

> Again, one of the main reasons we are moving from using the history API directly to the navigate API is to provide better compatibility with React suspense. React Router v6 uses the useTransition hook at the root of your component hierarchy. This lets us provide a smoother experience when user interaction needs to interrupt a pending route transition, for example when they click a link to another route while a previously-clicked link is still loading. The navigate API is aware of the internal pending transition state and will do a REPLACE instead of a PUSH onto the history stack, so the user doesn't end up with pages in their history that never actually loaded.

In fact, there are some reasons, in the documentation of React Router v5:

> The history object is mutable. Therefore it is recommended to access the location from the render props of <Route>, not from history.location. This ensures your assumptions about React are correct in lifecycle hooks.

**Comment by fzaninotto** [comment]
Bumping on this one. Using location instead of history forces us to a really nasty dance with a useRef and a useeffect to avoid rerendering a component whenever the location changes. 

Having a mutable object (or a function) to grab the location in callbacks was really neat.

**Comment by Julix91** [comment]
@AdeonMaster can you please post the solution you ended up using? 

Something like this?
```
import { useEffect } from 'react';
import { useLocation } from 'react-router';

const useOnLocationChange = (handleLocationChange: any) => {
  const location = useLocation();

  useEffect(() => {
    const unlisten = handleLocationChange;
    return () => (unlisten && unlisten());
  }, [location, handleLocationChange]);
};

export default useOnLocationChange;
```

**Comment by AdeonMaster** [comment]
@Julix91 Here it is
```ts
import { useEffect } from 'react';
import { useLocation } from 'react-router';

const useOnLocationChange = (handleLocationChange: any) => {
  const location = useLocation();

  useEffect(() => handleLocationChange(location), [location, handleLocationChange]);
};

export default useOnLocationChange;
```

**Comment by PredokMiF** [comment]
React add new hook `useSyncExternalStore`, that may be used for prevent unnecessary rerender with same data.
For example in this [article](https://thisweekinreact.com/articles/useSyncExternalStore-the-underrated-react-api) we can react on exctly needed data changing and prevent rerender if it not changed. But we need to get history instance to subscribe it.
