### ISSUE TITLE
[Feature]: v6 SSR strategy seems to require client/server duplication

### ISSUE THREAD

**Issue by billyjanitsch** [remix-run/react-router#8286]
### What is the new or updated feature that you are suggesting?

Hi! Congrats on shipping v6.

I've been looking at the changes to SSR strategy, namely the removal of `context` from `StaticRouter` and the guidance not to redirect on initial render. These are [mentioned briefly in the upgrade guide](https://reactrouter.com/docs/en/v6/upgrading/v5#remove-redirects-inside-switch) but the suggested migration path doesn't seem to cover some consequences of these changes, and I'm having trouble filling in the gaps. (Related: https://github.com/remix-run/react-router/issues/7267.)

There are three basic use cases that show up in my apps that I'm having trouble adapting to v6. The general theme is that it seems like the v6 approach requires the server to know significantly more about the route configuration ahead of time in certain cases, which leads to either duplicating route configuration between client and server, or sharing it between the two in a way that seems at odds with the v6 route declaration APIs.

I'm opening this as a feature request, either for the upgrade guide to provide additional guidance, or to consider re-introducing some of the v5 mechanisms if there aren't equivalents in v6. Thanks!

### 1. Client-side redirect symmetry

Consider the following v5 app, which should redirect from `/foo` to `/bar`.

```tsx
function App() {
  return (
    <Switch>
      <Route path="/"><HomePage /></Route>
      <Route path="/bar"><BarPage /></Route>
      <Redirect from="/foo" to="/bar" />
    </Switch>
  )
}

function middleware(req, res) {
  const context = {}
  const markup = renderToString(
    <StaticRouter location={req.url} context={context}>
      <App />
    </StaticRouter>
  )
  if (context.url) {
    res.redirect(301, context.url)
  } else {
    res.send(markup)
  }
}
```

In v6, it would look like this:

```tsx
function App() {
  return (
    <Routes>
      <Route path="/" element={<HomePage />} />
      <Route path="/bar" element={<BarPage />} />
    </Routes>
  )
}

function middleware(req, res) {
  if (req.url === '/foo') {
    res.redirect(301, '/bar')
  } else {
    const markup = renderToString(
      <StaticRouter location={req.url}>
        <App />
      </StaticRouter>
    )
    res.send(markup)
  }
}
```

No issues so far. But suppose that `<HomePage>` renders a `<Link to="/foo">`. In v5, this works seamlessly: a user who clicks on this link gets redirected to `/bar`. In v6, they land on a blank screen, because there's no mechanism to redirect on a client-side transition.

In order to have a redirect route that behaves identically regardless of whether it's loaded because of a server-side or client-side nav, it seems that the redirect now needs to be re-declared on the client:

```tsx
function App() {
  return (
    <Routes>
      <Route path="/" element={<HomePage />} />
      <Route path="/bar" element={<BarPage />} />
      <Route path="/foo" element={<Navigate to="/bar" replace />} />
    </Routes>
  )
}
```

This works because the route will never be rendered on the server, but it seems unfortunate to duplicate this information in two places. The redundancy can be cleaned up by pulling the list of redirect rules into a constant that is shared between the server and client, but is the expectation that every v6 SSR app needs to implement something like this?

### 2. Fallback redirects

Consider the following v5 app, which redirects to `/foo` only if no other route matches.

```tsx
function App() {
  return (
    <Switch>
      <Route path="/foo"><FooPage /></Route>
      <Route path="/bar"><BarPage /></Route>
      <Redirect to="/foo" />
    </Switch>
  )
}
```

In order to implement this behavior in v6, it seems that the server would need to know about _all_ valid app routes, so that it can decide whether to perform the fallback redirect:

```tsx
function middleware(req, res) {
  if (['/foo', '/bar'].includes(req.url)) {
    const markup = renderToString(
      <StaticRouter location={req.url}>
        <App />
      </StaticRouter>
    )
    res.send(markup)
  } else {
    res.redirect('/foo')
  }
}
```

Again, this can be cleaned up by moving all route config into a constant that is shared between client/server, but is that the expected solution? It seems like it would get quite hairy for any reasonably complicated app, especially accounting for dynamic path segments, wildcards, etc. all declared in nested fashion using the new v6 APIs.

### 3. Status codes

Consider the following v5 app, borrowed loosely from [the v5 docs](https://v5.reactrouter.com/web/guides/server-rendering/404-401-or-any-other-status), that displays a 404 page with the correct HTTP status as a fallback route:

```tsx
function NotFound() {
  return (
    <Route
      render={({staticContext}) => {
        if (staticContext) staticContext.status = 404
        return '404 Not Found'
      }}
    />
  )
}

function App() {
  return (
    <Switch>
      <Route path="/foo"><FooPage /></Route>
      <Route component={NotFound} />
    </Switch>
  )
}

function middleware(req, res) {
  const context = {}
  const markup = renderToString(
    <StaticRouter location={req.url} context={context}>
      <App />
    </StaticRouter>
  )
  res.send(context.status || 200, markup)
}
```

Adapting this to v6, it has a similar issue as the previous example: the status code needs to be set by the server, so it seems that the server needs to know about all valid routes so that it can decide whether to do so. This also removes the colocation of the declaration of the 404 page with the fact that it should 404.

### Why should this feature be included?

See above.

**Comment by mjackson** [comment]
Re: client-side symmetry:

> it seems unfortunate to duplicate this information in two places. The redundancy can be cleaned up by pulling the list of redirect rules into a constant that is shared between the server and client, but is the expectation that every v6 SSR app needs to implement something like this?

It depends on your app. Consider that the only time you'll ever hit the client-side redirect is on a client-side transition, presumably because you're still shipping broken links in your app. So if you fix those links you shouldn't need the client-side redirect. Anyone who clicks on a broken link from another site or email that you sent out will never hit the client-side redirect because the server redirect will send them to the right spot.

Re: fallback redirects and status codes:

These are basically the same concern IMO, and you bring up some good points about co-locating your redirect information with the rest of your routes. Thank you for the thoughtful comments.

Our thinking is that if you need this in v6, you're probably better off bypassing `<StaticRouter>` and using our low-level `matchRoutes()` and `renderMatches()` APIs than invoking `render(<StaticRouter />)` just so you can have some side effects on the `context` object. `matchRoutes()` allows you to specify all your routes as plain objects (you can even use `createRoutesFromChildren()` if you really love the`<Route>` API) and tells you whether or not there was a match. So you can do something like this:

```tsx
let routes = [
  { path: '/foo', element: <FooPage /> },
  { path: '/bar', element: <BarPage /> },

  // You can put anything you want on these objects. You'll get the same
  // object back from matchRoutes().
  { path: '/broken-foo', redirectTo: '/foo', status: 301 }
]

let matches = matchRoutes(routes, req.url);

if (matches == null) {
  return res.send(404); // no routes matched
}

let redirect = matches.find(m => m.route.redirectTo);

if (redirect) {
  let { redirectTo, status } = redirect.route;
  return res.redirect(redirectTo, status || 302);
}

let markup = ReactDOMServer.renderToString(
  renderMatches(matches)
);

res.send(markup);
```

Then, when it comes time to render in the client, you can reuse those same routes with `useRoutes(routes)` to get the element you need.

```tsx
import routes from './routes';

function App() {
  return useRoutes(routes);
}

ReactDOM.render(
  <BrowserRouter>
    <App />
  </BrowserRouter>
);
```

I know this might seem a little inconvenient, but we're trying to avoid calling `render()` unnecessarily on the server when all you really need to do is redirect. React is for your UI. If you're not rendering UI, you shouldn't need it. That's the philosophy, anyway.

I should note that it still may prove more convenient to just provide a `<Redirect>` component in the end and `<StaticRouter context>` and do it like we did in v5. I'm not completely opposed to that. But I'd like to avoid it if we can.

**Comment by htdangkhoa** [comment]
Hi @billyjanitsch I think my solution can help you

https://github.com/htdangkhoa/react-ssr-starter/blob/main/src/server/render/index.js#L56

**Comment by firasdib** [comment]
I'm actually in the process of re-writing large parts of an application I maintain, and decided to move from RR5 to RR6. So far I have only encountered two issues: this one and the animation of routes (still unsolved).

For me, I echo the reasons outlined by @billyjanitsch - its how much of my app functioned in RR5, and keeps the logic isolated in one place. Perhaps the routes could be extracted out into their own file, and read by the server and client, but this isn't something I have explored in greater detail. The most important thing for me is to avoid the double maintenance issue, which is why I actually just re-created my own `<Redirect />` component with RR6. When I render on the server I pass my own custom context and fill that with details about the redirect, if any is encountered. On the client, it simply renders a `<Navigate />`. This is a simple enough workaround for my purposes, but I don't see any clear advantage of RR6 not supporting this natively - its not very complex logic and its maybe 10 loc total. 

Fwiw, I think the solutions outlined by @mjackson and @htdangkhoa are fair and fairly clean, but I prefer having the declarative approach in my react code - it just feels simpler somehow. Almost all my routes end with a redirect if no match was found.

**Comment by tbarrella** [comment]
Thank you for https://github.com/remix-run/react-router/issues/8286#issuecomment-963845433. There are a couple difficulties I'm finding with this:
- The TypeScript type definitions don't support adding arbitrary fields to the objects in `routes` and then retrieving them from the return value of `matchRoutes`
- It's not clear how to retrieve page-level properties (like title or description) from `matchRoutes` since there can be multiple matches. Is there a straightforward way to get the outermost matched component, e.g. is it just the first match?

**Comment by gregmartyn** [comment]
There are times when we want to redirect based on logic that is more complicated than just paths. Maybe the user is trying to navigate somewhere they're not allowed to, but we don't know that until some request completes. <Redirect> let us do that in a reactive way that worked isometrically.

**Comment by lee-alexander** [comment]
I agree with @gregmartyn, with v5 I often`<Redirect />` based on properties of the logged in user (or if any user is even logged in) based on the results of a GraphQL query in my component, which just works on both server and client. The alternative v6 implementation ends up requiring different data fetching code and route matching on the server to redirect correctly. I understand the concerns around client-only use of `<Redirect />` and the desire to get out of the way of newer React features (server streaming / suspense / etc?). But for now I'll probably just re-implement the old Redirect logic for my projects unless I find it clashing with any of those.

**Comment by brophdawg11** [comment]
Hey folks!  I think the main pain points here are now solved via the new data APIs, and we just removed the `unstable_` prefix from the SSR Data APIs in 6.6.0 (`createStaticHandler`, `createStaticRouter`, `StaticRouterProvider`).  We're still getting docs together for SSR, but you can read up on [`loader`](https://reactrouter.com/en/main/route/loader) here for redirect logic and you can check out this [SSR example](https://github.com/remix-run/react-router/tree/dev/examples/ssr-data-router) for how to use the data APIs which should handle the status code scenario.

I'm going to close this out, but if there's still a feature request I missed, please open a [Proposal](https://github.com/remix-run/react-router/discussions/new?category=proposals) over in the Discussions tab so it can go through our new [Open Development](https://remix.run/blog/open-development) process.  Thanks!

**Comment by wama2308** [comment]
https://github.com/remix-run/react-router/tree/dev/examples/ssr-data-router este ejemplo funciona con el npm run dev, pero al ejecutar npm run build && npm run start se generan varios errores

**Comment by brophdawg11** [comment]
@wama2308 Does the following change in `server.js` fix `npm run build && npm run start` for you?

```js
-        render = require(resolve("dist/server/entry.server.js")).render;
+        render = (await import("./dist/server/entry.server.mjs")).render;
```
