### ISSUE TITLE
[Feature]: Provide support for external URLs

### ISSUE THREAD

**Issue by jchitel** [remix-run/react-router#8317]
### What is the new or updated feature that you are suggesting?

APIs that take a target URL (such as `<Link>` and `useNavigate()`) should detect external URLs and navigate to them natively.

### Why should this feature be included?

I discovered today that React Router doesn't support external URLs. It assumes that any URLs passed to `<Link>` and `useNavigate()` are either relative or absolute paths on the current site.

This means that I have to write code that handles internal and external URLs differently. Internal URLs can use `<Link>`, but external URLs have to use `<a>`. Internal URLs can use `useNavigate()` but external URLs have to use `window.location`. It's a rather small inconvenience, but it can make it a pain on projects that use links across multiple domains. This seems like something that React Router or History could handle without much additional code. Any `To` value simply needs to be treated as if it may also contain a protocol and host, and if it does not match the current protocol and host, an escape hatch can simply do `window.location = blah`.

I looked around for existing issues related to this feature and found [this](https://github.com/remix-run/react-router/issues/7341). This was the only (recent) information I could find that explicitly indicated that React Router does not support external URLs. The documentation didn't actually say anything about this, so if this feature is not possible, perhaps something could be added to the documentation.

Just out of curiosity, I'd be interested in knowing why this functionality hasn't existed, because based on the above issue it seems that this was an explicit decision.

**Comment by cwilso03** [comment]
In React Router v5, this was possible, by passing an object to the `to` property in a `<NavLink>`, e.g.:

```jsx
<NavLink to={{ pathname: 'https://github.com' }} target= '_blank' name='My Link Text' />
```

But unfortunately, this seems to no longer work with React Router v6.

**Comment by timdorr** [comment]
@cwilso03 That is certainly a hack to force it to work, but I would expect that to be supported. It may break at any time.

As for the main issue, React Router is only for routing happening within your application. It's ultimately based on the browser's `history` API, which does not let you access information outside of the current page or origin for security reasons. Similarly, we're not going to support external routing because that would require us to fight the API we're trying to make use of. We're always going to lose that battle.

If you need to link to an external URL, use an `<a>` tag. If you need to redirect to an external URL, use `window.location.href`.
