### ISSUE TITLE
[Bug][v6]: StaticRouter can't import as documented

### ISSUE THREAD

**Issue by duhdugg** [remix-run/react-router#8353]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

```bash
npx create-react-app test-app
cd test-app
yarn add react-router-dom@6.0.2
```

```jsx
// src/App.js
import { StaticRouter } from 'react-router-dom/server'
```

```bash
yarn build
```

### Expected Behavior

StaticRouter should import without error, as documented here: https://reactrouter.com/docs/en/v6/upgrading/v5#get-staticrouter-from-react-router-domserver

### Actual Behavior

Error:

```
Failed to compile.

./node_modules/react-router-dom/server.mjs
Can't import the named export 'Action' from non EcmaScript module (only default export is available)
```

**Comment by timdorr** [comment]
The file definitely exists, but your tooling is pulling in the mjs version instead of the js version. The history library it's importing from doesn't have those as exports because they are just types.

I'll see if we can fix this on our end. In the meantime, you might try switching to importing from `react-router-dom/server.js`, if that will override where it imports from.

**Comment by timdorr** [comment]
Found a fix for you: https://github.com/formatjs/formatjs/issues/1395#issuecomment-518823361

I double-checked and we do actually export Action, as it's an enum and has real value in non-TS code. The problem here is really more on the build tooling side. We can see about exporting mjs files in history, but there's nothing we've done strictly "wrong" here.

**Comment by paul-mesnilgrente** [comment]
That's the same issue I had on: https://github.com/remix-run/react-router/issues/8221

**Comment by duhdugg** [comment]
Importing from `react-router-dom/server.js` (explicit .js extension) as suggested fixed it for me back when I originally had this problem.

I just checked again by dropping the `.js` from the import in my project, and I'm not having the same problem as before. I try to keep the dependencies in my project updated as much as possible, so I'm using `react-router@6.2.1` right now. `yarn list` also shows `history@5.2.0`, although I admit I am unfamiliar with how that package is related (just saw it was mentioned in #8221).

**Comment by eerapheal** [comment]
> Importing from `react-router-dom/server.js` (explicit .js extension) as suggested fixed it for me back when I originally had this problem.
> 
> I just checked again by dropping the `.js` from the import in my project, and I'm not having the same problem as before. I try to keep the dependencies in my project updated as much as possible, so I'm using `react-router@6.2.1` right now. `yarn list` also shows `history@5.2.0`, although I admit I am unfamiliar with how that package is related (just saw it was mentioned in #8221).

Thanks, This fixed it for me
