### ISSUE TITLE
[Bug]: paths with dynamic parameters do not work correctly when there is a dot in the url.

### ISSUE THREAD

**Issue by Julio-Vasquez** [remix-run/react-router#8389]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

- My application router is this:

![code1](https://user-images.githubusercontent.com/30414199/143282155-53747f50-ae2a-4ce3-b9c4-f1d829764d01.png)

- My component display id

![code](https://user-images.githubusercontent.com/30414199/143281541-87cafbb4-86b5-4263-857d-bb0243b4fb90.png)

**Url to test:** 

- Case 1: 
 http://localhost:3000/setnewpassword/10

- Case 2: (this case no found)
http://localhost:3000/setnewpassword/10.5

I apologize, my English is not good, 

### Expected Behavior

- Case 1:
![Captura](https://user-images.githubusercontent.com/30414199/143282720-d699ee15-9f36-4a0c-85cc-df862cc46e93.JPG)

- Case 2:
![Captura1](https://user-images.githubusercontent.com/30414199/143282847-e95ca491-e6bd-4670-9756-20aacfeee0f6.JPG)

### Actual Behavior

HTTP ERROR 404
![Captura2](https://user-images.githubusercontent.com/30414199/143282956-643e5770-8b07-42d5-8f7a-56238a3793a0.JPG)

I have made different tests, but when a dot **( . )** appears, the routes do not work.

**Comment by timdorr** [comment]
This appears to be an issue with your server application, not the library. I'm able to match params with periods in them.

**Comment by rfoel** [comment]
I'm late to this but I think I found the cause, and it has nothing to do with react-router. I'm using Vite and this same bug happened to me.
Whenever I input a param with a dot AND it is the last thing in the url it fails to load, so `http://localhost:3000/setnewpassword/10.5` does not work but `http://localhost:3000/setnewpassword/10.5/abc` works, and even `http://localhost:3000/setnewpassword/10.5/` (with trailing slash) works. 
I've tested with create-react-app and it works perfectly, so the issue seems to be with the way Vite serves the application on dev.
