### ISSUE TITLE
[Bug]: "*" not matching a URL with double slashes "//"

### ISSUE THREAD

**Issue by harxki** [remix-run/react-router#8428]
### What version of React Router are you using?

6.0.2

### Steps to Reproduce

1. Prepare an application that uses react router v6.
2. prepare a Route with a path of *.
    ```
    { path: "/", element: <Home /> },
    { path: "*", element: <NotFound /> }
    ```
3. access the url with multiple slashes, such as https://example.com//a

### Expected Behavior

This is also happening with Remix.
When accessing https://remix.run//a, the behavior is unintended.
Presumably, the component specified by * should be rendrering even if an unintended url string is given.

### Actual Behavior

An error occurs.
I think it's because matchRoutes returns null.

**Comment by melloware** [comment]
I concur with this issue

**Comment by vreezy** [comment]
i have the same problem with hashrouter
#%2F7
index.js:21 No routes matched location "%2F7"

nothing works:
```
<HashRouter>
 <Routes>
  <Route element={<ProcessMap {...props}/>} />
  <Route index element={<ProcessMap {...props}/>} />
  <Route path="%*" element={<ProcessMap {...props}/>} />            
  <Route path="/" element={<ProcessMap {...props}/>} />
   <Route path="/:ident" element={<ProcessPage {...props} />} />
 </Routes>
 </HashRouter>```

on `%*` it says : "index.js:21 Route path "%*" will be treated as if it were "%/*" because the `*` character must always follow a `/` in the pattern. To get rid of this warning, please change the route path to "%/*".

on each it says: "No routes matched location "%2F7" "

no way to have an entry. Blank Page is showed :/

**Comment by YousefED** [comment]
I'm running into the same issue unfortunately. I would expect * to match any value (including double slashes, if there are any). Unfortunately it either doesn't match, or returns a matched value without the double slash.

This is fixed when I remove this line: https://github.com/remix-run/react-router/blob/44fa91c2e18842dbd6cc5f77f54d51aa24a4f3b1/packages/router/utils.ts#L876

However, that causes many of the other tests to fail. I gave it a go but I lack the right understanding of the architecture to find a fix that keeps the tests stable

**Comment by brophdawg11** [comment]
This doesn't appear to be an issue anymore, I was able to setup the routes in the original issue and can match `/` (matches index), `//` (matches index), and `//abc` (matches splat) appropriately.

https://codesandbox.io/s/affectionate-dew-vzfdmq

I'm going to close this out, but if there is still a specific issue, please open a new issue with a reproduction.

**Comment by fillinmar** [comment]
this does not work with loading https://github.com/remix-run/react-router/issues/8428

**Comment by marcellobarile** [comment]
I would double check it, as I'm experiencing this issue with v7

**Comment by stefan-stankovic-greenstate** [comment]
@marcellobarile Did you solve it?

**Comment by franciscomntll** [comment]
I got it to work by doing this

```
export async function loader({ request }: LoaderFunctionArgs) {
  const url = new URL(request.url);

  if (url.pathname.includes("//")) {
    const normalizedPath = url.pathname.replace(/\/+/g, "/");
    return redirect(normalizedPath + url.search);
  }
}
```

**Comment by rob-mcgrail** [comment]
I had a version 7 situation, probably related to this, where URLs like `https://website.com//this-path` would result in my homepage route loader erroring. 

It was receiving a request.url like `"http//this-path"` which parses to a URL object with a host of `"this-path"` and a pathname of `"/"`. It would then error client side after loading up the homepage.

I ended up adding this to the homepage loader:

```
  const url = new URL(props.request.url);
  // If we've ended up with a host that isn't a "dot something" or localhost:something,
  // let's redirect to the proper homepage URL.
  if (!url.host.includes('.') && !url.host.includes(':')) {
    throw redirect('/', { status: 301 });
  }
```
We had a catchall route but it wouldn't hit it - it would hit the "/" route instead.

Suspect there's code somewhere which assumes anything after a `//` is a hostname, and then it matches on whatever route would handle "/", since that's what the path gets interpreted as. Something along those lines.
