### ISSUE TITLE
[Bug]: [ProxyFacade] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment]

### ISSUE THREAD

**Issue by ErickSharp** [remix-run/react-router#8447]
### What version of React Router are you using?

6

### Steps to Reproduce

Code usage snippet below: 
![image](https://user-images.githubusercontent.com/30361843/144786967-ec904b3e-cdbe-4dab-a5d5-1c50373f9769.png)

### Expected Behavior

Seeing that all of the children of the < Routes > component are < Route >s, it should be working correctly and not raising an error.

### Actual Behavior

Fails to work, saying that children should all be < Route >s when they already are.

**Comment by ErickSharp** [comment]
Just downgraded to version 5, changed the Routes component to a Switch, and it is working perfectly... There is something wrong here...

**Comment by aksh05** [comment]
@ErickSharp Are you using react hot loader in your app? The error seems related to that, because react hot loader wraps everything with proxies and hence you get the type of your function as [ProxyFacade], which leads to an error from react router as it verifies if there is anything other than `Route` or `ReactFragment` as children of `Routes`. Check [here](https://github.com/JamesGelok/react-router/blob/40ccb321c62c4a821f20579de5ad3b714c504e54/packages/react-router/index.tsx#L707)
You can either try removing hot loader first to verify if it is causing the issue or try fixing the hot loader issue as mentioned [here](https://github.com/gaearon/react-hot-loader/issues/1311). 

PS: Above solution is only based on what you posted here. I might very well be wrong as I don't have all the details of your app configuration.

**Comment by ErickSharp** [comment]
> @ErickSharp Are you using react hot loader in your app? The error seems related to that, because react hot loader wraps everything with proxies and hence you get the type of your function(Component) as [ProxyFacade], which leads to an error from react router as it verifies if there is anything other than `Route` or `ReactFragment` as children of `Routes`. Check [here](https://github.com/JamesGelok/react-router/blob/40ccb321c62c4a821f20579de5ad3b714c504e54/packages/react-router/index.tsx#L707)
> 
> You can either try removing hot loader first to verify if it is causing the issue or try fixing the hot loader issue as mentioned [here](https://github.com/gaearon/react-hot-loader/issues/1311). 
> 
> 
> 
> PS: Above solution is only based on what you posted here. I might very well be wrong as I don't have all the details of your app configuration. 

Yes, you are correct. I am using a hot-loader inside of an electron app. I will try the fix that you mentioned above and report back in this thread.

**Comment by johnhillphoto** [comment]
Would it be possible to add some kind of configuration option to disable this invariant error? Our app works perfectly in production, but we cannot use react-hot-loader now.  Our app worked well with v6.0.0 also.

**Comment by timdorr** [comment]
You need to move those components into the `element` prop.

**Comment by aksh05** [comment]
Thanks @timdorr, I forgot to mention that element prop should be added as well. But I still think @ErickSharp has to fix the hot loader issue in order to completely resolve the error, because RHL is anyways going to wrap the components with proxies and the same issue would occur again even after adding the element prop.

**Comment by john-kamau01** [comment]
Hello,

I think the solution to the code is to wrap the routes in a 'Routes'.

`<Routes>
    <Route path='/' element={} />
    <Route path='/path-2' element={} />
</Routes>
`
