### ISSUE TITLE
[Bug]: Scroll Restoration when re-opening the Browser

### ISSUE THREAD

**Issue by Krutsch** [remix-run/react-router#8449]
### What version of React Router are you using?

latest?

### Steps to Reproduce

1. Use a **chromium based Browser** with setting '**Continue where I left off**' 
2. Open https://remix.run/docs/en/v1/api/remix#cookie-api
3. Close the Browser
4. Open the Browser

_(Verified in Win11, Brave and Chrome)_

### Expected Behavior

Expected to be at Cookie-Api Section

### Actual Behavior

Top of the page.

**Comment by timdorr** [comment]
React Router itself doesn't provide any kind of scroll restoration.

**Comment by Krutsch** [comment]
Ok, maybe I posted this at the wrong place, but I still think this is not working as expected?

**Comment by timdorr** [comment]
I'm not totally sure what's going on, but the way the page loads when re-opening a tab/window is different from a fresh page load. My best guess is the loading order changes when it's pulled from memory instead of the network. 

I'm not really sure what we could do in this case because we don't get signals this has occurred, so we'd risk overriding a default browser behavior. 

We've generally left scroll restoration to other libraries for this reason. There are different ways of handling it and different use cases to solve for. It's best that specialized libraries handle it exactly the way they want to, so you can pick and choose the best one for your app.
