### ISSUE TITLE
In v6 want to provide useHistory in v5 version

### ISSUE THREAD

**Issue by lgf196** [remix-run/react-router#8568]
### What is the new or updated feature that you are suggesting?

In v6 want to provide `useHistory` in v5 version

### Why should this feature be included?

``` 
const history = useHistory()
return <Button onClick={()=>history.goBack()}}>Go Back</Button>
```
I want to go back to the previous history via history.goBack() but don't know how to do it in v6

**Comment by timdorr** [comment]
https://reactrouter.com/docs/en/v6/getting-started/concepts#navigate-function

**Comment by Seth10001** [comment]
@timdorr Is there an easy way to get the internal [history](https://github.com/remix-run/history/blob/main/docs/api-reference.md#listening) object and do something like this:
```js
history.listen(location => {
        log(location)
    });
```

**Comment by Seth10001** [comment]
Disregard my previous comment, I found a way to do what I needed using `useLocation`:
```js
function App() {
  let location = useLocation();

  React.useEffect(() => {
    ga('send', 'pageview');
  }, [location]);

  return (
    // ...
  );
}
```
source: https://reactrouter.com/docs/en/v6/api#uselocation

**Comment by timdorr** [comment]
Just use `useLocation` and a `useEffect` hook with the location as a dependency.

**Comment by gnapse** [comment]
It's not equivalent. I've found that the `history.listen` callback is called before the previous page is unmounted. I needed it to implement some scroll restoration functionality (I'm not using remix, only react-router), and when I used `history.listen` I was still able to access `window.scrollY` for the page that the user is leaving. When I switch to `useLocation` + `useEffect`, it does not work.

This is the workaround I used to access the history object:

```typescript
import { useLocation, UNSAFE_NavigationContext as NavigationContext } from 'react-router-dom'
import type { History } from 'history'

function useScrollRestoration() {
    // …

    const { navigator } = useContext(NavigationContext)
    const history = (navigator as unknown) as History

    // …
    useEffect(() => {
        const unlisten = history.listen(() => { /* … */ })
        return unlisten
    }, [history])
}
```

I wonder why not offer the capability more easily to access it. Is the library trying to protect its users from something?

**Comment by WoodyWoodsta** [comment]
I'm in exactly the same position. We do some more complex analysis of the history stack in order to perform some redirects, as well as create somewhat of a middleware to intercept some fo the navigations the user makes.

What doesn't really make sense to me is that there is an [intention to provide an external history instance](https://reactrouter.com/docs/en/v6/api#unstable_historyrouter), but no ability to expose the internal one. There are two reasons why someone would want to provide the history instance:

1. They want to provide their own version or extension of the instance
2. They want access to the instance used by `react-router` outside of the provided API.

So reason 2 requires either a stable way to provide the history to `react-router`, or for `react-router` to expose it, neither of which it currently does in a stable way. Since the stability is lost by means of removing the peer dependency, I wonder why this was done if the outcome is of less benefit to more complex projects?
