### ISSUE TITLE
[Feature]: get active route

### ISSUE THREAD

**Issue by jamezaguiar** [remix-run/react-router#8583]
### What is the new or updated feature that you are suggesting?

Previously i could use useRouteMatch().path to get my current route pattern, useRouteMatch is no longer supported, i've tried to use useMatch, but it always return null. It can be very usefull if exists a hook like usePathPattern

### Why should this feature be included?

For some routing features, it's important to know what route is currently active.

**Comment by timdorr** [comment]
Is there a reason you need the pattern? There is probably an alternative API you could use for the same thing. 

Regardless, this isn't possible because we now have nested routes, so there isn't necessarily a single pattern that is matched. You may also be at different levels of that nesting (if you're using `Outlet`), so you might not have the full view of the matched routes and their patterns.

**Comment by WoodyWoodsta** [comment]
I've come across this stumbling block as well.

> so there isn't necessarily a single pattern that is matched.

This is surely untrue. Yes, from the perspective of the routing definition, multiple patterns can match - but given a url, there will be a match which is rendered and therefore a reason why the particular route is being rendered? Why can we not inspect which of the patterns it was which created the condition for the route to be rendered?

**Comment by codyaweber** [comment]
I've also run into this. In my case I have nested routes, and at multiple levels of nesting. So at the top level:

```
<Router>
  <AnimatedRoutes>
    <Route path="/red/*" element={<Page className='red' link="/blue">Red</Page>} />
    <Route path="/blue/*" element={<Page className='blue' link="/red">Blue</Page>} />
  </AnimatedRoutes>
</Router>
```

And in a `Page`:

```
const Page: React.FC<PageProps> = ({ className = '', link, children }: PageProps) => {
  const navigate = useNavigate();
  
  return (
    <div className={`page ${className}`}>
      {children}
      <button onClick={() => navigate(link)}>Switch Page</button>
      <AnimatedRoutes>
        <Route path="coral" element={<Box className='coral' link="../orange">coral</Box>} />
        <Route path="orange" element={<Box className='orange' link="../cyan">orange</Box>} />
        <Route path="cyan" element={<Box className='cyan' link="../teal">cyan</Box>} />
        <Route path="teal" element={<Box className='teal' link="../coral">teal</Box>} />
      </AnimatedRoutes>
    </div>
  )
}
```

My `<AnimatedRoutes/>` component can take a `routeKey` prop which, when changed, prompts the animation to run. In RRv5, I could pass the match pattern, which would only match "up to the current route" so to speak - ie if `/red/coral` is the route, inside of a `Page`, I could know that `/red` was the match that caused that `Page` to render, and animate accordingly. The easiest way to decide when to animate a route change would be with the specific portion of the path that caused that route to render - so if at the top level, I could know that the match was `/red`, it would animate at that level of route change. Currently, if I change from `/red/coral` to `/red/orange`, `Page` has to know its own route pattern in order to use `matchPath` to determine if it should animate. Yes, it's fairly trivial to passing the pattern as a prop to the `Page`, but this feels redundant, and like a pattern that shouldn't be necessary, especially compared to v5 where that information was easily available.

Anyways, this was long-winded, and at the end of the day, isn't a huge deal. But I just wanted to point out that I think there are reasonable use cases to have this functionality in v6, and I don't see why @WoodyWoodsta's point doesn't stand that surely RR must know for certain which routes were matches and for what reasons, though I'm always open to learning more if there are some internal reasons this is difficult.

**Comment by lamplightdev** [comment]
Adding this in case it's useful for anyone. I achieved this with [`useMatches()`](https://remix.run/docs/en/v1/api/remix#usematches) - the last item in the array will contain the current route info (`{ id, pathname, data, params, handle }`) with `id` being the route, e.g.:

```js
const matches = useMatches();

const { id } = matches[matches.length - 1];

// id in my case is 'routes/dashboard/reports/$reportId/items/index'
```

**Comment by naczu** [comment]
A better approach is useLocation hook.

```
import {useLocation} from '@remix-run/react';
const location = useLocation();
console.log(location.pathname);
```

**Comment by naczu** [comment]
> Adding this in case it's useful for anyone. I achieved this with [`useMatches()`](https://remix.run/docs/en/v1/api/remix#usematches) - the last item in the array will contain the current route info (`{ id, pathname, data, params, handle }`) with `id` being the route, e.g.:
> 
> ```js
> const matches = useMatches();
> 
> const { id } = matches[matches.length - 1];
> 
> // id in my case is 'routes/dashboard/reports/$reportId/items/index'
> ```

A better approach is useLocation hook.

```
import {useLocation} from '@remix-run/react';
const location = useLocation();
console.log(location.pathname);
```

**Comment by deadcoder0904** [comment]
Here's copy-paste code for getting active route:

```tsx
import { Link, useLocation } from "@remix-run/react"
import clsx from "clsx"

const navigation = [
	{ name: "Dashboard", href: "/dashboard" },
	{ name: "Settings", href: "/dashboard/settings" },
]

export default function Dashboard() {
	const location = useLocation()

	return ({navigation.map((item) => (
		<Link
			key={item.name}
			to={item.href}
			className={clsx('rounded-md px-3 py-2 text-sm font-medium', {
				'bg-zinc-900 text-white': location.pathname === item.href,
				'text-zinc-300 hover:bg-zinc-700 hover:text-white':
					location.pathname !== item.href,
			})}
			aria-current={location.pathname === item.href ? 'page' : undefined}
		>
			{item.name}
		</Link>
	))
})}
```
