### ISSUE TITLE
[Bug]: Descendant <Routes> in Layout Route shows redundant warning

### ISSUE THREAD

**Issue by penx** [remix-run/react-router#8784]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Create a component with routing and use it as a Layout Route at the top of your `<Routes>`

```tsx
import { BrowserRouter, Routes, Route, Outlet, Link } from "react-router-dom";

const Layout = () => (
  <>
    <h2>Layout</h2>
    <Routes>
      <Route path="/login" element={<div>Layout diff for login</div>} />
    </Routes>
    <Outlet />
  </>
);

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route
          path="/"
          element={
            <>
              <h1>Home</h1>
              <Link to="/login">Login</Link>
            </>
          }
        />
        <Route element={<Layout />}>
          <Route
            path="/login"
            element={
              <>
                <h1>Login</h1>
                <Link to="/">Home</Link>
              </>
            }
          />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}
```

https://codesandbox.io/s/react-router-warning-5uc4gp

### Expected Behavior

I would not expect warnings in the console regarding a missing path on the parent Route, as the parent Route intentionally doesn't have a path as it is being used as a [Layout Route](https://reactrouter.com/docs/en/v6/getting-started/concepts#layout-route).

### Actual Behavior

The following warning is received:

> You rendered descendant \<Routes\> (or called `useRoutes()`) at "/" (under \<Route path=""\>) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and therefore the child routes will never render.
> 
> Please change the parent \<Route path=""\> to \<Route path="/*"\>. 
>     in Routes (created by Layout)
>     in Layout (created by App)
>     in App 

I think, in this case, the warning is not accurate and there is no issue.

**Comment by penx** [comment]
Not stale

**Comment by Roman-H91** [comment]
have the same issue in useRoutes()

**Comment by brophdawg11** [comment]
You can use the fix suggested in the warning to suppress the console message:

```
<Route path="/*" element={<Layout />}>
```

And then descendant routes of:

```
<Route path="login"
```

Example: https://codesandbox.io/p/sandbox/react-router-warning-forked-qdrncm?file=%2Fsrc%2FApp.tsx%3A9%2C15

**Comment by penx** [comment]
@brophdawg11 I don’t have access to the application that was resulting in this warning (it was nearly 2 years ago) but I certainly tried following the advice and if I remember correctly there was something preventing me from fixing it as per your suggestion. 

I can’t remember the details, sorry, but still believe this warning should not need to be shown for this use case. 

This isn’t impacting me right now, I’ll comment back if I remember more details or reencounter it, but just raising as I think it would remove a frustration for others.

**Comment by RazerM** [comment]
@brophdawg11 following the suggested fix is presumably the first thing everyone following this issue already tried. I'm open to the idea we're "using it wrong" but in our case the suggested fix changes the behaviour to something we're not intending.

https://codesandbox.io/p/sandbox/react-router-warning-forked-9nrwqw?file=%2Fsrc%2FApp.tsx%3A49%2C22

**Comment by RazerM** [comment]
> You rendered descendant <Routes> (or called useRoutes()) at "/" (under <Route path="">) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won't match anymore and therefore the child routes will never render.

I can't see how this is true for a layout route.

If we look at the example in the source beside this warning:

https://github.com/remix-run/react-router/blob/bb107c9b38849c0faa4181843f181b710c276b06/packages/react-router/lib/hooks.tsx#L375-L388

It's clear that `<Blog />` wouldn't be rendered when navigating deeper. But for a layout route, it's picking up that the parent path doesn't end in "*" (because it's empty). But empty paths are treated specially, right? That's what a layout route is. In other words, the empty path is not relevant to when the layout route is rendered.

In my codesandbox, we see that Bar's sidebar still renders fine when we're at `/bar/a`.

**Comment by brophdawg11** [comment]
> But empty paths are treated specially, right? That's what a layout route is. In other words, the empty path is not relevant to when the layout route is rendered.

The nuance is that empty paths _only_ match if their defined children match - so an approach like the one in your sandbox introduces an unobvious tight-coupling between two route trees in different areas of the code (the children of the layout versus the descendant routes rendered within the layout).  Here's an update example that I hope shows the issue this warning is trying to address: https://codesandbox.io/p/sandbox/frosty-cherry-g4wy8s

Because the pathless layout doesn't have a child route of `baz`, then the layout descendant `baz` sidebar doesn't render either - even though it's easy to think "oh the pathless layout always matches so it'll render the descendant routes in `Layout`".

Do the above alternate approaches work for your use case?
