### ISSUE TITLE
[Feature]: usePathPattern() hook

### ISSUE THREAD

**Issue by jakajancar** [remix-run/react-router#8785]
### What is the new or updated feature that you are suggesting?

`usePathPattern()` or a similar hook, or an extension to one of the existing hooks, that would return the pattern that led to the current component being rendered (e.g. `/users/:id/friends`).

### Why should this feature be included?

Analytics. `useLocation()` can reveal sensitive data and you anyways need to remove IDs to aggregate properly.

**Comment by jakajancar** [comment]
Something along the lines of:

```
function usePathPattern() {
    const routeContext = React.useContext(UNSAFE_RouteContext)
    return '/' + routeContext
        .matches
        .map(({ route: { path } }) => path)
        .filter(p => p !== undefined)
        .map(p => p.replace(/^\/|\/\*?$/, '')) // remove leading '/' and trailing '/' and '/*'
        .join('/')
}
```

**Comment by gastonmorixe** [comment]
@jakajancar if the route has children routes it doesn't work, this does:

```ts
export function usePathPattern(to: Parameters<typeof matchRoutes>[1]) {
  const routeContext = React.useContext(UNSAFE_RouteContext)
  return matchRoutes(
    routeContext.matches.map((m) => m.route),
    to
  )
}
```

**Comment by jakajancar** [comment]
It works for nested `<Route>`'s — maybe you had some other scenario in mind?

What you're suggesting looks to me like it just reruns the matching algorithm again, then returns what you had in `routeContext` in the first place?

**Comment by mmcgahan** [comment]
I'm also interested in this feature for analytics. DataDog [built some custom components](https://github.com/DataDog/rum-react-integration-examples/tree/master/src/Router) that enhanced React Router v5 to make tracked view names in DD match router `path` patterns, but the path pattern matching is a little more opaque in RR v6, so I think `usePathPattern` would be a good bridge.

Originally I was hoping that calling `useMatch()` without any arguments might provide this info inside the returned `match` object, but it currently requires that you call it with a path pattern. If it could, instead, use the nearest-parent-`Route` component's resolved path pattern when no pattern was supplied, we could have the the proposed functionality without a big change to the existing RR API.

**Current**

```ts
const match = useMatch('/foo/:bar') // compares against current location, ignores current `<Route>` parent
const match = useMatch() // error, no path pattern supplied
```

**Proposed**

```ts
const match = useMatch('/foo/:bar') // compares against current location, ignores current `<Route>` parent
const match = useMatch() // compares against current location, using currently-resolved `<Route>` path pattern
```

**Comment by allankikkas** [comment]
This is esential if site language is handled within URL (somesite.com/en-us/somepath/1234/someother/asd/ and you would like to change this en-us part without having to redirect to site root again.

**Comment by timdorr** [comment]
This is now something you can implement with `useMatches` and a Route `handle` prop: https://reactrouter.com/en/main/hooks/use-matches

**Comment by mmcgahan** [comment]
@timdorr thank you for following up on this. The new `useMatches` API is interesting, and I put together a quick proof of concept for myself to see how it could be used for the issue described.

Unfortunately, it's still a bit of a workaround rather than a fix, because the path _pattern_ used to render the current view is not directly accessible from `useMatches` - I still have to write a custom `handle` prop that specifies the path pattern, and then read that from `match.handle`.

I suggest **re-opening this issue** but keeping the workaround in the code comments - we really would like access to the path pattern already defined on our routes rather than a way to access opt-in `handle` prop values. A 'simple' solution would be to expose the `path` value from the matched routes directly in the `match` object (although obviously there's a possible naming conflict with `match.path` which means something else).

For anyone looking, this is my understanding of @timdorr's recommendation:

```tsx
const router = createBrowserRouter([
  {
    path: "/",
    element: <Root />,
    handle: { pathPattern: "/" },
    children: [{
        path: "team/:teamId",
        element: <Team />,
        handle: { pathPattern: "team/:teamId" }
    }],
  },
]);

const usePathPattern = () => {
  const matches = useMatches()
  return matches.reduce((pattern, match) => {
    if (!match.handle?.pathPattern) return pattern
    pattern += match.handle.pathPattern
    return pattern
  }, '')
}

const Team = () => {
  const pathPattern = usePathPattern()
  return <div>My matched path pattern is {pathPattern}</div>
}
```

This 'works', but it's a fair amount of additional complexity and requires the author to remember to add the `handle.pathPattern` value for every route, or build additional tooling to enforce that convention.

**Comment by mirismaili** [comment]
Please reopen this feature request. Currently, `useContext(UNSAFE_RouteContext)` is the only solution.

**Comment by nanianlisao** [comment]
> This is now something you can implement with `useMatches` and a Route `handle` prop: https://reactrouter.com/en/main/hooks/use-matches现在您可以使用 `useMatches` 和 Route `handle` 属性来实现：https://reactrouter.com/en/main/hooks/use-matches

so stupid！

**Comment by Jerome1337** [comment]
Another solution is to replace all dynamic segments by the param(s) key, for example:

```ts
const { pathname } = useLocation();
const params = useParams();

let pathPattern = pathname;

for (const [name, value] of Object.entries(params)) {
  // page key is the page name, so we don't want to replace it
  if (name !== "page") {
    pathPattern = pathPattern.replace(`/${value}`, `/:${name}`);
  }
}
```

When added in the root layout match every paths of the router.
We use this for Datadog dynamic paths grouping, this may help someone 😄

**Comment by wihlke** [comment]
I too would request reopening this issue since it is a sorely missing feature (which was there in v5). Just check out the many [stackoverflow questions](https://stackoverflow.com/questions/66265608/react-router-v6-get-path-pattern-for-current-route) about it. V6 is far superior to V5, but for this miss.

**Comment by annitya** [comment]
Please reopen this one. Generating relative url's for nested dynamic routes is a major pain.

**Comment by wihlke** [comment]
@brophdawg11 Hi Matt, not sure who else could have a look at this, but not exposing the current path pattern, is a dealbreaker for migrating from v5 to v6 for many of us. Please reopen this ticket as the solution proposed by @timdorr doesn't work and all of us accessing `UNSAFE_RouteContext` isn't sustainable.

**Comment by brophdawg11** [comment]
Since this is a new feature request, would you mind opening a [Proposal](https://github.com/remix-run/react-router/discussions/new?category=proposals) and outlining the use-cases and we can use that to gauge interest from the community via upvotes?

**Comment by manvydas-tbol** [comment]
Interested in this too...
