### ISSUE TITLE
[Bug]: Component state isn't resetting with dynamic routes

### ISSUE THREAD

**Issue by Javokhir12** [remix-run/react-router#8786]
### What version of React Router are you using?

v6.3.0

### Steps to Reproduce

```js
import { useState } from 'react';
import { Link, Routes, Route } from 'react-router-dom';

const User = () => {
  const [text, setText] = useState('this is a default text');

  return (
    <>
      <p>{text}</p>
      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
      ></textarea>
    </>
  );
};

function App() {
  return (
    <>
      <nav>
        <nav>
          <Link to="/user1">User 1</Link>
          <Link to="/user2">User 2</Link>
        </nav>
        <Routes>
          <Route path="/" element={<div>Welcome</div>} />
          <Route path="/:userId" element={<User />} />
        </Routes>
      </nav>
    </>
  );
}

export default App;
```

### Expected Behavior

When I go to `User 1` and change `text` to (for example) `abc`, then move to `User 2` I want to see again default `text` state:  `this is a default text`

### Actual Behavior

But, `text` state is persistent in `routes`. Editing `state` in one route reflects in the other one. Dynamic route is re-rendering the same component instead of resetting the state.

**Comment by timdorr** [comment]
This isn't a bug, it's just how React works. When you render the same component tree, just with different props or context, it re-uses the state from previous instances.

You should be adding `useParams` and resetting your state in a `useEffect` that subscribes to the parameter.

**Comment by bthall16** [comment]
@timdorr this is less-than-ideal though, isn't it? By resetting state in `useEffect` after the location changes, you'd immediately be firing off a state update and re-rendering which seems to essentially be [adjusting some state when a prop (or in this case, context value) changes](https://beta.reactjs.org/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes). The first render after the location updates - but before `useEffect` adjusts the component state - could have part of a component rendering based on the location while another part is rendering based on stale state.

To me, this issue is in a heavily grey area that needs more attention. The current location is coming from the URL (i.e. an external system) so `useEffect` seems appropriate. However, react-router also already knew the location changed before it rendered the route again, so relying on `useEffect` seems like a poor choice. In the case above, the component state could be synchronously known at the time the route is rendered for the new location, so it's not the same as firing off an API request (which would necessitate `useEffect`).

It may be the case that users simply need to [use a `key` to reset their component state](https://beta.reactjs.org/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key), whether that be `location.key` or, in the example above, the `userId` parameter. Alternatively, [setting state during render](https://beta.reactjs.org/reference/react/useState#storing-information-from-previous-renders) which wouldn't require remounting an entire view and its children.

Or perhaps the events proposal (#9565) could solve this by letting users make state updates in response to _any_ location change before the route renders? I've been digging for information on this type of issue recently, primarily due to the differences in how a location can change: (1) through user interaction (i.e. clicking on a `<Link />`) which would allow **proactively** updating state or (2) through the browser's back button which would require subscribing to some type of event or **reactively** updating/resetting state using strategies discussed above.

**Comment by CGamesPlay** [comment]
I've found that setting a `key` on the `Outlet` in my root route effectively solves this problem for my entire application.

```typescript
export default function RootRoute() {
  const location = useLocation();
  return (
    <>
      <Outlet key={location.key} />
      <ScrollRestoration />
    </>
  );
}
```

I use this RootRoute component as my topmost parent route and nest everything else underneath it. Clicking on a link to the current page causes a remount, and clicking on any other page causes a remount.
