### ISSUE TITLE
Allow `<Link>` to omit active params.

### ISSUE THREAD

**Issue by machty** [remix-run/react-router#89]
Presently you have to provide every single param for a target route within `Link`, but particularly when you're writing links inside deeply nested routes, this becomes needlessly repetitive as you start having to repeat the params of already-active parent routes, and to my understanding (and per convos w @rpflorence) I don't think the argument for refactorability applies in this case. 

So why don't we default omitted params to whatever's in `props.params` rather than error out?

**Comment by andreigabreanu** [comment]
I agree. Not having it explicit looks much better. React is already pretty verbose, no need to add to it unless it improves something (it doesn't in this case).

Imagine this scenario:

```
React.createElement(Route, {handler: AppComponent},
  React.createElement(Route, {name: 'base', path: '/'},
    React.createElement(Route, {name: 'locale', path: ':locale'},
      React.createElement(Route, {name: 'home', path: 'home', handler: HomepageComponent}),
      React.createElement(Route, {name: 'another', path: 'another', handler: AnotherComponent}),
```

and then in a menu or whatever i want to do something like ```<Link to="home">``` from "/en/another

I don't think I see any advantage of 
```<Link to="home" locale={this.props.params.locale}>``` over this. If i want to overwrite the locale, I'll specify it. Otherwise, use the current params already present.
