### ISSUE TITLE
[Bug]: v6.4 useLoaderData return  undefined reading 'fetchKey' in useOutlet

### ISSUE THREAD

**Issue by ergofriend** [remix-run/react-router#8936]
### What version of React Router are you using?

- 6.4.0-pre.2
- React SPA (not Remix)

### AnimatedTransition with DataBrowserRouter.

I know There are two ways for AnimatedTransition in react-router v6. from https://github.com/remix-run/react-router/discussions/8008#discussioncomment-1280897
1. `<Routes  location>`
2. `const [outlet] = useState(useOutlet());`
3. Is there any ways ?

But, DataBrowserRouter does not allow to use `<Routes />` in DataBrowserRouter children.
https://beta.reactrouter.com/en/remixing/routers/data-browser-router

So, I tried to froze useOutlet.
Then first page rendered, Click next page link, It occurred `Uncaught TypeError: Cannot read properties of undefined (reading 'fetchKey')` at next page's useLoaderData().

↓ demo repo
https://github.com/ergofriend/react-router-loader-and-relay-preload/blob/main/src/App.tsx#L9

```tsx
    <DataBrowserRouter fallbackElement={<div>DataBrowserRouter</div>}>
      <Route element={<App />}>
        <Route
          path="/"
          element={<ShipList />}
          loader={() => shipListQueryLoader(environment)}
        />
        <Route
          path="/:id"
          element={<ShipDetail />}
          loader={({ params }) => shipDetailLoader(environment, params.id!)}
        />
      </Route>
    </DataBrowserRouter>
```

```tsx
      <AnimatePresence initial={false}>
        <PageWrapper key={location.pathname}>
          <AnimatedOutlet />
        </PageWrapper>
      </AnimatePresence>
```

### Expected Behavior

- Navigated page don't have loaderData :(
- `Uncaught TypeError: Cannot read properties of undefined (reading 'fetchKey')`

### Actual Behavior

Navigated page  have loaderData :)

**Comment by ergofriend** [comment]
This issue resolved By caching useLoaderData().
https://github.com/ergofriend/react-router-loader-and-relay-preload/blob/main/src/hooks/useInAppPreloadedQuery.ts#L6

But, I think previous Page's loaderData should keep state.

**Comment by brophdawg11** [comment]
Thanks for the example repo!  This issue is heavily related to the discussion in #8008 and gets slightly more complex with the introduction of the data APIs in 6.4.  For clarity, I cloned your repo and trimmed it down to a barebones example of animating between pages with loaders:

Repo: https://github.com/brophdawg11/react-router-dom-animation-example
Stackblitz: https://stackblitz.com/edit/brophdawg11-react-router-dom-animation-example-euzcjr

I imagine we'll let this be tackled with the discussion in#8008 but will check in with Michael and Ryan.
