### ISSUE TITLE
[Bug]: overriding peer dependency warning when using React 18

### ISSUE THREAD

**Issue by pamapa** [remix-run/react-router#8944]
### What version of React Router are you using?

5.3.3

### Steps to Reproduce

When using React 18, i get install warnings:

>npm install

### Expected Behavior

no install warnings

### Actual Behavior

When using React 18, i get the following install warnings:

```
...
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0" from mini-create-react-context@0.4.1
npm WARN   node_modules/react-router/node_modules/mini-create-react-context
npm WARN     mini-create-react-context@"^0.4.0" from react-router@5.3.3
npm WARN     node_modules/react-router
...
```

**Comment by pamapa** [comment]
Would you accept a MR with the following changes on `v5` branch?

package.json:
```
"peerDependencies": {
    "react": ">=16.8"
  },
```

and replace with React.createContext once we can assume React 16+ (https://github.com/remix-run/react-router/blob/v5/packages/react-router/modules/createNamedContext.js)

**Comment by timdorr** [comment]
We cannot assume React 16.8+ because to do so would require a major and we've already done that with v6. As a result, we can't really fix this because mini-create-react-context is archived and won't release a version that fixes this. The problem isn't with our library, but that dependency that we don't control.
