### ISSUE TITLE
[Bug]: useSearchParams is breaking useNavigate behavior

### ISSUE THREAD

**Issue by luizeboli** [remix-run/react-router#8974]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

[CodeSandbox Example](https://codesandbox.io/s/lucid-lake-mbn47y?file=/src/App.js)

Hey everyone ✋🏻, I tried to create a very concise example that reproduces what I have in my codebase. 

1. Open the Sandbox example
2. Change the url pathname to `/test` through the browser preview and hit Enter key

### Expected Behavior

You should be redirected to the home page

### Actual Behavior

You will be redirected to the `/test` page. The `navigate` call in `<OtherPage />` seems to be overlapped by the `setSearchParams` in `useHook`

**Comment by timdorr** [comment]
This is just ordering of your useEffects, not the library. The one in your ContextProvider is running first because it's the highest up the tree. If you swap setSearchParams and navigate between the two useEffects, you'll get the intended result.

**Comment by luizeboli** [comment]
@timdorr can you explain why this happens? I cant just swap the calls order. I have a hook inside the context that manages the search params based on some context data.

**Comment by xsjcTony** [comment]
@luizeboli Hey, I've run into the same issue, and after inspecting the source code I got the idea of what's happening under the hood.

Look at this part of the code:
https://github.com/remix-run/react-router/blob/bfcbd58d4005318ef4d5eed4aac96d4cecbbe51e/packages/react-router-dom/index.tsx#L812-L821

`setSearchParams` has no difference from calling another `navigate()` as a result, so basically `setSearchParams()` overwrites your `navigate()` and that's why the ordering is important.

---

@timdorr I think it would be better to mention that in the documentation saying explicitly
> Usage of `setSearchParams` after `navigate` will override the previous one

But currently in the doc, it's only saying

> The setSearchParams function works like [navigate](https://reactrouter.com/en/main/hooks/use-navigate), but only for the [search portion](https://developer.mozilla.org/en-US/docs/Web/API/Location/search) of the URL.

which does not make sense after I run into such an issue for me.
