### ISSUE TITLE
[Bug]: <Navigate to={-1} /> rewinds two steps back in StrictMode

### ISSUE THREAD

**Issue by mahnunchik** [remix-run/react-router#9116]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Use `<Navigate>` component to go back.
```js
if (!someConditions) {
  console.log('navigate back');
  return <Navigate to={-1} />;
}
```

Full example: https://stackblitz.com/edit/react-tgyfzg?file=src/App.js

### Expected Behavior

App goes one step back.

### Actual Behavior

In `StrictMode` app goes 2 steps back.

Without `StrictMode` app works as expected.

**Comment by korkt-kim** [comment]
component renders twice on react strict mode to activate additional check on it.
[strict mode](https://reactjs.org/docs/strict-mode.html)

and only happens on dev mode.

**Comment by mahnunchik** [comment]
This edge case prevents normal development flow because it is not clear how to check how many pages rewinds back.

**Comment by timdorr** [comment]
This is actually a really simple fix, if someone wants to make a PR. Just change this effect to check for an `isMounted` ref and skip the effect if it's already been mounted before. 

https://github.com/remix-run/react-router/blob/351a2a378880ad2a1704c2acf6c8f4f78b99d0b8/packages/react-router/lib/components.tsx#L93-L95

If you do, just be sure to add tests too!

**Comment by ryanflorence** [comment]
Not sure what to do about this (I'm not sure an `isMounted` ref as suggested is the right thing for React Router, that adds new problems like when you actually want the `Navigate` to run multiple times before the condition is met).

Personally I don't like `<Navigate>` now that we have hooks. I recommend using `useNavigate` directly instead of `<Navigate>` and deal with the strict mode double render yourself, or make your own `<Navigate>` that solves the problem how you like.

Even better, in 6.4 (should be released soon) loaders are a much better place to handle these use cases since redirects are pretty much always determined by data than rendering logic and loaders can redirect before rendering happens, avoiding the issue completely.
