### ISSUE TITLE
False error when testing: useHref() may be used only in the context of a <Router> component

### ISSUE THREAD

**Issue by pbn04001** [remix-run/react-router#9187]
### What version of React Router are you using?

6.3.0

### Steps to Reproduce

Setup an npm mono repo.
In one package, you will want a component that uses

`import { Link } from 'react-router-dom';`

In another package within this mono repo, make a component that consumes this component from the child package.

Write a jest test using react testing library to render this component.

Even with the component wrapped in a `BrowserRouter`, we still get the following error.
`Error: useHref() may be used only in the context of a <Router> component.`

If we move the Link out of the child package, and in to the current package being tested, we do not get this same error.

### Expected Behavior

We should not receive this error
`Error: useHref() may be used only in the context of a <Router> component.`

Because our component is inside of a Router, but for some reason the router doesn't think it is inside of router.

### Actual Behavior

Even with the component wrapped in a `BrowserRouter`, we still get the following error.
`Error: useHref() may be used only in the context of a <Router> component.`

If we move the Link out of the child package, and in to the current package being tested, we do not get this same error.

**Comment by pbn04001** [comment]
If we could just have a way to override this when testing to never throw this error.  We are having to write all kinds of crap in our tests to get around this error, when our code is 100% correct and working

**Comment by timdorr** [comment]
This is because of how React Context works. You need the *exact* same instance of a `React.createContext()` to exist on both the `Provider` side and the `Context` side. If your monorepo is not set up to share modules (separate installs of `react-router-dom` per package), and therefore module instances, across multiple packages, this will occur. You need to determine how best to do that (a common package for everything from React Router or having your monorepo tool centralize shared modules), but it's not something we can fix. This isn't a bug in the library.

**Comment by pbn04001** [comment]
@timdorr Thank you for the info.  I was able to resolve this context issue by referencing the `/src` folder, and not the `/dist` folder in my mono repo packages.  In case anyone else runs into this.
