### ISSUE TITLE
[Feature]: Form and fetcher.Form should pass the form element to the loaders/action props

### ISSUE THREAD

**Issue by vidjuheffex** [remix-run/react-router#9228]
### What is the new or updated feature that you are suggesting?

[Feature]: Form and fetcher.Form should pass the form element to the loaders/action props

currently, `params` and `request` is passed but no access to event or the currentElement.

### Why should this feature be included?

I am simply trying to reset the form after a successful submission but can't get access to it, would be nice to pass along the form element to these props to do stuff with it.

(ended up using an id and query selector to access the form from the loader)

**Comment by brophdawg11** [comment]
You don't actually need to access the form in the loader to do this.  This is a UI side effect so you can handle in a `useEffect` in your component.  Check out this [Remix Single] where Ryan shows you how to do that.  The abstractions are all the same in React Router (except you'd use `fetcher.state/formData` to drive your version of `isAdding`)

Said another way - actions/loaders exist to submit/fetch _data_, but they don't deal with the UI.  That's where your react components come in.  Thus, UI changes like this belong in the components instead of the actions/loaders
