### ISSUE TITLE
[Bug]: shouldRevalidate not being called

### ISSUE THREAD

**Issue by vendramini** [remix-run/react-router#9275]
### What version of React Router are you using?

6.4

### Steps to Reproduce

Just create a root route with a loader and `shouldRevalidate` returning false.
Demo: https://stackblitz.com/edit/github-5gf1ji-5nfvis?file=src%2FApp.tsx (check the console.log).

### Expected Behavior

I'm not sure if `shouldRevalidate` means that it will execute the loader once at least or if it isn't executing the loader whatsoever if it returns false.

### Actual Behavior

The loader is being executed every time when changing routes.

Am I missing something? Did I understand the purpose of `shouldRevalidate`?

**Comment by kiliman** [comment]
React Router will only call `shouldRevalidate` *after* an action, during revalidation. Initial requests will call active loaders. 

However, I am surprised that the root loader is still being called on navigation since all those routes share the same layout. Perhaps RR is different here than Remix.

**Comment by vendramini** [comment]
If I understood the docs correctly: https://reactrouter.com/en/main/route/should-revalidate it is saying that if `shouldRevalidate` is defined then it'll be executed, just it. There's no need for an `action`.

Idk if it is the best place to do it, but I'd like to check if my user is logged in, so I've implemented a `loader` at the root route to check it. If it is **not** logged in, then `return redirect('/login')`. But the problem is: as `shouldRevalidate` is not being executed, it gives me an infinity loop of loaders execution.

**Comment by timdorr** [comment]
@vendramini You're not reading the docs correctly. They say `shouldRevalidate` is only called after an action occurs once a route is successfully loaded. A `redirect` within a loader does not count as one of these actions.

This is behaving as expected.

**Comment by vendramini** [comment]
Ok, ty for pointing it out.

But as @kiliman said, is it expected to call the root loader every time since they're sharing the same layout?

**Comment by kiliman** [comment]
Yes, I know that Remix doesn't call shared parent loaders during navigation. I'm not sure if RR has the same behavior, although the example seems to indicate it doesn't. Perhaps @chaance can shed some insight.

**Comment by brophdawg11** [comment]
Hey @vendramini!  The current issue here is that you're not returning anything from your loader.  The router internally leverages the existence of `loaderData` from a _prior_ execution to determine if the loader is being called for initial data load or as a revalidation.  Specifically it does this by checking for `loaderData[routeId] === undefined`, so by returning `undefined` you're making it as if your loader never ran at all (which sort of defeats the purpose of a data loader!).  If you need a loader that doesn't return any data, then you can return `null` and that will cause subsequent loads to be considered a "revalidation" since it can see _something_ was returned from the previous loader execution.

Also one other note in this example - you should be creating your `router` outside of your react components so it doesn't get recreated on subsequent re-renders - it should be a singleton in 6.4.0.

**Comment by vendramini** [comment]
I've updated my example following your instructions and it worked :)
Thank you for you deeply explanation about RR, it really helped me a lot.
