### ISSUE TITLE
[Bug]: You page doesn't make sense

### ISSUE THREAD

**Issue by testacode** [remix-run/react-router#9289]
### What version of React Router are you using?

latest

### Steps to Reproduce

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/1852080/190878484-a44ba057-2ecc-4e89-bd45-17cea8565329.png">

I enter the page and the first thing I see are those four options in which I don't know how to properly install and use the Router. I've used this Router since a long time and it's the first time I feel confused on how to add it to my CRA.

Now you're promoting the use of `createBrowserRouter` and that's ok. But I would also like to have all of the examples for using the provider in the legacy way (using traditional components: `<BrowserRouter />`, `<Switch />` and `<Route />`).

### Expected Behavior

As a user I would like to enter the page and have a clear path to a place where I can see and copy the basic installation commands (`npm install react-router-dom`) agnostic from any app and see the proper implementation of any of the Router's Providers.

**Comment by timdorr** [comment]
We're not going to walk through what are now legacy components, as we don't want users to use them. The future of this library is with the data loading elements, so we are only going to walk you through those. If you want to use the older components, there are API docs for all of them, as they continue to work in 6.4.

**Comment by Pomelo1213** [comment]
i can`t find installation commands, i don`t know how to start it.

**Comment by worc** [comment]
seriously though. the "tutorial" depends on an outside app template. the main reason anyone is on a library's home page is to double check the `npm install` command. half the community is using namespaces, the other half is squatting on random names, and yet another half is using paths hanging off the package name, and none of those necessarily match the org/repo names on the origin

glad to see the clout numbers were removed, but look at all this unused space:

![Screenshot from 2023-10-08 12-45-12](https://github.com/remix-run/react-router/assets/5589725/295a3f6d-6d39-43b9-8f56-08ecc6ac8c71)

we just want to know if it's `npm install @remix-run/react-router` or `npm install react-router` or what.

not to mention that there's a difference between `react-router`, `react-router-dom`, and `react-router-native`, but it's all buried somewhere below the fold

**Comment by kiliman** [comment]
For Web apps: `npm install react-router-dom`
For React Native: `npm install react-router-native`

The package `react-router` contains the core logic. As the README specifies, you should never directly import from the `react-router` package.

As for `@remix-run/router`, that is used to bridge Remix framework with React Router. You can also create "React" Router packages for other libraries like Vue, as it doesn't depend on React. Anyway, it is not something that app developers should concern themselves with.

That said, most apps are created via some generator. CRA has been deprecated, and Vite seems to be the most common. That's why the tutorial starts there.
