### ISSUE TITLE
[Bug]: setSearchParams changes its value on searchParams change

### ISSUE THREAD

**Issue by mysuf** [remix-run/react-router#9304]
### What version of React Router are you using?

6.4

### Steps to Reproduce

```
// after mounted we change keyValParam
const [searchParams, setSearchParams] = useSearchParams();

useEffect(() => {
  setSearchParams(newSearchParamsWithKeyValParam);

}, [keyValParam, setSearchParams]);

useWhyDidYouUpdate(
  "query handler dependency changes",
  { keyValParam, setSearchParams }
);
```

### Expected Behavior

It should print only once `keyValParam` value change. `setSearchParams` should keep the same as all state setters in react do

### Actual Behavior

`useWhyDidYouUpdate` from example above prints twice
First time its cos `keyValParam` value change EXPECTED
Second time its cos `setSearchParams` value change UNEXPECTED

**Comment by timdorr** [comment]
This is expected behavior. `setSearchParams` uses the value of the search params (for the callback version of the first argument), so it must change when that value itself changes.

**Comment by mysuf** [comment]
@timdorr I don't think that function itself has to change. Value of searchParams can be passed by reference (useRef).

**Comment by philer-jambit** [comment]
@timdorr Please reconsider. @mysuf has shown that the problem is easy to fix.

This should also be considered a breaking API change (it broke our app).

The current behavior (as of 6.4.3) is counter intuitive and very impractical – the hook's API is clearly based on useState, yet it does not behave like useState [which is guaranteed to have a stable setter](https://reactjs.org/docs/hooks-reference.html#usestate). This also means that any effects that depend on the searchParams setter but not the current value will still trigger when the value was updated – which is basically never what you want.

As an example, consider this use case: We want to reset pagination to page 1 when the number of items per page is changed by the user. A simplified implementation could looks like this:
```js
  const [searchParams, setSearchParams] = useSearchParams()
  
  const perPage = searchParams.get("perPage")

  useEffect(() => {
    setSearchParams({ perPage, page: "1" })
  }, [perPage, setSearchParams])
```
The effect should only run when `perPage` is updated, but since it also depends on an up-to-date reference of the setter it will instead run whenever any search parameter is updated. To work around this I have to omit the setter from the dependency list (suppressing the eslint rule `react-hooks/exhaustive-deps`) and hope that calling an outdated setter still works.

**Comment by mxvrnv** [comment]
@timdorr Any change for reconsidering this issue?

Also, the documentation of `useSearchParams` mentions React's `useState` hook and how both are similar. But the fact that the setter function of `useSearchParams` is unstable unlike in `useState` isn't mentioned.

Any reason not to proceed with the solution that @mysuf proposed?

Thanks :)

**Comment by nullberri** [comment]
@mysuf your useMemo has side effects 

```

  let searchParams = React.useMemo(
    () => {
      return getSearchParamsForLocation(
            location.search,
            defaultSearchParamsRef.current
      )}
    ,
    [location.search]
  );

  let searchParamsRef = React.useRef();
  searchParamsRef.current = searchParams 

  let navigate = useNavigate();
  let setSearchParams = React.useCallback<SetURLSearchParams>(
    (nextInit, navigateOptions) => {
      const newSearchParams = createSearchParams(
        typeof nextInit === "function" ? nextInit(searchParamsRef.current) : nextInit
      );
      navigate("?" + newSearchParams, navigateOptions);
    },
    [navigate]
  );
```

**Comment by mysuf** [comment]
@nullberri well so far I know, useRef value is not reactive so I would doubt that it has side effects however I can imagine that somebody prefer  solution you mentioned and I'm okay with it

**Comment by nullberri** [comment]
@mysuf  I do not mean in the react sense but the general sense, useMemo should be telling the developer " I am creating data", not "I am creating and modifying data". So the side effect is the assignment itself.

**Comment by mysuf** [comment]
@nullberri You are right. I tried to write that assignment on place where it really makes sense (can change its value) so maybe searchParams as state and useEffect instead of useMemo would be more appropriate to achieve that.

**Comment by nullberri** [comment]
I think your initial approach makes the most sense still. We really don't want to ever regenerate that function once its initialized. 
But we do want access to the current state for the nextInit functionality. Navigate doesn't seem to change unless the route changes and then it doesn't really matter. 

switching to useState + useEffect just means it will render twice for all searchParam updates. 

Once when it it notices Location.search changes and another when it updates the state.

Where as useMemo is 0 re-renders as it only runs when its already rendering (and location.search changed) and it triggers no further renders.

**Comment by pgsandstrom** [comment]
At my company this has caused issues more than once. The fix suggested by nullberri is safe and completely solves the problem. Could this please be fixed? The current behaviour is VERY counter intuitive.

**Comment by Moh-inc** [comment]
+1 for being counter intuitive and not similar to `useState`

**Comment by HaileyesusZ** [comment]
Yeah, the `setSerachParams` should've been referentially unchanged. But it doesn't seem to be.

I solved the re-rendering issue (caused by the dependency to useEffect) by wrapping setSearchParams with a `useCallback` so its reference wouldn't change after creation.
```
 // wrap the original setSearchParams in a useCallback
  const setRouteSearchParams = useCallback(
    (
      newSearchParams: (oldSearchParams: URLSearchParams) => URLSearchParams
    ) => {
      setSearchParams(newSearchParams);
    },
    []
  );

// use it in a useEffect, it's better to use the callback from the setter function as the new route depends on values from the previous one
useEffect(() => {
  setRouteSearchParams((oldSearchParams): URLSearchParams => {
      const newSearchParams = new URLSearchParams(oldSearchParams);

      if (isDefined(searchQuery) && !isEmpty(searchQuery)) {
        newSearchParams.set("q", searchQuery);
      } else {
        newSearchParams.delete("q");
      }
      return newSearchParams
   })


}, [searchQuery])

```

**Comment by nullberri** [comment]
You fix has several subtle bugs that while wont bite you today may bite you someday (or not maybe you get lucky!).
setSearchParams is in fact changing every render so when you close over it using useCallback with a [], if RR ever changes their code to depend on the fact the function is new you will have a stale closure and it will matter to you. Two, you should include setRouteSearchParams  in your useffect. just because today your useCallback is unable to change doesn't mean some day some one wont come and modify the callback handler and forget to add it to the useEffect and you'll get another stale closure and a failure to run your useEffect.

**Comment by mysuf** [comment]
If anyone is still struggling with this, there is no magic so you can use your own hook instead of built-in with the caveat that some of the react-router-dom future updates may break this implementation. For Typescript, most of the type definitions can be found around [here](https://github.com/remix-run/react-router/blob/27c93cbdc1342548c8623943140f794fdb797f82/packages/react-router/lib/dom/lib.tsx#L1350).

```javascript
import { useCallback, useRef, useMemo } from "react";
import { createSearchParams, useLocation, useNavigate } from "react-router-dom";

export default function useSearchParams(defaultInit) {
  if (typeof URLSearchParams === "undefined") {
    const msg =
      `You cannot use the \`useSearchParams\` hook in a browser that does not ` +
      `support the URLSearchParams API. If you need to support Internet ` +
      `Explorer 11, we recommend you load a polyfill such as ` +
      `https://github.com/ungap/url-search-params.`;
    console.warn(msg);
    try {
      throw new Error(msg);
    } catch (err) {}
  }

  const location = useLocation();
  const navigate = useNavigate();
  const defaultSearchParamsRef = useRef(createSearchParams(defaultInit));
  const hasSetSearchParamsRef = useRef(false);
  const searchParamsRef = useRef();

  const searchParams = useMemo(() => {
    // getSearchParamsForLocation
    const sp = createSearchParams(location.search);
    if (!hasSetSearchParamsRef.current) {
      defaultSearchParamsRef.current.forEach((_, key) => {
        if (!sp.has(key)) {
          const values = defaultSearchParamsRef.current.getAll(key);
          values.forEach((value) => sp.append(key, value));
        }
      });
    }
    return sp;
  }, [location.search]);

  searchParamsRef.current = searchParams;

  const setSearchParams = useCallback(
    (nextInit, navigateOptions) => {
      const newSearchParams = createSearchParams(
        typeof nextInit === "function" ? nextInit(searchParamsRef.current) : nextInit
      );
      const paramsToString = (sp) =>
        [...sp.entries()]
          .sort()
          .map(([k, v]) => `${k}=${v}`)
          .join("&");
      if (paramsToString(searchParamsRef.current) !== paramsToString(newSearchParams)) {
        hasSetSearchParamsRef.current = true;
        navigate("?" + newSearchParams, navigateOptions);
      }
    },
    [navigate]
  );

  return [searchParams, setSearchParams];
}
```

**Comment by crabvk** [comment]
https://gist.github.com/crabvk/7a432b1fdecd14f522a96fe60e231c53
Had to copy the `getSearchParamsForLocation` function, because for some reason it's not exported.

**Comment by harryi3t** [comment]
This bit me today. It took me a long time to find that the weird issue in my application where multiple API calls made multiple times was due to this.
setSearchParams in useSearchParams is not stable across renders, which is inconsistent with typical React state setters and breaks expected usage patterns. I confirmed this behavior in the latest version: it changes whenever the router context updates or when searchParams change.

This seems like a bug rather than intended behavior. Could the issue please be reopened so it can be properly addressed?

**Comment by crabvk** [comment]
The solution might be to use the router directly. I mean the one created with the `createBrowserRouter` function in [data mode](https://reactrouter.com/start/modes#data). Like this:
```typescript
import type { NavigateOptions, To } from 'react-router'

export function navigate(to: To | number, options?: NavigateOptions) {
  if (typeof to === 'number') {
    return router.navigate(to)
  }
  return router.navigate(to, options)
}

navigate('?q=term&hello=world')
```
