### ISSUE TITLE
[Bug]: Scroll Restoration does not maintain scroll position on a page refresh for a lazy loaded route

### ISSUE THREAD

**Issue by fetters5** [remix-run/react-router#9472]
### What version of React Router are you using?

6.4.2

### Steps to Reproduce

Please see my example on stackblitz.  The about route is lazy loaded, the dashboard is not. If you refresh on the about route it will always go to the top (back and forward seems to work as intended)

https://stackblitz.com/edit/github-4s5el2-e5ujjy?file=src%2FApp.tsx

### Expected Behavior

refreshing a lazy route would restore position the same as refreshing an eager route

### Actual Behavior

lazy routes do not maintain scroll position on refresh

**Comment by timdorr** [comment]
Scroll restoration only occurs during a layout effect, so immediately upon a location change:

https://github.com/remix-run/react-router/blob/5f3cfb7ac2ad823ecdf69069332567e35ad795c6/packages/react-router-dom/index.tsx#L1081-L1110

Because a lazy loaded component will not render until after this effect has run, there's no way for ScrollRestoration to know that there is an updated layout that needs to restore its position. It would have to assume that every update requires a scroll position restoration, which would result in the page continually jumping back to that scroll position.

The only way to work around this is to render ScrollRestoration _within_ your lazy-loaded component. This will ensure the scroll position is restored once the component is in place and rendered. You will just need to be careful about not rendering multiple ScrollRestorations on the page.
