### ISSUE TITLE
[Bug]: isRouteErrorResponse doesn't work with hydrated error

### ISSUE THREAD

**Issue by eldar-gamisoniya** [remix-run/react-router#9537]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

- Open https://stackblitz.com/edit/github-1s7uwc?file=src/App.tsx

### Expected Behavior

- The route is executed on server side and 404 page is rendered
- error gets hydrated on the client side
- `isRouteErrorResponse` recognizes it as a router error
- hydration works

### Actual Behavior

- The route is executed on server side and 404 page is rendered
- error gets hydrated on the client side
- since it's now a json object `isRouteErrorResponse` returns false
- hydration fails

**Comment by brophdawg11** [comment]
The SSR 6.4 APIs are marked `unstable_` since they're not complete yet.  I'm going to close this for now as we should have this handled by the time we push it stable 👍 .  If you want this behavior now you can handle hydration manually via `<StaticRouterProvider hydrate={false}>` and passing `hydrationData` to `createBrowserRouter` - and handling the serialization/deserialization of `ErrorResopnse` objects

**Comment by brophdawg11** [comment]
This should be fixed in `6.4.4-pre.0` now if you want to give it a test!
