### ISSUE TITLE
[Bug]: Cannot redirect from parent with outlet to child route via loader function

### ISSUE THREAD

**Issue by unbiased-dev** [remix-run/react-router#9559]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

https://codesandbox.io/s/zealous-platform-q12fc8

Here is a minimal repro

Uncomment the redirect line inside App.js loader to make the app crash (or rather infinite load and freeze).

### Expected Behavior

I expect when a user goes to `"/"` to be redirected to `"/home"` where i can see the `<h1>I want this on all routes</h1>` and the `<Home />` to be nested underneath it. This is because I don't want my users to go to a fallback page before going to `"/home"` but rather home to be the default page.

Further the `<h1>I want this on all routes</h1>` would actually be a navbar with a navlink of `Home` and the user would be able to go to other `/child` routes where the navbar would remain the same and the `Child` would render inside the `Outlet`.

But that really doesn't matter for this bug report right now.

And my app is not hosted under a subpath so setting a `basepath` doesn't actually work for me.

### Actual Behavior

No redirect happens and the app freezes.

**Comment by Stekac** [comment]
One way to achieve this is with an intermediate index route, but that does indeed feel a bit hacky.

To me it makes sense if the route is index, the url path should also be the one on the child, not the parent, and if you want to stick to the parent route, just leave out the path param in the child.

```export const router = createBrowserRouter([
  {
    path: "/",
    element: <Root />,
    children: [
      {
        index: true,
        loader() {
          return redirect("/home");
        }
      },
      {
        path: "/home",
        element: <Home />
      },
      {
        path: "/other",
        element: <div>other</div>
      },
    ]
  }
]);

**Comment by brophdawg11** [comment]
I would recommend exactly what you've proposed in https://github.com/remix-run/react-router/issues/9559#issuecomment-1304357896. 

When using nested routing, all matched route loaders will run, so if you have side effects you only want to run for _some_ children, it can get messy pretty quickly.  Using a standalone `index` child loader makes it very explicit when to redirect.

As it stands now the infinite loop is correct since you are redirecting on every invocation regardless of if you are at `/` or `/home`, and you would need to conditionally redirect to prevent it:

```js
export const loader = ({ request }) => {
  if (new URL(request.url).pathname === "/") {
    return redirect("/home");
  }
  return null;
};
```
