### ISSUE TITLE
[Bug]: Loader called when RouterProvider has not been rendered

### ISSUE THREAD

**Issue by luke-john** [remix-run/react-router#9567]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

1. Create a react element which contains a router but do not render it

---

The following code is a minimal reproduction of this issue.

```tsx
import React from 'react';
import { RouterProvider, createBrowserRouter } from "react-router-dom";

function rootLoader() {
  console.log("should not run")
}

const router = createBrowserRouter([{ path: "/", loader: rootLoader, element: <div>router loaded</div>, }])

export default function Example() {
  const [loaded, setLoaded] = React.useState(false)

  return (<div>
    mode where router not loaded
    {/* note re below -- the element is created even when it is not rendered */}
    {loaded ? <RouterProvider router={router} /> : null}
  </div>)
}
```

### Expected Behavior

When there are loaders on a router, and that router has not been rendered via a RouterProvider (even if a RouterProvider element has been created).

I do not expect the loaders to be called.

### Actual Behavior

When there are loaders on a router, and that router has not been rendered via a RouterProvider (but a RouterProvider element has been created).

The loaders are called.

**Comment by timdorr** [comment]
`createBrowserRouter` is being run outside of the React render context. It's hooking into the History API and preparing its rendered elements immediately. This is expected behavior.

One way around this would be to run it inside of a `useEffect` and store the `router` in a `ref`. This requires more careful management of the `router` instance, but is totally doable.
