### ISSUE TITLE
[Bug]: Cannot include a '?' character in a manually specified....

### ISSUE THREAD

**Issue by VQH-cmd** [remix-run/react-router#9613]
### What version of React Router are you using?

6.4.x

### Steps to Reproduce

Cannot include a '?' character in a manually specified.... on Link  / NavLink Container

It has been more than 1 month since 6.4 released, and the annoying issue still exists !
Even in 6.4.3 version recently !

> 6.4.x is very unstable.

[Issue](https://stackoverflow.com/questions/74176810/getting-uncaught-error-cannot-include-a-character-in-a-manually-specified)

### Expected Behavior

`<Link to="/somepath/?query=abcd">Target</Link>`
`<Route path="/somepath?query=:q" element={<Comp />} />`

 When ever `?` appears in `to` or `path` => issue happen.

### Actual Behavior

Link and NavLink if has `?` character.

**Comment by timdorr** [comment]
You can't match a Route on the query string in the path. If this was possible in 6.3 or earlier, that was a bug. The query string is intentionally not supposed to match on a Route, as it is intended for extra data you want sent to that Route.

**Comment by VQH-cmd** [comment]
> You can't match a Route on the query string in the path. If this was possible in 6.3 or earlier, that was a bug. The query string is intentionally not supposed to match on a Route, as it is intended for extra data you want sent to that Route.

Ok, It's a limitation on 6.4
And what's the solution for this case, docs, links or something ? Due to some of my projects have issue blank page because of this.

- or you simply write some excuses and wait for it to cool without any advice or solution like many ?

**Comment by pganster** [comment]
I've gotten this error when using `navigate()` to navigate to an URL that includes query parameters. I'm receiving the URL from a third party service (the `onRedirectCallback` callback from [auth0-react](https://github.com/auth0/auth0-react) to be concrete). 

Supplying a URL with a query parameter worked with 6.3, but after upgrading to 6.4.3 I'm receiving the same error as described in this issue.

To get the same behavior as before, instead of simply calling `navigate({pathname: returnTo})`, I'm currently supplying the URL from the third party service this way:
```javascript
const returnToUrl = new URL(returnTo, window.location.origin);
navigate({
     pathname: returnToUrl.pathname,
     search: returnToUrl.searchParams.toString()
});
```
