### ISSUE TITLE
[Bug]: Error using unstable_HistoryRouter with 6.4.3

### ISSUE THREAD

**Issue by rlebascle** [remix-run/react-router#9630]
### What version of React Router are you using?

6.4.3

### Steps to Reproduce

"history": "^5.3.0",
"react-router-dom": "6.4.3"

```
import { unstable_HistoryRouter as HistoryRouter, Routes, Route } from "react-router-dom";
import { createBrowserHistory } from "history";

const history = createBrowserHistory({ window });

<HistoryRouter history={history} basename={basename}>
```

### Expected Behavior

No typing error.

### Actual Behavior

> TS2741: Property 'encodeLocation' is missing in type 'BrowserHistory' but required in type 'History'.
> 
> "encodedLocation" is required in @remix-run/router history but not available in history module.

This is broken since react-router-dom 6.4.3, 6.4.2 is working.

And a quick word to thank you for the amazing work on the data router !

**Comment by rlebascle** [comment]
I found out the change introducing the bug.
https://github.com/remix-run/react-router/pull/9496

**Comment by vishal-kadmos** [comment]
Also observing same issue while upgrading from `6.4.2` to `6.4.3`

**Comment by vraravam** [comment]
Same issue with us on Ferdium while upgrading from `6.4.2` to `6.4.3` - downgrading till this gets fixed. Thanks for the awesome package btw!

**Comment by pleunv** [comment]
[This comment](https://github.com/remix-run/react-router/issues/9422#issuecomment-1301182219) might help.

**Comment by netcoding87** [comment]
I am facing the same issue, but not with `createBrowserHistory`, instead I am using `createMemoryHistory`. The linked post did not help unfortunately :/

**Comment by brophdawg11** [comment]
There's no functional issue here - this is just a TS error from using an old `history@5` implementation with an unstable API in 6.4 which uses a different internal `history`.  These APIs are marked `unstable_` because they may encounter breakages like this 😄 

The easiest solution is to just add `// ts-expect-error` since these are incompatible packages:

```tsx
ReactClient.createRoot(document.getElementById("root")).render(
  // @ts-expect-error
  <unstable_HistoryRouter history={history}>...</unstable_HistoryRouter>
);
```

Otherwise you can leverage the new `history` implementation for 6.4+, but note it has some differences from v5 (no blocking,  no `back`/`forward` - just `go`)

```jsx
import { createBrowserHistory } from "@remix-run/router";

const history = createBrowserHistory({ v5Compat: true });
```

But the **recommended** solution is to upgrade to `RouterProvider` as mentioned in https://github.com/remix-run/react-router/issues/9422#issuecomment-1301182219 and https://github.com/remix-run/react-router/issues/9422#issuecomment-1302564759.
