### ISSUE TITLE
[Feature]: handle type inference in useMatches

### ISSUE THREAD

**Issue by guaijie** [remix-run/react-router#9633]
### What is the new or updated feature that you are suggesting?

```
type RouteHandle = {
  title?: string
}

const title= matchRoutes(myRoutes, location)
  .map(match => {
    return match.route.handle?.title; // Inference of success
  })

const matches = useMatches(
const title= matchRoutes()
  .map(match => {
    return match.route.handle?.title; // Not inferring normally
  })

// type definition
export declare function useMatches(): {
    id: string;
    pathname: string;
    params: Params<string>;
    data: unknown;
    handle: unknown;  //  why unknown ?
}[];
``` 

### Why should this feature be included?

The same type inference as `matchRouter` can be implemented

**Comment by tlindsay42** [comment]
Almost the same request, but I'd like a hook for retrieving the typed route handle for the current location so that I don't have to scan useMatches output, type guard/cast result.

**Comment by timdorr** [comment]
Because at compile time Typescript cannot know the context within which you are rendering the component containing a `useMatches()` hook. 

`matchRoutes` works because it's a function with a known input and return type. TS can see its entire execution. `useMatches` pulls from external data that may be of any type. Hence, we mark it as `unknown` as the safest way to deal with it until you put appropriate type guards in place.

**Comment by nikolailehbrink** [comment]
> Because at compile time Typescript cannot know the context within which you are rendering the component containing a `useMatches()` hook.
> 
> `matchRoutes` works because it's a function with a known input and return type. TS can see its entire execution. `useMatches` pulls from external data that may be of any type. Hence, we mark it as `unknown` as the safest way to deal with it until you put appropriate type guards in place.

Hi @timdorr, that makes sense! Could you share some info on how you would put some type guards in place and type the `useMatches` results correct?
