### ISSUE TITLE
[Bug]: Even when providing the new setSearchParams updater, it still unsafely references stale params

### ISSUE THREAD

**Issue by joshribakoff-sm** [remix-run/react-router#9757]
### What version of React Router are you using?

6.5

### Steps to Reproduce

Update the search params synchronously 2x (eg. in 1 event handler, such as an `onClick`, try to call it twice):

```ts
setSearchParams(params => {
  params.set('a', 'true')
  return params
})
setSearchParams(params => {
  console.log(params.toString()) // "a" is NOT present, this is undesired
  console.log(window.location.search) // "a" is present
  params.set('b', 'true')
  console.log(params.toString()) // only "b" is present, now :(
  return params // we lose the previously set value for "a" here!
})
```

### Expected Behavior

1) Read directly from `window.location.search` instead of a memoized value. See https://github.com/remix-run/react-router/blob/b67538b1172c3dcf07a2e431bbe7c2eb32b06eaf/packages/react-router-dom/index.tsx#L803-L810 since this memoized value will correspond to a stale value if `location.search` has changed since it was last computed.

2) Don't snapshot the value of `window.location.search` during the render phase, instead read it synchronously just prior to invoking the "updater" I have supplied.

### Actual Behavior

you unsafely reference previous search params by memoizing `locations.search` here https://github.com/remix-run/react-router/blob/b67538b1172c3dcf07a2e431bbe7c2eb32b06eaf/packages/react-router-dom/index.tsx#L803-L810 during the render phase, which assumes I will always wait for the hook to re-render prior to me calling `setSearchParams` a subsequent time. This assumption seems at odds with the presumed intention of the updater function (to avoid footguns with stale params)

**Comment by joshribakoff-sm** [comment]
Here is the workaround for any consumers who suffer from this bug:

```
setSearchParams((_params) => {
        const params = new URLSearchParams(window.location.search);
       // update params, which is safe, instead of trying to update _params argument
       return params
})
```

I can now observe that my code works as intended, multiple invocations of `setSearchParams` don't clobber each other any longer.

**Comment by timdorr** [comment]
This is actually considered "safe" from the React perspective. Within the updater's closure, you can reference values during the current render cycle. These values need to be stable, primarily for async rendering to work successfully. 

The bigger thing here is that `setSearchParams` is just calling `navigate` under the hood. So, you're going to put two navigations on the history stack if you call the function twice, essentially overwriting the params with the second call. You should combine this update into one single call to avoid the problem. It would most likely be ideal not to use the callback form and just use the params value from `useSearchParams` directly and send it back to `setSearchParams`.

**Comment by joshribakoff-sm** [comment]
> This is actually considered "safe" from the React perspective. Within the updater's closure, you can reference values during the current render cycle. These values need to be stable, primarily for async rendering to work successfully.

I'm not sure I follow, I am calling it during an event handler. When the event handler runs the URL is updated, but there has been no render. I would respectfully disagree, and wonder if you're referring to the fact that React guarantees re-renders between multiple invocations of event handlers? That seems unrelated, since my issue is with updating the URL multiple times in one invocation of an event handler.

> The bigger thing here is that setSearchParams is just calling navigate under the hood

At this point in time the browser URL is updated, and React has not re-rendered, and your memoized value is stale

> So, you're going to put two navigations on the history stack if you call the function twice

Not if the user passes `replace`.


>  You should combine this update into one single call to avoid the problem.

What's the point of providing an updater function? There are reasons my app needs to update the URL in separate steps,  synchronously, which I'd be happy to elaborate on. Basically two different components responding the same GQL query and they update different params.

"re-architect your app" isn't a very satisfying suggestion :/

**Comment by love-nltg** [comment]
I was very happy to find this discussion! To me, the current behavior of this hook goes against how I expect **any** React hook to work. In the reactrouter.com docs, it says

> Just as React's [useState hook](https://reactjs.org/docs/hooks-reference.html#usestate), setSearchParams also supports [functional updates](https://reactjs.org/docs/hooks-reference.html#functional-updates).

By saying the hook works like `useState`, it's **clearly** inferred that subsequent calls  in the same frame should not lose track of the previous state.

With how things stand I would argue their's either a bug in the code, or the documentation.

**Comment by joshribakoff-sm** [comment]
Yes, if the maintainers do not want to offer an updater that offers the same guarantees as the React one, that's "fine" but the docs should not imply it does offer the guarantees!

I think maybe @timdorr you're referring to:

> You might hear a recommendation to always write code like setAge(a => a + 1) if the state you’re setting is calculated from the previous state. There is no harm in it, but it is also not always necessary.

> In most cases, there is no difference between these two approaches

https://beta.reactjs.org/apis/react/useState#is-using-an-updater-always-preferred

My point is, it does not say the updater is *never* necessary:

>  if you do multiple updates within the same event, updaters can be helpful.

Maybe the react router docs should instead say:

The updater function does *not* work like the React state updater. You need to make sure to only update the URL 1x per event handler.

**Comment by Moh-inc** [comment]
+1

**Comment by Pinpickle** [comment]
@timdorr Could this be re-opened? @joshribakoff-sm and @love-nltg have made very good points as to why the documentation should at least be updated to make this explicit.

Other issues are being closed with this one as a reference (#10316, #10580), so it would make sense to keep this canonical issue open.

For what it's worth, I ran into this issue when applying two orthogonal updates simultaneously in `useEffect` calls (one for search params, another for path). Combining them would have required tightly coupling very different concerns.

**Comment by tedchirvasiu** [comment]
I think the issue stems from the fact that setSearchParams is dependent on searchParams:
https://github.com/remix-run/react-router/blob/13ac1b6c5cc2c3f99629bed6ed0ccc8542de0d94/packages/react-router-dom/index.tsx#L1464-L1473

And searchParams is dependent on location.search
https://github.com/remix-run/react-router/blob/13ac1b6c5cc2c3f99629bed6ed0ccc8542de0d94/packages/react-router-dom/index.tsx#L1450-L1461

And if we dig deeper location is in turn obtained via React.useContext. Thus you have to wait a render cycle to get the new searchParams.

This means that setSearchParams memoizes its value for the previousSearchParams (prev). This indeed deviates from React's guarantees for setState in 2 ways:
1. The value of prev can be stale
2. setSearchParams changes reference on each render

This leads to various footguns and bugs if we assume it works like setState, for instance:
- You have to include setSearchParams in the dependency array of useCallback or useMemo hooks, otherwise you'll receive a very old prev value
- You cannot call setSearchParams multiple times in the same render cycle unless you avoid the prev value and use window.location.search as suggested by [joshribakoff-sm](https://github.com/joshribakoff-sm)
- You have to be careful if you call setSearchParams from something like setInterval or setTimeout (for instance from debounced functions). You will have an old reference to setSearchParams and it will once again override any changes made in the meantime by other calls to setSearchParams. (the workaround here is the same as for point b which is to use window.location.search)

Using window.location.search is indeed a nice workaround for BrowserRouter but I'm not sure if it works well for other routers. And it feels a bit unclean. I agree with the rest that the documentation should mention this behavior if it is intended to work this way.
Otherwise, **I think the best approach would be to have a way to obtain the most up-to-date location immediately (in useRef style rather that useState style) and remove setSearchParams's dependency on searchParams** so that all the pitfalls mentioned above would be eliminated. If the maintainers think this could be a good idea, I could try to suggest a fix via a PR.

**Comment by AdrianDiazCode** [comment]
why was this closed? this is still happening

**Comment by 72ridwan** [comment]
This is the current workaround that I do: https://stackblitz.com/edit/vitejs-vite-eppyehuc?file=app%2Fscoped-params%2FScopedParams.tsx

It wraps around React Router's `setSearchParams` so that only a single instance of search params is used and the previous result from `setSearchParams` is used for next `setSearchParams` call. The custom setter needs to be inside provider that can be done at the app root.

This also handles two separete components that need to change the search params. In the above example, the filter and the parent has different query params that they're synced with. The parent needs to reset the page when the filter is changed.

**Comment by dobesv** [comment]
Here's a hook I created as a workaround for this:

```ts
import {
  createSearchParams,
  NavigateOptions,
  SetURLSearchParams,
  useSearchParams as useSearchParamsImpl,
} from 'react-router-dom';

let pendingSetSearchParams:
  | {
      searchParams: URLSearchParams;
      opts: NavigateOptions;
    }
  | undefined = undefined;

/**
 * Wrapper around useSearchParams from react-router-dom where if you call
 * setSearchParams and provide a function, subsequent calls to setSearchParams
 * with a function will get the return value of the previous call instead of
 * the value of searchParams from the last render.
 *
 * If you are using setSearchParams with a function, you should use this function
 * to avoid unexpected loss of updates.
 *
 * Workaround for https://github.com/remix-run/react-router/issues/9757
 */
export default function useSearchParams(): [
  URLSearchParams,
  SetURLSearchParams,
] {
  const [searchParams, setSearchParamsImpl] = useSearchParamsImpl();
  const setSearchParams: SetURLSearchParams = (v, opts = {}) => {
    // In case we have had a setSearchParams call in the same frame with different options, flush
    // that out to the URL now so that it can push the options to the history stack if desired
    const pending = pendingSetSearchParams;
    if (pending && JSON.stringify(pending.opts) !== JSON.stringify(opts)) {
      setSearchParamsImpl(pending.searchParams, pending.opts);
    }

    // Calculate the new search params value
    pendingSetSearchParams = {
      searchParams: createSearchParams(
        typeof v === 'function'
          ? v(new URLSearchParams(pending?.searchParams ?? searchParams))
          : v,
      ),
      opts,
    };

    // Queue application of the new search params value in the next frame
    requestAnimationFrame(() => {
      if (pendingSetSearchParams) {
        setSearchParamsImpl(
          pendingSetSearchParams.searchParams,
          pendingSetSearchParams.opts,
        );
        pendingSetSearchParams = undefined;
      }
    });
  };
  return [searchParams, setSearchParams];
}

```

**Comment by GendelfLugansk** [comment]
> This is the current workaround that I do: https://stackblitz.com/edit/vitejs-vite-eppyehuc?file=app%2Fscoped-params%2FScopedParams.tsx
> 
> It wraps around React Router's `setSearchParams` so that only a single instance of search params is used, and the previous result from `setSearchParams` is used for next `setSearchParams` call. The custom setter needs to be inside provide, which can be done at the app root.
> 
> This also handles two separate components that need to change the search params. In the above example, the filter and the parent have different query params that they're synced with. The parent needs to reset the page when the filter is changed.

Nice workaround but It seems `useEffect` may lead to bug if `setParams` is called right after navigation (navigation clears search parameters but `setParams` still rely on pre-navigation ones). Replacing lines 18-22 with

```
  const statesRef = useRef({ params, originalSetParams });
  statesRef.current = { params, originalSetParams };
```

seems to help

**Comment by StevenHallLtd** [comment]
Wow – I must say I'm really surprised by this shortcoming. Can't you just fix this with a global variable with a funny name like `DONT_TOUCH_THIS_OR_YOU_WILL_BE_FIRED`? 😅
