### ISSUE TITLE
[Bug]: Path matching no longer works if the pattern contains `@`

### ISSUE THREAD

**Issue by srmagura** [remix-run/react-router#9779]
### What version of React Router are you using?

6.6.0

### Steps to Reproduce

Minimal repro: https://github.com/srmagura/react-router-at-sign-repro

```ts
import { matchPath } from "react-router-dom";

const pattern = "/@:slug";
const pathname = "/@sam";
const match = matchPath(pattern, pathname);

console.log(match);
```

### Expected Behavior

A match object is printed:

```js
{
  params: { slug: 'sam' },
  pathname: '/@sam',
  pathnameBase: '/@sam',
  pattern: { path: '/@:slug', caseSensitive: false, end: true }
}
```

This was the behavior as of react-router-dom 6.3.0.

### Actual Behavior

`null` is printed.

### Related

#9778

**Comment by pting-me** [comment]
Just confirmed via testing that the code seems to be working fine up until [this particular commit](https://github.com/remix-run/react-router/commit/c6c8c3bfe4bce8ce53e61cee5542d88363593a93).

Not entirely sure, but I believe it's because the code here makes an assumption that params are always preceded with `/:`.

Also want to note that none of the tests in `matchPath-test.tsx` include any colons or variable paths. Not sure if that's intentional, but maybe it's something we'd want to include?

**Comment by ckarras11** [comment]
I am also now running into the same issue.
```typescript
if (matchPath({ path: '/@:username/:slug/*' }, pathname)) {
  // used to match in 6.4.5
} else if (matchPath({ path: '/:other/:thing/*' }, pathname)) {
  // now matches this breaking the site in 6.6.0
}
````
Just want to make sure this was intentional before rewriting all of our routes and utils.

**Comment by brophdawg11** [comment]
This is expected behavior due to a [fix in 6.5.0](https://github.com/remix-run/react-router/releases/tag/react-router%406.5.0).  Params were always intended to be full URL segments (just like how you can't match on `/prefix*`) but we fixed a bug that was inadvertently matching params when a prefix was present (such as `/prefix:param`).  There's a recommended workaround in the [6.5.0 release notes](https://github.com/remix-run/react-router/releases/tag/react-router%406.5.0).

**Comment by srmagura** [comment]
@brophdawg11  This is a huge breaking change, released with only a minor version bump. 

The core path structure of our application is `/@:orgSlug/@:worldSlug/@:spotSlug`, so we have a very large number of routes and `matchPath` calls that relied being able to match parameters after the `@` prefix. It will take a large scale refactor for us to upgrade to 6.5.0 using the workaround suggested in the release notes.

Please consider:

- Reverting the breaking change to restore the old behavior, or
- Marking 6.5.0+ as obsolete and re-releasing the latest code as a version 7.0.0

**Comment by machour** [comment]
@brophdawg11 in what version was the bug introduced?

**Comment by xavier-lc** [comment]
> There's a recommended workaround in the [6.5.0 release notes](https://github.com/remix-run/react-router/releases/tag/react-router%406.5.0).

Sorry, but I don't see the workaround on the release notes, could you please explain how to keep using `@` at the beginning of a URL segment, if it's still possible? Thanks!

**Comment by srmagura** [comment]
@xavier-lc This is the workaround he is referring to. (Though it is not a very effective workaround IMO.)

![image](https://user-images.githubusercontent.com/801549/209355633-bbf641de-5e2a-46dc-8d24-d2db6e1f7096.png)

**Comment by brophdawg11** [comment]
@srmagura I'm sorry this change impacted your app - but this was never documented as valid/expected behavior which is why it wasn't considered breaking.  Every example of dynamic parameters in the documentation shows them as full URL segments, which is how the original code was always supposed to behave.  Unfortunately, at scale it's inevitable that some apps will some to rely on buggy behavior so we do our best to document fixes like this in the release notes and provide suggested workarounds to handle these scenarios.

Would it be possible for you to leverage a helper in the short term that could allow you to match the old style and convert your app use cases over time?  You'd have to update your app `<Route path>` definitions to remove the `@` from the `path`, but I think for any cases where you're calling `matchPath` with a static string you could do something like the following and get the same `params` values:

```js
function matchPathParamsWithStrippedPrefix(pattern, pathname) {
  // Convert `/@:param` to `/:param`
  let convertedPattern = pattern.replace(/\/@:/g, "/:");
  // Match against non-prefixed params
  let match = matchPath(convertedPattern, pathname);
  if (!match) return null;
  // Strip the leading `@` back off the matched params
  let convertedParams = {};
  for (let [name, value] of Object.entries(match.params)) {
    convertedParams[name] = value.replace(/^@/, "");
  }
  return convertedParams;
}
```

You could do something similar with `useParams` as well if you have a lot of those ins your app.

**Comment by srmagura** [comment]
@brophdawg11 Thank you for your detailed response 🙂. 

Your patched version of `matchPath` looks good. It would not be hard for us to adopt it.

For `<Route>`s, we will need to attempt to change the route patterns from

```
/@:orgSlug/@:worldSlug/@:spotSlug
```

to

```
/:orgSlug/:worldSlug/:spotSlug
```

and then subtract the `@` from each parameter. Though, this could lead to problems because now paths like `/@myOrg/settings/overview` will result in a match when they did not before.

The easiest option for us may be to copy parts of the React Router source into our codebase so that we can add back support for prefixes.

**Comment by brophdawg11** [comment]
I thin you'd be able to update the example `matchPathParamsWithStrippedPrefix` method above to detect matched params without a leading `@` and return `null`?

**Comment by srmagura** [comment]
Yes, but we would need to figure out how to make the `<Route>` component use that logic. This might mean creating a modified version of the `<Route>` component, or something like that.

**Comment by brophdawg11** [comment]
I'm not sure I follow - the Route component doesn't provide params to the app layer, it just helps define routes up front.  If you're referring to accessing param values via `useParams` then maybe you could create a small wrapper hook around that as well?

For the `/@myOrg/settings/overview` path - if thats a real path wouldn't it have it's own defined `<Route path="/:orgSlug/settings/overview">`?  if so that will match before the param version due to how the route scoring works.  You could also use loaders to return a 404 if the matched parameter didn't start with `@`, or redirect from your component if you're not using data APIs.

**Comment by xavier-lc** [comment]
@srmagura thanks! Yeah, not the best workaround, but I think it'll work for us 🤷‍♂️
