### ISSUE TITLE
[Feature]: Typed routes

### ISSUE THREAD

**Issue by g4rcez** [remix-run/react-router#9791]
### What is the new or updated feature that you are suggesting?

Offer a possibility to use Link or navigate functions using typed strings, like [Tanstack Routers](https://tanstack.com/router/v1). This will improve a lot the DX of the react-router. This can be introduced as a helper function that takes all routes and return a typed string with all `RouteObjects["path"]`

### Why should this feature be included?

1. A big improvement for DX
2. Avoid mistakes on type routes
3. Avoid string maps with all routes
4. Best refactors

I'm able to implement this feature. I already did this feature in a personal project and helps me a lot.

**Comment by timdorr** [comment]
This would require a fundamentally different API to be truly typesafe. Tanner's library is able to get away with this since he's designed it this way from scratch. We started with plain JS and added TS later. We also have different goals than just type safety. 

Many previous proposals have been wrappers around the `as` keyword, which overrides type safety. There is no way to implement true end-to-end type safety without breaking every React Router app out there.
