### ISSUE TITLE
[Bug]: Is there a property called message in error object?

### ISSUE THREAD

**Issue by MenaiAla** [remix-run/react-router#9817]
### What version of React Router are you using?

18.2.0

### Steps to Reproduce

1.  Run this command:` touch src/error-page.jsx.`
2. Copy this code: 
```javascript
import { useRouteError } from "react-router-dom";

export default function ErrorPage() {
  const error = useRouteError();
  console.error(error);

  return (
    <div id="error-page">
      <h1>Oops!</h1>
      <p>Sorry, an unexpected error has occurred.</p>
      <p>
        <i>{error.statusText || error.message}</i>
      </p>
    </div>
  );
}
````
3. Remove `error.statusText`:
```javascript
  return (
    <div id="error-page">
      <h1>Oops!</h1>
      <p>Sorry, an unexpected error has occurred.</p>
      <p>
        <i>{ error.message}</i> // error.status is removed
      </p>
    </div>
  );
```

### Expected Behavior

See the `error.message` text:

`No route matches URL "/contacts/1`

### Actual Behavior

Empty text.

<hr>

After debbuging `console.log(error)`, I found only these properties:

```
1. status

2. statusText

3. internal

4. data

5. error { 
               1. message
               2. stack
        }

```

It should be like this: `<i>{ error.error.message}</i>`

To get its value : `No route matches URL "/contacts/1`

Documentation link: [handling not found errors](https://reactrouter.com/en/main/start/tutorial#handling-not-found-errors)

**Comment by brophdawg11** [comment]
In this case, you want to look at `error.data` since the error is an `ErrorResponse` for the 404.  `useRouteError` can take many forms since anything can be thrown from a loader or an action, so you can use [`isRouteErrorResponse`](https://reactrouter.com/en/main/utils/is-route-error-response) and `instanceof Error` checks to narrow down to know what fields will be available.

**Comment by david-mcafee** [comment]
Since the error object is `unknown`, I think it would make more sense in the documentation to _not_ include code examples that attempt to render `error.message` when using `useRouterError`. 

For example, if I simply attempt to navigate to a route that does not exist (a common routing-related user error), `error.message` will fail (`error.error.message` succeeds). By instead simply displaying a friendly error message in the examples, the docs happy path would be less troublesome.
