### ISSUE TITLE
[Bug]: Navigating back from nested routes does not trigger their wrappers/parent routes

### ISSUE THREAD

**Issue by emrerdem1** [remix-run/react-router#9827]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

1. Use BrowserRouter as your router.
2. Use two nested routes inside a base route.
3. Use wrapper routes as the index in the route definitions to keep track of re-render.
4. Navigate down the last route, and try to navigate back by using browser navigations. See none of the wrapper routes get triggered except the base route.

Reproduction link: https://codesandbox.io/s/crazy-austin-oeb6h9?file=/src/RouterScreen.tsx

### Expected Behavior

Wrapper/parent routes should get triggered while navigating back from nested routes.

### Actual Behavior

Wrapper/parent routes do not get triggered.

**Comment by timdorr** [comment]
This is expected behavior from how React itself works. When the location changes (through the link or through the back button), you're rendering a component tree with the same components inside of it. React is re-using those components, just the same as it would with any other component. 

You can get around this by subscribing to location changes with `useLocation` in any component that might depend on the location changing.
