### ISSUE TITLE
[Feature]: Extract remix features to extra plugin for react router

### ISSUE THREAD

**Issue by Sin9k** [remix-run/react-router#9869]
### What is the new or updated feature that you are suggesting?

I am a big fun of the react router, but I'm not really think that I want to use remix features (like loader or Form) in my app. That's why I want to suggest to extract all remix features to plugins for react router and install it optionally. I saw that the size of the package decreased in two times between 5 and 6 versions. It's impressive and I like changes. But that I see the size of the bundle was increased in 3 times. As part of this release remix features were added. I don't plan to use these features and would like to be able to disable them 

### Why should this feature be included?

it will help you understand how much these features are in demand by the community, if you make them optional

**Comment by brophdawg11** [comment]
Bundle size alone is not a reliable number.  All new Remix-inspired Data API functionality was added so that it is tree-shaken out if you don't use it, so if you're using `<BrowserRouter>` then your resulting app size should not be impacted by any of the new data APIs.  

If you see otherwise, please provide a working reproduction of the same app on `6.3` and `6.6` so we can compare resulting application bundle sizes.
