### ISSUE TITLE
[Bug]: loader cause components render twice

### ISSUE THREAD

**Issue by justBadProgrammer** [remix-run/react-router#9931]
### What version of React Router are you using?

"react-router-dom": "^6.6.2"

### Steps to Reproduce

Hi !
The example of code in sandbox:
https://codesandbox.io/s/condescending-cdn-qz0clq
You can see in console that each post renders twice

### Expected Behavior

When redirect from post to post have only one render  (new post render).

### Actual Behavior

The same post  renders twice:
first render: on visit post first time,
second render: on redirect to another post/postList

**Comment by timdorr** [comment]
This is expected behavior. When you click to load another post, it's firing the loader and waiting for the result. When this happens, the navigation state changes. This is so you can render something to indicate the loading state while you wait for the loader to resolve.

https://reactrouter.com/en/main/start/overview#pending-navigation-ui
