### ISSUE TITLE
[Bug]: ScrollRestoration does not work with nested routes when the route contains a parameter

### ISSUE THREAD

**Issue by atifc** [remix-run/react-router#9982]
### What version of React Router are you using?

6.5.0

### Steps to Reproduce

```javascript
function Layout() {
  return (
    <div>
      <div>
        <Navbar />
          <Outlet />
          <Footer />
        </div>
      </div>
      <ScrollRestoration
        getKey={(location, matches) => {
          return location.pathname;            
        }}
      />
    </div>
  );
}
```

```javascript
const router = createBrowserRouter(
  createRoutesFromElements(
    <Route path="/" element={<Layout />}>
      <Route path="rules" element={<Rules />} />
      <Route path="tour" element={<Tour />} />
      <Route path="c/:categoryShortName" element={<FrontPageCategory/>}/>
    </Route>
  )
);
```

### Expected Behavior

Scroll position should be restored even for the route with path "c/:categoryShortName".

### Actual Behavior

Scroll position is only restored for simple routes, such as "/rules", "/about", "/tour".

**Comment by atifc** [comment]
Worth noting is that I followed the example from, but did not use loaders. The elements load data via useEffect. Could this be the issue?

**Comment by brophdawg11** [comment]
Hard to say for sure without a working reproduction to look at. 

It could be the useEffect-data-loading, since if the data doesn't exist yet at render time, the page might not be tall enough for the restoration to work.  ScrollRestoration will work most reliably when data is loaded using loaders.  

Also make sure you're attempting to restore with the same param value since that would affect the getKey value.

**Comment by atifc** [comment]
Yes, this was it. Works fine with loaders. Thanks!
